apache/kylin

- website/_dev/dev_env.md
- website/_dev/howto_test.md
KYLIN-3305 Fix typos `kylin.job.run.as.remote.cmd`
> KYLIN-3305 Fix typos `kylin.job.run.as.remote.cmd`

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/util/DeployCoprocessorCLI.java
Called without a default parameter will result in
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
at org.apache.kylin.storage.hbase.util.DeployCoprocessorCLI.main(DeployCoprocessorCLI.java:118)
In 100 lines to determine if the first parameter of the command line is default, curIdx has ++, if the first parameter is not the default line 103, curIdx is re-++, resulting in the parameter misalignment.
> Analytic table name ArrayIndexOutOfBoundsException

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/lookup/LookupTableToHFileJob.java
In LookupTableToHFileJob#calculateShardNum
> KYLIN-3398 Fix inaccurate arithmetic operations

- jdbc/src/main/java/org/apache/kylin/jdbc/KylinConnection.java
- jdbc/src/test/java/org/apache/kylin/jdbc/DriverTest.java
So far, Kylin JDBC only satisfies domain/project pattern, but many companies use multi-path of domain. For example, domain/path/project. I improve this issue. @yiming187  Please review this issue.
> satisfy multi-path of domain for kylin connection (against master)

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/resources/kylin-defaults.properties
- core-common/src/test/java/org/apache/kylin/common/KylinConfigTest.java
- query/src/main/java/org/apache/kylin/query/QueryConnection.java
- query/src/test/java/org/apache/kylin/query/QueryConnectionTest.java
reported by https://issues.apache.org/jira/browse/KYLIN-3475
> KYLIN-3475 Make calcite connection is more configurable

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- core-metadata/src/main/java/org/apache/kylin/metadata/project/ProjectManager.java
- pom.xml
- server-base/pom.xml
- server-base/src/main/java/org/apache/kylin/rest/request/PrepareSqlRequest.java
- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
support cache preparedStatement in kylin sever, to save sql parse/optimize/implement time. Detail information can see in: https://issues.apache.org/jira/browse/KYLIN-3434
> KYLIN-3434 Support prepare statement in Kylin server side

- .travis.yml
While there are a lot of dependencies need to be downloaded from maven central enable Travis CI cache maven dependencies helps speed up the CI process.
See http://docs.travis-ci.com/user/caching/
> Enable Travis CI cache to speed up CI checks

- source-hive/src/main/java/org/apache/kylin/source/jdbc/JdbcHiveMRInput.java
Now sqoop home we used must end with '/bin' , which is not appropriate. It should be like "*/sqoop-client"
> KYLIN-3510 Correct sqoopHome at 'createSqoopToFlatHiveStep'

- build/script/download-tomcat.sh
- pom.xml
[SECURITY] CVE-2018-1336
Severity: High 
Versions Affected: Apache Tomcat 9.0.0.M9 to 9.0.7, 8.5.0 to 8.5.30, 8.0.0.RC1 to 8.0.51, and 7.0.28 to 7.0.86.
Description: An improper handing of overflow in the UTF-8 decoder with supplementary characters can lead to an infinite loop in the decoder causing a Denial of Service.
CVE-2018-8014
Description: The defaults settings for the CORS filter provided in Apache Tomcat 9.0.0.M1 to 9.0.8, 8.5.0 to 8.5.31, 8.0.0.RC1 to 8.0.52, 7.0.41 to 7.0.88 are insecure and enable 'supportsCredentials' for all origins. It is expected that users of the CORS filter will have configured it appropriately for their environment rather than using it in the default configuration. Therefore, it is expected that most users will not be impacted by this issue. …
> KYLIN-3553 Tomcat Security Vulnerability Alert. The version of the tomcat for kylin should upgrade to 7.0.90.

- core-metadata/src/main/java/org/apache/kylin/metadata/project/ProjectManager.java
https://issues.apache.org/jira/browse/KYLIN-3587
> KYLIN-3587 Including tableID in IllegalStateException messages

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/lookup/LookupTableHFilesBulkLoadJob.java
> KYLIN-3597 Improve code smell

- core-job/src/main/java/org/apache/kylin/job/execution/AbstractExecutable.java
- core-job/src/main/java/org/apache/kylin/job/execution/DefaultChainedExecutable.java
- core-job/src/main/java/org/apache/kylin/job/execution/ExecutableManager.java
- core-job/src/main/java/org/apache/kylin/job/impl/threadpool/DefaultScheduler.java
- core-job/src/test/java/org/apache/kylin/job/PersistExceptionExecutable.java
- core-job/src/test/java/org/apache/kylin/job/impl/threadpool/DefaultSchedulerTest.java
https://issues.apache.org/jira/projects/KYLIN/issues/KYLIN-3647
http://10.1.1.39/view/Kylin%20CI/job/kylin-manual-ci/205/
> KYLIN-3647 Fix inconsistent states of job and its sub-task

- core-metadata/src/main/java/org/apache/kylin/measure/hllc/DenseRegister.java
- core-metadata/src/main/java/org/apache/kylin/measure/hllc/HLLCounter.java
- core-metadata/src/test/java/org/apache/kylin/measure/hllc/HLLCounterTest.java
The current HLLCounter implementation has some room to improve performance, as we find in our product environment. Improvement related to getCountEstimate of HLLCounter and constructor of HLLCounter.
- Create HLLCounter from another HLLCounter, we can copy register(using System.arraycopy) instead of merge. (Constructor of HLLCounter)
- Precompute harmonic mean in the HLLCSnapshot to avoid doing this on the fly. (getCountEstimate of HLLCounter)
UnitTest has add cost duration compare.
> KYLIN-3656  Improve HLLCounter performance

- core-cube/src/test/java/org/apache/kylin/cube/cuboid/CuboidSchedulerTest.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/Segments.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/TableDesc.java
- core-metadata/src/test/java/org/apache/kylin/measure/topn/DoubleDeltaSerializerTest.java
Issue : https://issues.apache.org/jira/browse/KYLIN-3631
How to fix : 
1. Find all the Arrays.sort and replace with Arrays.parallelSort and add comments.
2. Run UT & integration tests to validate the fix.
> Fix issue : KYLIN-3631

- core-common/src/main/java/org/apache/kylin/common/util/ClassUtil.java
- core-dictionary/src/main/java/org/apache/kylin/dict/DictionaryInfoSerializer.java
- core-dictionary/src/main/java/org/apache/kylin/dict/DictionarySerializer.java
- core-dictionary/src/main/java/org/apache/kylin/dict/NumberDictionary.java
- core-dictionary/src/main/java/org/apache/kylin/dict/NumberDictionary2.java
- core-dictionary/src/main/java/org/apache/kylin/dict/TrieDictionary.java
- core-dictionary/src/main/java/org/apache/kylin/dict/TrieDictionaryForest.java
- core-dictionary/src/main/java/org/apache/kylin/dict/global/GlobalDictHDFSStore.java
- kylin-it/src/test/java/org/apache/kylin/jdbc/ITJDBCDriverTest.java
- query/src/main/java/org/apache/kylin/query/QueryConnection.java
- query/src/main/java/org/apache/kylin/query/relnode/OLAPAggregateRel.java
- server-base/src/test/java/org/apache/kylin/rest/bean/BeanValidator.java
Issue : https://issues.apache.org/jira/browse/KYLIN-3290
How to fix : Leverage getDecalredConstructor().newInstance() instead of newInstance()
> KYLIN-3290 Leverage getDecalredConstructor().newInstance() instead of newInstance()

- core-common/src/main/java/org/apache/kylin/common/BackwardCompatibilityConfig.java
- core-common/src/main/java/org/apache/kylin/common/KylinConfig.java
- core-common/src/main/resources/kylin-defaults.properties
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Kylin 2.6.0-SNAPSHOT:
[INFO]
[INFO] Apache Kylin ....................................... SUCCESS [  6.897 s]
[INFO] Apache Kylin - Core Common ......................... SUCCESS [ 14.739 s]
[INFO] Apache Kylin - Core Metadata ....................... SUCCESS [ 58.231 s]
[INFO] Apache Kylin - Core Dictionary ..................... SUCCESS [05:17 min]
[INFO] Apache Kylin - Core Cube ........................... SUCCESS [01:21 min]
[INFO] Apache Kylin - Core Metrics ........................ SUCCESS [  1.472 s]
[INFO] Apache Kylin - Core Job ............................ SUCCESS [ 43.913 s]
[INFO] Apache Kylin - Core Storage ........................ SUCCESS [  8.012 s]
[INFO] Apache …
> KYLIN-3597 fix sonar issues

- core-job/src/main/java/org/apache/kylin/job/dao/ExecutableDao.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/HBaseResourceStore.java
When any single file of Kylin's metadata miss in HDFS, the "Monitor" Page will failed to display all job info and kylin process will throw FileNotFoundException as above. The page has a warning message.
The better way should be : miss file should only affect specific task. And if only execute output miss, task should be success, otherwise that should be a fatal exeception. You have to fix it manually.
Test at https://issues.apache.org/jira/projects/KYLIN/issues/KYLIN-3406
> KYLIN-3406 Ignore execute output file lose

- build/bin/kylin.sh
- build/bin/set-java-home.sh
We believe that the following scenario is fairly common in big data communities:
1. Have CDH 5.x with JDK 1.7 (/usr/lib/jvm/java-7-oracle-cloudera)
2. Have JDK 1.8+ for other usage (e.g., kylin 2.5.2+ runs on 1.8+)
The added  set-java-home.sh will try to set JAVA_HOME before start or stop the server.
If JAVA_HOME is not set, under the above scenario, kylin server would try to start with JDK 1.7.  And many jars built after kylin 2.5.0 would NOT run on jdk 1.7.
> set JAVA_HOME before server start or stop

- engine-spark/src/main/java/org/apache/spark/sql/KylinSession.scala
When testing parquet storage, the spark session job failed to be submit for no JAVA_HOME in executor env. This config is set in the spark default property file: spark-defaults.conf.
```
2018-12-18,15:13:15,466 ERROR org.apache.spark.deploy.yarn.YarnAllocator: Failed to launch executor 6 on container container_e823_1541646991414_1025309_01_000007
java.util.NoSuchElementException: key not found: JAVA_HOME
at scala.collection.MapLike$class.default(MapLike.scala:228)
at scala.collection.AbstractMap.default(Map.scala:59)
at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
at org.apache.spark.deploy.yarn.ExecutorRunnable$$anonfun$prepareEnvironment$3$$anonfun$apply$3.apply(ExecutorRunnable.scala:286)
at org.apache.spark.deploy.yarn.ExecutorRunnable$$anonfun$prepareEnvironment$3$$anonfun$ …
```
> Kylin 3726: KylinSession should load spark properties from spark-defaults.conf

- storage-druid/src/main/java/org/apache/kylin/storage/druid/read/filter/PruneIntervalsProcessor.java
kylin on druid,when query like [select * from tb where dt='yyyyMMdd'] will no data return
fix query no data when partion column as filter
> fix query no data when partion column as filter 

- core-metadata/src/main/java/org/apache/kylin/metadata/cachesync/Broadcaster.java
Increase broadcast concurrency to avoid exceptions:
org.apache.kylin.job.exception.ExecuteException: org.apache.kylin.job.exception.ExecuteException: java.lang.NullPointerException
at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:178)
at org.apache.kylin.job.impl.threadpool.DistributedScheduler$JobRunner.run(DistributedScheduler.java:111)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kylin.job.exception.ExecuteException: java.lang.NullPointerException
at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:178)
at …
> KYLIN-3752 Increase broadcaster's concurrency to avoid exceptions

- core-common/src/main/java/org/apache/kylin/common/lock/DistributedLockFactory.java
- core-job/src/main/java/org/apache/kylin/job/JobInstance.java
- core-job/src/main/java/org/apache/kylin/job/execution/AbstractExecutable.java
- core-job/src/main/java/org/apache/kylin/job/execution/DefaultChainedExecutable.java
- core-job/src/main/java/org/apache/kylin/job/execution/ExecutableManager.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/JobInfoConverter.java
- server-base/src/main/java/org/apache/kylin/rest/service/JobService.java
- tool/src/main/java/org/apache/kylin/tool/JobInstanceExtractor.java
- webapp/app/partials/jobs/job_steps.html
In DistributedScheduler, it's hard to known which machine the kylin job is running on.
But this info is helpful to debug the failed jobs.
So we add the  job built instance info in job info and kylin web ui.
> KYLIN-3780: Add built instance in Job info

- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkUtil.java
The default string split method will remove empty values.  This will lose null column fields and cause ArrayIndexOutOfBoundsException in BaseCuboidBuilder.
Just fix it using string split with -1 limit.
See: https://stackoverflow.com/questions/14602062/java-string-split-removed-empty-values
> KYLIN-3494: Build cube with spark reports ArrayIndexOutOfBoundsException

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/util/DeployCoprocessorCLI.java
bugfix KYLIN-3822
101行运行完之后，curIdx的值为1，如果101行表达式为false，则args[curIdx]取到的参数为第二个参数，非第一个参数（第一个参数才代表localCoprocessorJar的地址）
> KYLIN-3822 fix the param parse error in DeployCoprocessorCLI

- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkFactDistinct.java
For environment with low RAM, and huge Cube, remove List to avoid java.lang.OutOfMemory and iterate by Iterator.
> KYLIN-3824

- engine-spark/src/main/java/org/apache/kylin/engine/spark/KylinKryoRegistrator.java
After patch was applied in my env, i test it.
In my test case, i set properties
kylin.engine.spark-conf.spark.driver.memory=2G
kylin.engine.spark-conf.spark.executor.memory=512M
Launch build a huge cube, with no mapreduce.input.fileinputformat.split at all.
The most huge data goes to executor 20 (4.6G) and spark spilling process goes here:
2019-02-26 17:55:13 INFO  ShuffleBlockFetcherIterator:54 - Getting 3898 non-empty blocks out of 3898 blocks
2019-02-26 17:55:13 INFO  ShuffleBlockFetcherIterator:54 - Started 6 remote fetches in 39 ms
2019-02-26 17:55:15 INFO  ExternalAppendOnlyMap:54 - Thread 34 spilling in-memory map of 97.5 MB to disk (1 time so far)
2019-02-26 17:55:40 INFO  ExternalAppendOnlyMap:54 - Thread 34 spilling in-memory map of 97.5 MB to disk (2 times so far)
2019-02-26 …
> KYLIN-3714 Register kryo for spark spilling process.

- core-job/src/main/java/org/apache/kylin/job/execution/DefaultChainedExecutable.java
- core-job/src/main/java/org/apache/kylin/job/execution/ExecutableManager.java
See KYLIN-3817.
After building the cube for a few minutes, click the Refresh button and the duration of the job becomes negative.
This bug is introduced in KYLIN-3780: https://github.com/apache/kylin/pull/442/commits/b3728040e39bf32412624907e493f666c49dfb5c
> KYLIN-3817: Duration in Cube building is a negative number

- core-metadata/src/main/java/org/apache/kylin/metadata/datatype/DataType.java
See: https://issues.apache.org/jira/browse/KYLIN-3880
> KYLIN-3880: DataType is incompatible in Kylin HBase coprocessor

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/lookup/LookupTableToHFileJob.java
See: https://issues.apache.org/jira/browse/KYLIN-3888
> KYLIN-3888 TableNotDisabledException when running "Convert Lookup Table to HFile"

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/BulkLoadJob.java
See: https://issues.apache.org/jira/browse/KYLIN-3884
Delete the temporary dir before loading hfiles to HBase tables.
> KYLIN-3884: loading hfile to HBase failed for temporary dir in output path

- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java
See: https://issues.apache.org/jira/browse/KYLIN-3886
The app id may be empty which cause the yarn command failed for missing argument.
Checking the app id before executing yarn command
> KYLIN-3886:  Missing argument for options for yarn command

- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkBatchMergeJobBuilder2.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkMergingDictionary.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/UpdateDictionaryStep.java
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3851
> KYLIN-3851 Flink cubing step : merge dictionary

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
In dev mail list's discussion, I suggest to enable shrunken dictionary by default, and received some dev's aggrement. 
When using bitmap measure on a large cardinality column(require global dictionaty), build base cuboid step need frequent cache swap so it cannot finished within a reasonable period.
When shrunken dictionary enabled, a new step will be added to build separated dictionary for each `InputSplit`, Mapper of *BuildBaseCuboid* step only has to fetch a smaller dictionary for itself, instead of a larger global dictionary. It will reduce cache swap and make *BuildBaseCuboid* step run as quicker as possible.
> KYLIN-3905 Enable shrunken dictionary default

- jdbc/src/main/java/org/apache/kylin/jdbc/KylinClient.java
This update intends to make the code to handle HTTP connection releasing not confusing. 
Issue description is at https://issues.apache.org/jira/browse/KYLIN-3908
> KYLIN-3908 KylinClient's HttpRequest.releaseConnection is not needed in retrieveMetaData & executeKylinQuery

- core-job/src/main/java/org/apache/kylin/job/JobInstance.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/JobInfoConverter.java
- server-base/src/main/java/org/apache/kylin/rest/service/JobService.java
- tool/src/main/java/org/apache/kylin/tool/JobInstanceExtractor.java
- webapp/app/js/model/cubeConfig.js
- webapp/app/partials/cubes/cubes.html
- webapp/app/partials/jobs/job_steps.html
See: https://issues.apache.org/jira/browse/KYLIN-3918
> KYLIN-3918: Add project name in cube and job pages

- stream-source-kafka/src/main/java/org/apache/kylin/stream/source/kafka/KafkaSource.java
KafkaSource load method need kafka propeties to structure kafkaConsumer; but default code can not pass cube overwrite properties to use
like : 
kylin.source.kafka.config-override.security.protoco SASL_PLAINTEXT
kylin.source.kafka.config-override.sasl.mechanism PLAIN
kylin.source.kafka.config-override.sasl.jaas.config sasl.jaas.config
kylin.source.kafka.config-override.group.id group_id
https://issues.apache.org/jira/browse/KYLIN-3932
> KYLIN-3932 KafkaConfigOverride to take effect

- stream-source-kafka/pom.xml
- stream-source-kafka/src/main/java/org/apache/kylin/stream/source/kafka/TimedJsonStreamParser.java
- stream-source-kafka/src/test/java/org/apache/kylin/stream/source/kafka/TimedJsonStreamParserTest.java
- stream-source-kafka/src/test/resources/message.json
- webapp/app/js/controllers/sourceMeta.js
Currently real-time OLAP didn't support  multi-level json event.
For example,if I have a kafka multi-level json event like this:
```json
{"country":"JAPAN","amount":13.075058425023922,"qty":8,"currency":"USD","order_time":1554801950882,"category":"ELECTRONIC","device":"Andriod","user":{"gender":"Female","id":"7a0cfa5e-bbaa-79ef-1a38-e06f02c85fcb","first_name":"unknown","age":16}}
```
```
2019-04-09 09:46:09,878 ERROR [StreamingV2Cube_channel] kafka.TimedJsonStreamParser:107 : error
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
at [Source: (String)"\{"country":"US","amount":14.498498222823619,"qty":1,"currency":"USD","order_time":1554803169876,"category":"Other","device":"Other","user":{"gender":"Fema …
```
> KYLIN-3942 Support multi-level json event in backend

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-job/src/main/java/org/apache/kylin/job/JoinedFlatTable.java
- core-job/src/main/java/org/apache/kylin/job/util/FlatTableSqlQuoteUtils.java
- core-job/src/test/java/org/apache/kylin/job/util/FlatTableSqlQuoteUtilsTest.java
- source-hive/src/main/java/org/apache/kylin/source/hive/GarbageCollectionStep.java
- source-hive/src/test/java/org/apache/kylin/source/hive/HiveMRInputTest.java
- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/JdbcHiveInputBase.java
- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/extensible/JdbcHiveInputBase.java
- source-kafka/src/main/java/org/apache/kylin/source/kafka/KafkaInputBase.java
1. add quote for create table ddl
2. add switch for turn off quote
> KYLIN-3857 Disable quote when needed

- core-job/src/main/java/org/apache/kylin/job/execution/ExecutableManager.java
- server-base/src/main/java/org/apache/kylin/rest/controller/JobController.java
- server-base/src/main/java/org/apache/kylin/rest/service/JobService.java
The command "pause" only sets status of the job to "stopped" and does not reset the status of the subtask.https://github.com/apache/kylin/blob/e9dfaf9a5465ff3f6f3bfa3460ca8b2adb8c6617/server-base/src/main/java/org/apache/kylin/rest/service/JobService.java#L662-L666
So, In SparkExecutable, we can't get the real status of the running task. https://github.com/apache/kylin/blob/e9dfaf9a5465ff3f6f3bfa3460ca8b2adb8c6617/engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java#L293-L300
> KYLIN-3936 MR/Spark task will still run after the job is stopped

- webapp/app/js/controllers/cubeMeasures.js
In the cubeMeasures.js, It will withdraw precision and scale by using Regular Expression. The scale parameter is ok, but precision use the magic number 19.
So we fixed it, In cubeMeasures.js, around line 469:
“var precision = 19;”  --> "var precision = returnValue[2] || 0;"
and we test ok including building cube and querying when the column is decimal(38,18).
> KYLIN-3968 Customized precision doesn't work in web

- engine-mr/src/test/java/org/apache/kylin/engine/mr/common/DefaultX509TrustManagerTest.java
- engine-mr/src/test/java/org/apache/kylin/engine/mr/common/HadoopCmdOutputTest.java
Added additional Unit Tests to increase code coverage.
> Add unit tests three

- stream-core/src/main/java/org/apache/kylin/stream/core/source/MessageParserInfo.java
- stream-source-kafka/src/main/java/org/apache/kylin/stream/source/kafka/AbstractTimeParser.java
- stream-source-kafka/src/main/java/org/apache/kylin/stream/source/kafka/DateTimeParser.java
- stream-source-kafka/src/main/java/org/apache/kylin/stream/source/kafka/LongTimeParser.java
- stream-source-kafka/src/main/java/org/apache/kylin/stream/source/kafka/TimedJsonStreamParser.java
- webapp/app/js/controllers/sourceMeta.js
- webapp/app/partials/tables/loadStreamingTableConfig.html
- webapp/app/partials/tables/table_detail.html
**Allow user-specified time format using real-time**
I found that real-time only supports millisecond timestamp, does not support second timestamp and  Date type like '2019-01-01 11:11:11'.
I add a LongTimeParser and a DateTimeParser and page configuration 
You can configure tsParser, tsPattern on the page that creates the streaming table.
- for date :
`{ "timestamp":"2019-04-29 11:11:11","gmv":1.1 }`
`tsParser=org.apache.kylin.stream.source.kafka.DateTimeParser`
`tsPattern=yyyy-MM-dd HH:mm:ss`
- for second  : 
`{ "timestamp":"1556618887","gmv":1.1 }`
`tsParser=org.apache.kylin.stream.source.kafka.LongTimeParser`
`tsPattern=S`
- for millisecond : 
`{ "timestamp":"1556618887000","gmv":1.1 }`
`tsParser=org.apache.kylin.stream.source.kafka.LongTimeParser`
`tsPattern=MS`
> KYLIN-4001 Allow user-specified time format using real-time

- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- server-base/src/main/java/org/apache/kylin/rest/job/MetadataCleanupJob.java
- server-base/src/main/java/org/apache/kylin/rest/job/StorageCleanJobHbaseUtil.java
- server-base/src/main/java/org/apache/kylin/rest/job/StorageCleanupJob.java
See: https://issues.apache.org/jira/browse/KYLIN-3994
> KYLIN-3994: StorageCleanupJob may delete cube id data of new built segment because of cube cache in CubeManager

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/java/org/apache/kylin/common/util/BufferedLogger.java
- core-common/src/main/java/org/apache/kylin/common/util/Logger.java
- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- core-metadata/src/main/java/org/apache/kylin/metadata/cachesync/CachedCrudAssist.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/DataModelManager.java
- server-base/src/main/java/org/apache/kylin/rest/job/KylinHealthCheckJob.java
- tool-assembly/pom.xml
- tool/src/main/java/org/apache/kylin/tool/KylinHealthCheckJob.java
See: https://issues.apache.org/jira/browse/KYLIN-3997
> KYLIN-3997: Add a health check job of Kylin

- .travis.yml
- source-kafka/src/main/java/org/apache/kylin/source/kafka/util/KafkaClient.java
Add an overwrite method getKafkaConsumer() for KafkaClient.
Add method getKafkaConsumer() with the default properties from KafkaConsumerProperties.
The class KafkaConsumerProperties can load kafka config from conf/kylin-kafka-consumer.xml.
> add overwrite method getKafkaConsumer in KafkaClient

- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/UHCDictionaryJob.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/filter/UHCDictPathFilter.java
KYLIN-4015 "Build UHC Dictionary" step filter ".dci" files to solve the problem that MR engine run failed because the ".dci" file is  not a  sequence file.
> KYLIN-4015 "Build UHC Dictionary" step filter ".dci" files 

- core-common/src/main/java/org/apache/kylin/common/util/ZKUtil.java
- core-job/src/main/java/org/apache/kylin/job/lock/zookeeper/ZookeeperDistributedLock.java
```
【Type】：BUG 
【Severity】：1-Blocker
【Module】：Build Engine
【Description】：Kylin build engine occasionally appears to be unable to get the ZK lock exception, and once this build engine appears, it will not work and can only be restarted to solve.Usually this problem will recur one day after the build engine starts.
【Design】：Setting the cache for curator is never invalid (unless the service stops) and check the state before use curator instance (if closed ,create a new curator instance and put into the cache)
```
```
issue: https://issues.apache.org/jira/browse/KYLIN-4017
```
> KYLIN-4017 Build engine get zk(zookeeper) lock failed when building job, it causes the whole build engine doesn't work

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
> KYLIN-3999, make kylin.query.enable-dynamic-column default true

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkColumnCardinality.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java
- server-base/src/main/java/org/apache/kylin/rest/service/TableService.java
link to https://issues.apache.org/jira/browse/KYLIN-4035
Support calculating column cardinality by using spark engine
> KYLIN-4035 Calculate column cardinality by using spark engine

- core-job/pom.xml
- core-job/src/main/java/org/apache/kylin/job/lock/zookeeper/ZookeeperDistributedLock.java
- core-job/src/main/java/org/apache/kylin/job/lock/zookeeper/exception/ZkAcquireLockException.java
- core-job/src/main/java/org/apache/kylin/job/lock/zookeeper/exception/ZkPeekLockException.java
- core-job/src/main/java/org/apache/kylin/job/lock/zookeeper/exception/ZkPeekLockInterruptException.java
- core-job/src/main/java/org/apache/kylin/job/lock/zookeeper/exception/ZkReleaseLockException.java
- core-job/src/main/java/org/apache/kylin/job/lock/zookeeper/exception/ZkReleaseLockInterruptException.java
- core-job/src/main/java/org/apache/kylin/job/util/ThrowableUtils.java
- core-job/src/test/java/org/apache/kylin/job/lock/zookeeper/ZookeeperDistributedLockTest.java
KYLIN-4039, fix ZK distributed lock may not release lock when catching interrupt exception,
Please see: https://issues.apache.org/jira/browse/KYLIN-4039
> KYLIN-4039, fix ZK distributed lock may not release lock

- server/pom.xml
Cubing job will failed with kylin.source.hive.client=beeline when I launch Kylin Server locally.
> Minor, add Hive JDBC dependency for DebugTomcat

- core-metadata/src/main/java/org/apache/kylin/exception/QueryOnCubeException.java
- core-metadata/src/main/java/org/apache/kylin/metadata/expression/BinaryTupleExpression.java
- core-metadata/src/test/java/org/apache/kylin/metadata/expression/TupleExpressionTest.java
- query/src/main/java/org/apache/kylin/query/util/PushDownUtil.java
Scene：
SQL:select round (car_dismatch_cnt*100/answer_order_cnt, 4) from db.table1.
- 1、Executes the SQL on a  project where its cube has db.table1,it will throws the right side of the BinaryTuple Expressions columns is not supported for / exception and is not queried through pushdown;
- 2、When change a project where not create the table cube , the same query  can be executed to push down and get the right result.
- 3、 Expect that no matter whether a table cube is created or not, when the cube query is not success, the result can still be obtained by pushdown query, which will give users a consistent experience.
> KYLIN-4047 Use push-down query when division dynamic column cube query is not supported

- build/bin/kylin-port-replace-util.sh
In Kylin3.0, we introduce new real-time OLAP feature. When you use "kylin-port-replace-util.sh" to change listen port used by Kylin and use "kylin.sh start" to start a Coordinator. If you
forget to set "kylin.stream.node" to new port, Coordinator will register its address into ZK using wrong port, that will make receiver cannot connect to Coordinator. That will create a mis-understand exception in all receivers and confused user.
> KYLIN-4084 Reset kylin.stream.node in kylin-port-replace-util.sh

- jdbc/src/main/java/org/apache/kylin/jdbc/KylinResultSet.java
- pom.xml
JDBC driver fails either in Tableau or Apache Drill - the issue is that KylinConnection class derived from AvaticaConnection throws NonImplementedException for isValid method in Avatica 1.10 - that was fixed in Avatica 1.12 in this commit https://github.com/apache/calcite-avatica/commit/50d45f989ee7a8eae0456dee7a88c5fa4d9d8b5a#diff-88cfeb980a0b86ea07f69cb4f3352646L376. 
After upgrading to avatica 1.12 Tableau is able to connect to Kylin.
> Upgraded avatica/calcite version

- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- query/src/main/java/org/apache/kylin/query/enumerator/LookupTableEnumerator.java
In some case, cube returned by findLatestSnapshot didn't contains the snapshot table
for what you need. Because some dimension which exists in model but was removed in cube design phase, query such as "select * from LookupTable" will throw unexpected exception and confused user.
> KYLIN-3628 Fix unexpected exception for select from Lookup Table

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- stream-core/src/main/java/org/apache/kylin/stream/core/consumer/StreamingConsumerChannel.java
- stream-core/src/main/java/org/apache/kylin/stream/core/metrics/StreamingMetrics.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/StreamingSegmentManager.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/ColumnarSegmentStore.java
- stream-receiver/src/main/java/org/apache/kylin/stream/server/StreamingServer.java
Use absolute path instead of relative path for local segment cache may cause unpredicted result. After restart receiver, if working directory change, Receiver cannot find segment data/checkpoint which created previously, and recreate new one, which is a serious problem.
> KYLIN-4081 Use absolute path instead of relative for local segment cache

- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkCubingByLayer.java
See: https://issues.apache.org/jira/browse/KYLIN-4099
> KYLIN-4099: Using no blocking RDD unpersist in spark cubing job

- pom.xml
Jacoco 0.8.2 adds Java 11 support. We should upgrade Jacoco.
> [KYLIN-3519] Upgrade Jacoco version to 0.8.2

- webapp/app/js/controllers/cubeSchema.js
KYLIN-4067 optimize the kylin cube page loading mechanism. Get all information of cubes only when adding a new cube.
> KYLIN-4067 optimize the kylin cube page loading mechanism.

- build/bin/kylin.sh
- build/conf/setenv-tool.sh
See: https://issues.apache.org/jira/browse/KYLIN-4092
> KYLIN-4092: Support setting seperate jvm params for kylin backgroud tools

- engine-mr/src/main/java/org/apache/kylin/engine/mr/CubingJob.java
- server-base/src/main/java/org/apache/kylin/rest/service/CubeService.java
Fix the bug that when we discard one job, Kylin's monitoring mechanism always creates the same new job.
> KYLIN-4057 Don't merge the job that has been discarded manually before.

- kylin-it/src/test/resources/query/sql_intersect_count/query01.sql
- kylin-it/src/test/resources/query/sql_intersect_count/query03.sql
- query/src/main/java/org/apache/kylin/query/relnode/OLAPProjectRel.java
In query of intersect_count, says `intersect_count(OPS_USER_ID, part_dt, array[date '2012-01-01',date '2012-01-02'])`, we need to specific data type of each entry in array, if *date* miss, return value will be 0, which will mislead user. So I think we should auto adjust data type of each entry from string/char to real data type.
> KYLIN-4117 Auto adjust data type of RelNode for intersect_count

- server-base/src/main/java/org/apache/kylin/rest/job/StorageCleanJobHbaseUtil.java
- server-base/src/main/java/org/apache/kylin/rest/job/StorageCleanupJob.java
- server-base/src/test/java/org/apache/kylin/rest/job/StorageCleanJobHbaseUtilTest.java
See: https://issues.apache.org/jira/browse/KYLIN-3901
The pr only implement the multi-thread cleanup for hbase tables
> KYLIN-3901: Use multi threads to speed up the storage cleanup job

- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java
See: https://issues.apache.org/jira/browse/KYLIN-4112
> KYLIN-4112: Add hdfs keberos token delegation in Spark to support se and MR use different HDFS clusters

- server/src/test/java/org/apache/kylin/rest/service/AdminServiceTest.java
The commit ["Add time filter for current day jobs"](https://github.com/apache/kylin/commit/ebff43a81eeac79429138d2be1ab7a9a0d5f41f3) whose commit id is 
ebff43a81eeac79429138d2be1ab7a9a0d5f41f3 will cause Test case AdminServiceTest. testGetPublicConfig() error because expected kyiln config is unequal with kylin-default.properties
> Fix admin service test error 

- core-job/src/main/java/org/apache/kylin/job/JoinedFlatTable.java
- core-job/src/main/java/org/apache/kylin/job/JoinedFormatter.java
- core-job/src/test/java/org/apache/kylin/job/JoinedFormatterTest.java
- webapp/app/partials/modelDesigner/conditions_settings.html
**Description**
The users can use ${START_DATE} and ${END_DATE} in where filter which in the WebUI.
And the dynamic variables ${START_DATE} and ${END_DATE} are from the building date of Cube.
#
Refer-issue: https://issues.apache.org/jira/browse/KYLIN-4156
> Add JoinedFormatter for dynamic variables in where sentence

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/cube/v2/coprocessor/endpoint/generated/CubeVisitProtos.java
See: https://issues.apache.org/jira/browse/KYLIN-3973
Notice: This is just a quick fix, not the best solution.  The best way is using shaded protobuf:2.5.0
> KYLIN-3973: InvalidProtocolBufferException

- server-base/src/main/java/org/apache/kylin/rest/service/TableService.java
Load table metadata from tree in 'Data Source' tab, then choose one database, you will find the intermediate tables are also loaded, But intermediate tables are the inner tables, which should not be showed to client, so I filter them in the kylin server.
> KYLIN-4176 Filter the intermediate tables when loading table metadata from tree

- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/FragmentSearchResult.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/RawRecord.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/compress/RunLengthCompressedColumnReader.java
issue link : https://issues.apache.org/jira/browse/KYLIN-4184
> fix KYLIN-4184 Real time OLAP query gets wrong result

- webapp/app/js/controllers/query.js
https://issues.apache.org/jira/browse/KYLIN-1716
> KYLIN-1716 Insight routing error fix

- webapp/app/js/controllers/cubes.js
When the segment is not selected, "$scope.lookup.select.segments" will be undefined, which will cause this problem.
> KYLIN-4183 Clicking 'Submit' button is unresponsive, when the segment is not selected.

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-dictionary/src/main/java/org/apache/kylin/dict/AppendTrieDictionary.java
- core-dictionary/src/test/java/org/apache/kylin/dict/AppendTrieDictionaryTest.java
Reverts apache/kylin#760 for now duo to Failure of regression test.
> Revert "KYLIN-4097: Throw exception when too many dict slice evictions in AppendTrieDictionary"

- stream-core/src/main/java/org/apache/kylin/stream/core/util/NodeUtil.java
Support three kylin.stream.node config format, ip:prot or port or not set the config.
- if set ip:port , then kylin will set the config ip and port as the currentNode,
- if set port only, then kylin will get the node ip address and set the node ip and port as the currentNode,
- if not set the config ,then kylin will get the node hostname address and set the hostname and defaultPort(7070) as the currentNode.
issue link: https://issues.apache.org/jira/browse/KYLIN-4208
> KYLIN-4208 RT OLAP kylin.stream.node configure optimization support all receiver can have the same config

- webapp/app/js/controllers/page.js
The reason is that when I perform the purge operation, the size_kb parameter returned by the Kylin server is null.
So we can judge whether the input parameter is null in function dataSize, if data is null, return 0 KB.
> KYLIN-4195 The cube size is 'NaN KB' after purging one cube.

- server-base/src/main/java/org/apache/kylin/rest/security/PasswordPlaceholderConfigurer.java
Usage instructions in 'PasswordPlaceholderConfigurer' doesn't work
> KYLIN-4242: Usage instructions in 'PasswordPlaceholderConfigurer' doesn't work

- build/deploy/server.xml
1. change the default decoding to 'UTF-8' in tomcat's server.xml
> KYLIN-4254: Export from Insight with CSV format error, when sql contains Chinese

- stream-core/src/main/java/org/apache/kylin/stream/core/query/StreamingDataQueryPlanner.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/ColumnarSegmentStoreFilesSearcher.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/FragmentSearchResult.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/compress/NoCompressedColumnReader.java
- stream-core/src/test/java/org/apache/kylin/stream/core/storage/StreamingSegmentManagerTest.java
1. When real-time query group by minute_start and filter by another column, the aggregate result maybe not correct, the issue has been addressed in KYLIN-4184 , the fix is good, but in  
NoCompressedColumnReader class, the readBuffer bytes is still shared, it is a potential issue, need to be fixed.
2. When filter by a minute_start range, the first minute data may not be correct, it is caused by:https://github.com/apache/kylin/blob/master/stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/ColumnarSegmentStoreFilesSearcher.java#L68, the fragment's max time is inclusive, but this method's max time is exclusive, that may skip some fragments for the first minute by mistake.
3. Add some UT to cover these two cases.
> KYLIN-4258 Real-time OLAP may return incorrect result for some case

- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/Coordinator.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/coordinate/BuildJobSubmitter.java
- stream-coordinator/src/test/java/org/apache/kylin/stream/coordinator/coordinate/BuildJobSubmitterTest.java
- stream-coordinator/src/test/java/org/apache/kylin/stream/coordinator/coordinate/StreamingTestBase.java
Make cube planner works for real-time streaming job:
1, when no ready segment is ready for streaming cube, only 1 segment is allow to build, ensure that the 1st phrase cube planner will take effective
2, when there are any optimization job is running, stop new segment building for streaming cube
> KYLIN-4273 Make cube planner works for real-time streaming job

- webapp/app/js/controllers/query.js
https://issues.apache.org/jira/browse/KYLIN-1716
> fix location change url error

- core-common/src/main/java/org/apache/kylin/common/StorageURL.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/PartitionDesc.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/CuboidStatsReaderUtil.java
- server-base/src/main/java/org/apache/kylin/rest/controller/StreamingV2Controller.java
I run FindsBugs against Kylin codebase and find some potential NPE bugs.  
related class:
org.apache.kylin.metadata.model.PartitionDesc
org.apache.kylin.engine.mr.common.CuboidStatsReaderUtil
org.apache.kylin.rest.controller.StreamingV2Controller
org.apache.kylin.common.StorageURL
> KYLIN-4259 fix potential NPE bug reported by FindBugs

- build/bin/kylin.sh
When we restart the Kylin instance, due to the slow start of kylin, some monitoring scripts fail to detect the surviving kylin, and will also start the kylin instance. As a result, there are multiple kylin instances on a node.
By adding a file lock to the startup script (kylin.sh), it is guaranteed that only one kylin instance will be started when concurrent startup on a node.
> KYLIN-4290: Add file lock to kylin startup script to avoid starting multiple instances on one node

- webapp/app/js/model/projectConfig.js
refer to `/webapp/app/js/filters/filter.js`, projects are sorted by their attribute value. There is a wrong attribute name in `projectConfig.js`.
see [KYLIN-4304](https://issues.apache.org/jira/browse/KYLIN-4304)
> KYLIN-4304 Project list cannot be correctly sorted by 'Create Time'

- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/JdbcExplorer.java
- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/JdbcSource.java
See: https://issues.apache.org/jira/browse/KYLIN-4235
> KYLIN-4235 Failed to load table metadata from JDBC data source

- core-job/src/main/java/org/apache/kylin/job/impl/threadpool/DefaultFetcherRunner.java
- core-job/src/main/java/org/apache/kylin/job/impl/threadpool/PriorityFetcherRunner.java
https://issues.apache.org/jira/browse/KYLIN-4250
> KYLIN-4250 FechRunnner should skip the job to process other jobs instead of throwing exception when the job section metadata is not found

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/java/org/apache/kylin/common/util/ToolUtil.java
- core-common/src/test/java/org/apache/kylin/common/util/ToolUtilTest.java
- core-job/src/main/java/org/apache/kylin/job/impl/threadpool/DistributedScheduler.java
- tool/src/main/java/org/apache/kylin/tool/AbstractInfoExtractor.java
- tool/src/main/java/org/apache/kylin/tool/DiagnosisInfoCLI.java
- tool/src/main/java/org/apache/kylin/tool/JobDiagnosisInfoCLI.java
- tool/src/main/java/org/apache/kylin/tool/KylinLogExtractor.java
1. DistributedScheduler can selectively assign task nodes according to cube extra configuration
2. move `ToolUtil` to `core-common` module to avoid module cycle
>  KYLIN-4249:DistributedScheduler can selectively assign task nodes according to cube extra configuration

- build/bin/kylin.sh
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- pom.xml
- server-base/pom.xml
- server-base/src/main/java/org/apache/kylin/rest/controller/UserController.java
- server-base/src/main/java/org/apache/kylin/rest/security/cas/CasUserDetailsService.java
- server-base/src/main/java/org/apache/kylin/rest/security/saml/SAMLSimpleUserDetailsService.java
- server-base/src/main/java/org/apache/kylin/rest/service/KylinUserService.java
- server/src/main/resources/applicationContext.xml
- server/src/main/resources/kylin-security-cas-plugin.xml
- server/src/main/resources/kylin-security-saml-noldap-plugin.xml
- server/src/test/java/org/apache/kylin/rest/service/AdminServiceTest.java
- webapp/app/js/controllers/auth.js
- webapp/app/partials/login.html
KYLIN-4240 use kylin SSO without LDAP. see: https://issues.apache.org/jira/browse/KYLIN-4240
first we change `kylin.sh` to support multiple profiles (`spring.profiles.active` can accept a list of profiles)
```
additional_security_profiles=`bash ${dir}/get-properties.sh kylin.security.additional-profiles`
if [[ "x${additional_security_profiles}" != "x" ]]; then
spring_profile="${spring_profile},${additional_security_profiles}"
fi
```
In front-end, a button is added to redirect to the CAS/SAML server.
User can now login with either username/password or SSO, and their groups can be managed in the `System` tab.
Here we add `server/resources/kylin-security-cas-plugin.xml` to configure Spring Security for CAS, 
defining the following beans under `authn-cas` profile, and filters only `/cas/**`: …
> KYLIN-4240 Kylin SSO with CAS or SAML without LDAP

- build/script/package.sh
Releast test failure because there is a commit in Flink engine  add `sh build/script/download-spark.sh` to package.sh.
This will delete the dir of jenkins SPARK_HOME and result in 'spark not found'.
From v2.6.1, Kylin have not provide Spark binary anymore. So `sh build/script/download-spark.sh` should be deleted from package.sh.
> Fix release test failure

- core-common/src/main/java/org/apache/kylin/common/util/FIFOIterator.java
- core-common/src/main/java/org/apache/kylin/common/util/ImmutableBitSet.java
- core-metadata/src/main/java/org/apache/kylin/source/datagen/ColumnGenerator.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/cube/v2/ExpectedSizeIterator.java
JIRA: https://issues.apache.org/jira/browse/KYLIN-4311
By contract, any implementation of the java.util.Iterator.next() method should throw a NoSuchElementException exception when the iteration has no more elements. Any other behavior when the iteration is done could lead to unexpected behavior for users of this Iterator.
https://sonarcloud.io/project/issues?id=org.apache.kylin%3Akylin&issues=AWExwNw9ikuHJGLsvan_&open=AWExwNw9ikuHJGLsvan_
https://sonarcloud.io/project/issues?id=org.apache.kylin%3Akylin&issues=AWExwNxOikuHJGLsvaoZ&open=AWExwNxOikuHJGLsvaoZ
https://sonarcloud.io/project/issues?id=org.apache.kylin%3Akylin&issues=AWExwOHQikuHJGLsvbDO&open=AWExwOHQikuHJGLsvbDO
> KYLIN-4311 fix noncompliant interator issue in sonar

- server-base/src/main/java/org/apache/kylin/rest/controller/ServiceDiscoveryStateController.java
- webapp/app/js/controllers/instances.js
Query Node can't get allParticipants because query node no need to run job scheduler, so the jobClient is null.
Job Node:
Query Node:
We can add instance of the mode  equals ‘job’ or ‘all’ to job node list in query server, but query server can not find which job node is Leader. In order to avoid instance page display a leader as a follower by mistake, just display the Leader of job node as Job Node (Leader), the others display as Job Node.
Job Node:
Query Node:
> KYLIN-4295 Instances displayed on Query Node are inconsistent with JobNode

- core-job/src/main/java/org/apache/kylin/job/dao/ExecutableDao.java
delete both /execute and /execute_output metadata when deleting a job.
compress commit #1026
> delete /execute_output metadata at the same time when deleting a job

- core-cube/src/main/java/org/apache/kylin/cube/gridtable/CuboidToGridTableMappingExt.java
- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/framework/FixedCachedRowSetImpl.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutableLivy.java
https://issues.apache.org/jira/browse/KYLIN-4331
When a method in a child class has the same signature as a method in a parent class, it is assumed to be an override. However, that's not the case when:
the parent class method is static and the child class method is not.
the arguments or return types of the child method are in different packages than those of the parent method.
the parent class method is private.
Typically, these things are done unintentionally; the private parent class method is overlooked, the static keyword in the parent declaration is overlooked, or the wrong class is imported in the child. But if the intent is truly for the child class method to be different, then the method should be renamed to prevent confusion.
  …
> KYLIN-4331 Fix noncompliant method names in child class

- core-common/src/main/java/org/apache/kylin/common/metrics/metrics2/CodahaleMetrics.java
- core-common/src/main/java/org/apache/kylin/common/persistence/ResourceStore.java
- core-metadata/src/main/java/org/apache/kylin/measure/percentile/PercentileSerializer.java
- core-metadata/src/main/java/org/apache/kylin/measure/topn/DoubleDeltaSerializer.java
- core-metadata/src/main/java/org/apache/kylin/metadata/datatype/DataTypeSerializer.java
- issue link :https://issues.apache.org/jira/browse/KYLIN-4333
- Internalthreadlocal is not suitable for creating a large number of instances . Otherwise, memory leakage will occur, leading to frequent full GC and even OOM.
> KYLIN-4333 Fix Build Server OOM

- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/client/HttpCoordinatorClient.java
This fix is based on similar methods in this repository, as described below.
https://github.com/apache/kylin/blob/f41c6c8198e5cad295e9212c6a0047d83bd54ae2/stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/client/HttpCoordinatorClient.java#L226-L236
https://github.com/apache/kylin/blob/f41c6c8198e5cad295e9212c6a0047d83bd54ae2/stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/client/HttpCoordinatorClient.java#L238-L248
https://github.com/apache/kylin/blob/f41c6c8198e5cad295e9212c6a0047d83bd54ae2/stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/client/HttpCoordinatorClient.java#L250-L260
> Making uniform position of variable declaration statements

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/lookup/LookupTableToHFileJob.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/CreateHTableJob.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/CubeHFileJob.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/HFileOutputFormat3.java
Backport HBASE-22887 to Kylin HFileOutputFormat3
1. add HFileOutputFormat3 copy from HBase's (V2.0.0) org.apache.hadoop.hbase.mapreduce.HFileOutputFormat2, with HBASE-22887 fixed. see more [KYLIN-4293](https://issues.apache.org/jira/browse/KYLIN-4293)
2. copy 3 more Function from HBase's org.apache.hadoop.hbase.mapreduce.MultiTableHFileOutputFormat, so that it's protected can be used. 
3. with KYLIN-3317, replace UUID.randomUUID with new UUID applied.
Signed-off-by: langdamao <lang--lang--lang@163.com>
> KYLIN-4293 Backport HBASE-22887 to Kylin HFileOutputFormat3

- server-base/src/main/java/org/apache/kylin/rest/controller/MetricsController.java
- server-base/src/main/java/org/apache/kylin/rest/service/MetricsService.java
- server/src/main/resources/kylinSecurity.xml
- server/src/test/java/org/apache/kylin/rest/controller/MetricsControllerTest.java
1.  Expose metrics through http api to facilitate the integration of some external monitoring components, such as tsdb
2. add a python script for tcollector
> KYLIN-4294: Add http api for metrics

- core-common/src/main/java/org/apache/kylin/common/util/DecimalUtil.java
- core-cube/src/main/java/org/apache/kylin/gridtable/GTAggregateScanner.java
- core-dictionary/src/main/java/org/apache/kylin/dict/NumberDictionary.java
- core-dictionary/src/main/java/org/apache/kylin/dict/NumberDictionary2.java
- core-metadata/src/main/java/org/apache/kylin/metadata/tuple/Tuple.java
- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/framework/conv/ConvSqlWriter.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/util/PercentileCounterSerializer.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/CubingJob.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/util/PercentileCounterSerializer.java
- server-base/src/main/java/org/apache/kylin/rest/controller/StreamingController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/StreamingV2Controller.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/cube/v2/coprocessor/endpoint/CubeVisitService.java
- stream-core/src/main/java/org/apache/kylin/stream/core/consumer/StreamingConsumerChannel.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/FragmentFilesMerger.java
- Fixed 6 sonar bugs according to the rule: **_Method parameters, caught exceptions and foreach variables' initial values should not be ignored_**
- Fixed 6 sonar bugs according to the rule: **_The value returned from a stream read should be checked_**
- Fixed 5 sonar bugs according to the rule: **_Jump statements should not occur in "finally" blocks_**
- Fixed 4 sonar bugs according to the rule: **_"volatile" variables should not be used with compound operators_**
- Fixed 2 sonar bugs according to the rule: **_"BigDecimal(double)" should not be used_**
> Sonar bugs

- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
`minEvictableIdleTimeMillis ` param is invalid, because `timeBetweenEvictionRunsMillis ` parameter must be used at the same time. [GenericObjectPool](https://commons.apache.org/proper/commons-pool/api-1.6/org/apache/commons/pool/impl/GenericObjectPool.html)
```
timeBetweenEvictionRunsMillis indicates how long the eviction thread should sleep before "runs" of examining idle objects. When non-positive, no eviction thread will be launched. The default setting for this parameter is -1 (i.e., idle object eviction is disabled by default).
minEvictableIdleTimeMillis specifies the minimum amount of time that an object may sit idle in the pool before it is eligible for eviction due to idle time. When non-positive, no object will be dropped from the pool due to idle time alone. This setting has no …
```
> KYLIN-4358:Bugfix statement cache eviction invalidation base on time

- core-common/src/main/java/org/apache/kylin/common/persistence/ExponentialBackoffRetry.java
- core-common/src/main/java/org/apache/kylin/common/persistence/RootPersistentEntity.java
- core-common/src/main/java/org/apache/kylin/common/util/ByteArray.java
- core-cube/src/main/java/org/apache/kylin/cube/cuboid/algorithm/BPUSCalculator.java
- core-cube/src/main/java/org/apache/kylin/cube/cuboid/algorithm/CuboidStatsUtil.java
- core-cube/src/main/java/org/apache/kylin/cube/inmemcubing/RecordConsumeBlockingQueueController.java
- core-cube/src/main/java/org/apache/kylin/gridtable/GTAggregateScanner.java
- core-dictionary/src/main/java/org/apache/kylin/dict/lookup/cache/RocksDBLookupTableCache.java
- core-metadata/src/main/java/org/apache/kylin/dimension/AbstractDateDimEnc.java
- core-metadata/src/main/java/org/apache/kylin/source/datagen/ColumnGenerator.java
- core-metrics/src/main/java/org/apache/kylin/metrics/lib/impl/BlockingReservoir.java
- core-storage/src/main/java/org/apache/kylin/storage/StorageContext.java
- core-storage/src/main/java/org/apache/kylin/storage/gtrecord/SortedIteratorMergerWithLimit.java
- core-storage/src/test/java/org/apache/kylin/storage/gtrecord/DictGridTableTest.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/BatchOptimizeJobCheckpointBuilder.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/ByteArrayWritable.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/streaming/ColumnToRowJob.java
- query/src/main/java/org/apache/kylin/query/relnode/OLAPProjectRel.java
- server-base/src/main/java/org/apache/kylin/rest/controller/QueryController.java
- server-base/src/main/java/org/apache/kylin/rest/job/KylinHealthCheckJob.java
- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/SqlUtil.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/cube/v2/coprocessor/endpoint/CubeVisitService.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/util/CubeMigrationCLI.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/Coordinator.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/coordinate/StreamingCoordinator.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/ColumnarSegmentStore.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/FSInputGeneralColumnDataReader.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/compress/FSInputLZ4CompressedColumnReader.java
- stream-receiver/src/main/java/org/apache/kylin/stream/server/ReplicaSetLeaderSelector.java
- tool/src/main/java/org/apache/kylin/tool/CubeMigrationCLI.java
Fixed 30 sonar issues.
- Fixed 18 issues: Math operands should be cast before assignment
- Fixed 7 issues: Iterator.next() methods should throw NoSuchElementException
- Fixed 1 issue: toString() should not return null
- Fixed 2 issues: Non-thread-safe fields should not be static
- Fixed 1 issue:  compareTo should not be overloaded
- Fixed 1 issue: Externalizable classes should have no-arguments constructors
> Fix sonar issues

- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- core-cube/src/main/java/org/apache/kylin/cube/model/CubeDesc.java
- core-cube/src/main/java/org/apache/kylin/cube/model/CubeDescTiretreeGlobalDomainDictUtil.java
- core-cube/src/main/java/org/apache/kylin/cube/model/DictionaryDesc.java
- core-cube/src/main/java/org/apache/kylin/cube/model/validation/rule/DictionaryRule.java
- core-metadata/src/main/java/org/apache/kylin/measure/bitmap/BitmapMeasureType.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/DataModelDesc.java
- core-metadata/src/test/java/org/apache/kylin/metadata/model/DataModelManagerTest.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/AbstractHadoopJob.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java
- webapp/app/js/controllers/cubeAdvanceSetting.js
- webapp/app/partials/cubeDesigner/advanced_settings.html
issue link : https://issues.apache.org/jira/browse/KYLIN-4338
> KYLIN-4338 Web page modification to support global domain dict

- stream-coordinator/src/test/java/org/apache/kylin/stream/coordinator/CoordinatorTest.java
The background information and a detailed analysis is here: 
https://issues.apache.org/jira/browse/KYLIN-4386
The tests in `org.apache.kylin.stream.coordinator.CoordinatorTest#testReassignFailOnStartNew` and `org.apache.kylin.stream.coordinator.CoordinatorTest#testReassignFailOnStopAndSync` will fail when making assertions due to an order issue.
The fix is to use LinkedHashMap instead of HashMap so that the non-deterministic order when iterating a HashMap is eliminated. It will not affect the performance and can make the tests more stable.
> KYLIN-4386 Use LinkedHashMap for a deterministic order

- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkUtil.java
Fix "Table or view not found" error when build cube with spark for JDBC source at step "Build cube by Layer"
> KYLIN-4370 Fix "Table or view not found" error when using JDBC source

- build/bin/find-flink-dependency.sh
I think flink is NOT a **required** dependency for most of the users at the moment. I suggest just print warning message when flink not available.
> Skip flink dependency.

- webapp/Gruntfile.js
- webapp/package.json
Add `grunt-contrib-connect` to start a static server and `grunt-contrib-watch` to trigger rebuild on source code changing. Additional middleware to fine tune the static web server:
- grunt-connect-rewrite: solve context root problem
- grunt-connect-proxy: proxy REST API to existing Kylin instance
usage:
```
cd /path/to/kylin/source/root/webapp
grunt devserver
```
a static web server will listen on `localhost:7071`
note:
in Gruntfile.js, proxy is set to `127.0.0.1:7070`. If your Kylin instance is started in docker with default settings, it will be okay. Otherwise, you may need to change the `host:port` to adjust to your environment.
> KYLIN-4424 use static web server to help frontend development

- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/CreateDictionaryJob.java
issue: https://issues.apache.org/jira/browse/KYLIN-4433
If the system level configuration is used, it will cause the dictionary to be built repeatedly, so I think the configuration of the cube should be used here.
Thanks!
> KYLIN-4433 use cube config when uhc step enabled

- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/assign/AssignmentUtil.java
This PR aims to solve the issue here: https://issues.apache.org/jira/browse/KYLIN-4397
The fix is to use `newLinkedHashMap` instead of `newHashMap` when initializing a Map. In this way, the non-deterministic behaviour is eliminated and the test will not suffer from the failure again. The code will be more stable.
> KYLIN-4397 Use newLinkedHashMap for deterministic order in AssignmentUtil.java	

- build/bin/kylin.sh
> KYLIN-4441 Add restart command to kylin.sh

- core-common/src/main/java/org/apache/kylin/common/util/CliCommandExecutor.java
- core-common/src/test/java/org/apache/kylin/common/util/CliCommandExecutorTest.java
- server-base/src/main/java/org/apache/kylin/rest/service/CubeService.java
> KYLIN-4426 CliCommandExecutor

- core-common/src/main/java/org/apache/kylin/common/util/EncryptUtil.java
- core-common/src/test/java/org/apache/kylin/common/util/EncryptUtilTest.java
Add condition to treet null input for EncryptUtil methods.  For default settings, password may not be set, so `null` will passed to `PasswordPlaceholderConfigurer#resolvePlaceholder`.  This will cause an "IllegalArgumentException: Null input buffer" and lead to startup failure. This fix treets `null` as a legal input and returns `null` for both encrytion and decrytion.
N/A
> KYLIN-4438 fix bug: null password may cause RuntimeException when starting up

- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
**Problems:**
1. The value of "Realization Names" in logQuery is wrong when query two different sqls within the same thread and second sql hits cache:
Example:
1). query Q1 hit project P1 and cube C1;
2). query Q2 hit project P2 and cube C2 in the same thread with Q1;
3). Q1 comes again and hits cache, it will show project P1 and cube C2. However, it should be cube C1.
2. Missing "Cuboid Ids" in logQuery when hit cache in a new thread which does not have OLAPContext;
**Solutions:**
1. Call 'OLAPContext.clearThreadLocalContexts()' before a query starts;
2. Get "Cuboid Ids" from SQLResponse when "OLAPContext.getThreadLocalContexts()" is null;
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves …
> KYLIN-2971 Fix the wrong "Realization Names" and missing "Cuboid Ids" in logQuery when hit cache

- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
- server/src/test/java/org/apache/kylin/rest/service/QueryServiceTest.java
This PR fix the bug described in [KYLIN-4432](https://issues.apache.org/jira/browse/KYLIN-4432) that duplicated queries with sytax error take unexpect long time when lazy query enabled. 
N/A
> KYLIN-4432 duplicated queries with sytax error take unexpect long time when lazy query enabled

- core-common/src/main/java/org/apache/kylin/common/util/EncryptUtil.java
- core-common/src/test/java/org/apache/kylin/common/util/EncryptUtilTest.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/DefaultSslProtocolSocketFactory.java
see https://issues.apache.org/jira/projects/KYLIN/issues/KYLIN-4477?filter=allissues
and https://issues.apache.org/jira/projects/KYLIN/issues/KYLIN-4478?filter=allissues
> KYLIN-4478 Use secure AES/CFB/PKCS5Padding instead of insecure AES/ECB/PKCS5Padding

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- server-base/src/main/java/org/apache/kylin/rest/controller/AdminController.java
- server-base/src/main/java/org/apache/kylin/rest/service/StreamingV2Service.java
- server-base/src/test/java/org/apache/kylin/rest/service/StreamingV2ServiceTest.java
- stream-coordinator/src/test/java/org/apache/kylin/stream/coordinator/CoordinatorTest.java
- stream-receiver/src/main/java/org/apache/kylin/stream/server/StreamingServer.java
> KYLIN-4355 add ut

- core-common/src/main/java/org/apache/kylin/common/zookeeper/KylinServerDiscovery.java
- core-common/src/test/java/org/apache/kylin/common/zookeeper/KylinServerDiscoveryTest.java
- core-job/src/main/java/org/apache/kylin/job/impl/curator/CuratorScheduler.java
Problem:
When server self discovery enables, it throws UnrecognizedPropertyException on some env, for example: cdh 5.7.
Root cause:
The json of ServiceInstance is incompatible, related to the issue of curator:  https://issues.apache.org/jira/browse/CURATOR-394
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging …
> KYLIN-4577 Throws UnrecognizedPropertyException when server self discovery enables

- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/framework/def/DataSourceDef.java
- datasource-sdk/src/main/resources/datasource/postgresql.xml
- datasource-sdk/src/test/java/org/apache/kylin/sdk/datasource/framework/conv/PostgresqlSqlConverterTest.java
- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/extensible/JdbcHiveInputBase.java
From the documentation, we know that when quoted, identifier is case sensitive, which is not easy to fix. So we cannot support reserved word as identifier, which is rare.
If this is a relatively large or complex change, kick off the discussion at …
> KYLIN-3832 Disable all convert and quote behavior for postgresql

- core-common/src/main/java/org/apache/kylin/common/util/CliCommandExecutor.java
Problems:
When download diagnosis info for a job, it throws NPE.
Solutions:
Don't replace '-' to '' for job id, which will change the value of job id and can't find the job.
If this is a relatively large or complex change, kick off the discussion at …
> KYLIN-4597 Fix NPE when download diagnosis info for a job

- build/bin/kylin.sh
Problems:
It throws 'NoClassDefFoundError: org/apache/kafka/clients/producer/Producer' when run kylin.sh org.apache.kylin.source.kafka.util.KafkaSampleProducer.
Solutions:
Add 'export kafka_dependency' before export HBASE_CLASSPATH in kylin.sh
If this …
> KYLIN-4598 Missing dependency when run kylin.sh org.apache.kylin.*

- webapp/app/partials/admin/change_pwd.html
- webapp/app/partials/admin/user_create.html
add some hint of password length in frontend password placeholder
> KYLIN-4576 add some hint of password length

- server-base/src/main/java/org/apache/kylin/rest/controller/AdminController.java
- webapp/app/js/controllers/admin.js
- webapp/app/partials/admin/config.html
> KYLIN-4705 add rest api for sparder-context url monitor

- tool/src/main/java/org/apache/kylin/tool/CubeMetaIngester.java
> KYLIN-4712 Optimize CubeMetaIngester.java CLI

- stream-core/src/main/java/org/apache/kylin/stream/core/query/MultiThreadsResultCollector.java
1、Clear the recordCachePool when the deadline has reached.
2、Add timeout for the recordCachePool offer.
https://issues.apache.org/jira/projects/KYLIN/issues/KYLIN-4771?filter=reportedbyme
> KYLIN-4771 Clear the recordCachePool when the deadline has reached

- build/bin/download-flink.sh
- core-common/src/main/java/org/apache/kylin/common/util/HadoopUtil.java
- core-common/src/main/resources/kylin-defaults.properties
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkOnYarnConfigMapping.java
- engine-flink/src/test/java/org/apache/kylin/engine/flink/FlinkOnYarnConfigMappingTest.java
- pom.xml
> KYLIN-4736 flink upgrade to 1.11.1

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- kylin-spark-project/kylin-spark-query/pom.xml
- kylin-spark-project/kylin-spark-query/src/main/java/org/apache/kylin/query/monitor/SparderContextCanary.java
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContext.scala
- kylin-spark-project/kylin-spark-query/src/test/java/org/apache/kylin/query/monitor/SparderContextCanaryTest.java
> KYLIN-4800 Add canary tool for sparder-context

- build/bin/find-hive-dependency.sh
- build/bin/kylin.sh
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
when using kylin 3.1.1's global dictionary, building the global dictionary failed because it could not be found "kylin.source.hive.warehouse-dir", resulting input path error.
After kylin is started for the first time, when it is started again,  ${dir}/cached-hive-dependency.sh will be used, now " kylin.source.hive.warehouse-dir" is not in cached-hive- dependency.sh, the parameter is null, causing a bug
If this is a relatively large or complex …
> KYLIN-4826 fix kylin.source.hive.warehouse-dir can't found

- core-common/src/main/java/org/apache/kylin/common/restclient/RestClient.java
- kylin-spark-project/kylin-spark-common/src/main/java/org/apache/kylin/engine/spark/metadata/cube/PathManager.java
- tool/src/main/java/org/apache/kylin/tool/CubeMigrationCLI.java
> KYLIN-4817 Refine CubeMigrationCLI for kylin4

- engine-mr/src/test/java/org/apache/kylin/engine/mr/steps/FactDistinctColumnsReducerMappingTest.java
- examples/test_case_data/localmeta/cube_desc/ci_left_join_cube.json
- kylin-it/src/test/resources/query/sql_expression/query10.sql
- query/src/main/java/org/apache/kylin/query/relnode/OLAPAggregateRel.java
- query/src/main/java/org/apache/kylin/query/relnode/OLAPFilterRel.java
- source-jdbc/src/test/java/org/apache/kylin/source/jdbc/extensible/JdbcHiveMRInputTest.java
> KYLIN-4682 Fix java.lang.IndexOutOfBoundsException due to not setting havingFilter correctly

- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/utils/SparkVersionUtils.scala
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/application/SparkApplication.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkExecutable.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/builder/CubeDictionaryBuilder.scala
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/builder/CubeTableEncoder.scala
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/utils/Repartitioner.java
- kylin-spark-project/kylin-spark-engine/src/test/scala/org/apache/kylin/engine/spark/builder/TestGlobalDictBuild.scala
With spark 2.X, when set 'spark.sql.adaptive.enabled' to true, it will impact the actually partition count when doing repartition with spark, which will lead to the wrong results for global dict and repartition by shardby column.
For example, after writing a cuboid data, kylin will repartition the cuboid data with 3 partition if need, but if 'spark.sql.adaptive.enabled' is true, spark will optimize the partition num to 1, which leads to wrong.
If …
> KYLIN-4967 Forbid to set 'spark.sql.adaptive.enabled' to true when building cube with Spark 2.X

- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
There are two project in Kylin: project1, project2.
Cube1 is in project1 now.
1.Some one is in project2 (In KYLIN-UI)
2.edit cube1 with url https://xxxx/kylin/cubes/edit/cube1
3. then save, now cube1 is in project2.
> [KYLIN-5032] Not allow change project for a cubeInstance.

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-job/src/main/java/org/apache/kylin/job/execution/AbstractExecutable.java
- kylin-spark-project/kylin-spark-common/src/test/java/org/apache/spark/sql/common/LocalMetadata.scala
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkExecutable.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/utils/MetaDumpUtil.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/utils/RestService.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/spark/deploy/SparkApplicationClient.scala
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/spark/deploy/StandaloneAppClient.scala
- kylin-spark-project/kylin-spark-engine/src/test/resources/response/application-detail-246.html
- kylin-spark-project/kylin-spark-engine/src/test/resources/response/standalone-master-246.json
- kylin-spark-project/kylin-spark-engine/src/test/scala/org/apache/spark/deploy/StandaloneAppClientTest.scala
[Design doc](https://www.notion.so/xxyu/Dev-Diary-KYLIN-5023-Kylin-4-deployMode-Cluster-80c269b757a74f9892551701e252ceec)
If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by explaining why you chose …
> KYLIN-5023 Support cluster deployMode for Standalone

- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/datasource/FilePruner.scala
JIRA:  https://issues.apache.org/jira/browse/KYLIN-5021
> KYLIN-5021 FilePruner throws NPE when there is no timePartitionColunm in cube

- tool/src/main/java/org/apache/kylin/tool/metrics/systemcube/CubeInstanceCreator.java
- tool/src/main/java/org/apache/kylin/tool/metrics/systemcube/ProjectCreator.java
Kylin_System's project and cubes create time is wrong (1970 ). It should be based on the current time when the user set up the Kylin_System project.
- [X ] Bugfix (non-breaking change which fixes an issue)
- [X ] I have create an issue on [Kylin's jira](https://issues.apache.org/jira/browse/KYLIN), and have described the bug/feature there in detail
- [X ] Commit messages in my PR start with the related jira ID, like "KYLIN-0000 Make Kylin project …
> KYLIN-5054 kylin_system's project and cubes create time is wrong 1970

- .github/workflows/maven.yml
- .travis.yml
- pom.xml
> KYLIN-4864 Travis CI improvement for kylin4

- .gitignore
- bin/init.sh
- cloudformation_templates/ec2-cluster-kylin4-template.yaml
- cloudformation_templates/ec2-cluster-kylin4.yaml
- cloudformation_templates/ec2-cluster-spark-master.yaml
- cloudformation_templates/ec2-cluster-spark-slave-template.yaml
- cloudformation_templates/ec2-cluster-spark-slave.yaml
- cloudformation_templates/ec2-cluster-static-services.yaml
- cloudformation_templates/ec2-cluster-zk.yaml
- clouds/aws.py
- engine.py
- engine_utils.py
- instances/aws_instance.py
- kylin_configs.yaml
- utils.py
> adapt initialized config for default aws account limits

- server-base/src/main/java/org/apache/kylin/rest/controller/AccessController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/CubeDescController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/ModelController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/ProjectController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/QueryController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/TableACLController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/TableController.java
- server-base/src/main/java/org/apache/kylin/rest/service/ProjectService.java
> add api to support for mdx

- core-common/src/main/java/org/apache/kylin/common/QueryContext.java
- core-common/src/main/java/org/apache/kylin/common/debug/BackdoorToggles.java
- jdbc/src/main/java/org/apache/kylin/jdbc/IRemoteClient.java
- jdbc/src/main/java/org/apache/kylin/jdbc/KylinClient.java
- jdbc/src/main/java/org/apache/kylin/jdbc/KylinResultSet.java
- jdbc/src/main/java/org/apache/kylin/jdbc/json/SQLResponseStub.java
- server-base/src/main/java/org/apache/kylin/rest/response/SQLResponse.java
- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
- server-base/src/test/java/org/apache/kylin/rest/response/SQLResponseTest.java
When there is a problem with the query, due to the large amount of queries at the same time, many query IDs are generated, but the query results are not returned, and the specific ID cannot be accurately located, which increases the problem location and operation and maintenance costs.
Now you can get or set any query id when you want justing using 'CUSTOMIZE_QUERY_ID' in you requset or connect property when you connect the kylin to query 
Properties info= new Properties();
info.put("user","ADMIN");
info.put("password","KYLIN");
info.put("CUSTOMIZE_QUERY_ID","test_query_id_"+System.currentTimeMillis());
Connection conn= driver.connect("jdbc:kylin://",info);
Kylin 4 or main
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of …
> KYLIN-5183 customize or get query id for devops

- core-dictionary/src/main/java/org/apache/kylin/dict/GlobalDictionaryBuilder.java
fix the dictionary lock 
kylin3
multi cube job building will be ok
> KYLIN-5180 Repair the dictionary lock bug when multi job building

- build/sbin/prepare-hadoop-conf-dir.sh
- pom.xml
- src/common-service/src/main/java/org/apache/kylin/rest/KylinPrepareEnvListener.java
- src/common-service/src/main/java/org/apache/kylin/rest/config/AppInitializer.java
- src/core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- src/core-job/src/main/java/org/apache/kylin/job/lock/ZookeeperUtil.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/project/ProjectInstance.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/query/QueryHistory.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/query/QueryMetrics.java
- src/core-metadata/src/test/java/org/apache/kylin/source/adhocquery/DoubleQuotePushDownConverterTest.java
- src/modeling-service/src/main/java/org/apache/kylin/rest/service/ModelService.java
- src/modeling-service/src/test/java/org/apache/kylin/rest/service/ModelServiceTest.java
- src/query-common/src/main/java/org/apache/kylin/query/util/KapQueryUtil.java
- src/query-common/src/main/java/org/apache/kylin/query/util/RestoreFromComputedColumn.java
- src/query-server/src/test/java/org/apache/kylin/rest/controller/NQueryControllerTest.java
- src/query-service/src/main/java/org/apache/kylin/rest/service/QueryService.java
- src/query-service/src/main/java/org/apache/kylin/rest/util/SparderUIUtil.java
- src/query/src/main/java/org/apache/kylin/query/engine/AsyncQueryApplication.java
- src/query/src/main/java/org/apache/kylin/query/engine/exec/sparder/SparderQueryPlanExec.java
- src/second-storage/core/src/main/java/org/apache/kylin/job/SecondStorageJobParamUtil.java
- src/server-base/src/test/java/org/apache/kylin/rest/metrics/QueryMetricsContextTest.java
- src/spark-project/engine-spark/src/main/java/org/apache/kylin/engine/spark/merger/SparkJobMetadataMerger.java
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/SegmentFlatTable.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/job/stage/build/FlatTableAndDictBase.scala
- src/spark-project/engine-spark/src/test/java/org/apache/kylin/engine/spark/source/NSparkSourceTest.java
- src/spark-project/sparder/src/main/scala/org/apache/spark/sql/KylinSession.scala
- src/spark-project/sparder/src/test/scala/org/apache/spark/sql/udf/TimestampDiffTest.scala
- src/streaming/pom.xml
- Don't need to initialize distributed lock when running in local mode
- Add one mode of spring.profiles.active, dev,reuse, to reuse metadata stored in local file system
- Update dependency version for the integration of DataFusion
- Make QueryEngine for SparderQueryPlanExec configurable
Co-authored-by: yangzhong <yangzhong@ebay.com>
> KYLIN-5217 Remove meaningless comment and upgrade maven dependency

- src/core-common/src/main/java/org/apache/kylin/common/KylinExternalConfigLoader.java
- src/core-common/src/test/java/org/apache/kylin/common/TestExternalConfigLoader.java
Currently we use properties.list() to get kylin config from properties to string, but this method results in a maximum length limit (which is set as 37 )for each properties. We can leverage the properties.store() method
What types …
> KYLIN-5228 Fixed length limitation during loading properties to Kylin config in Kylin5.0

- kylin-spark-project/kylin-spark-common/src/main/spark31/org/apache/spark/sql/execution/KylinFileSourceScanExec.scala
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/spark/application/JobWorkSpace.scala
当查询满足shardby条件，在创建 FileScanRDD 时，FilePartition 数应由 shardby 裁剪后的数据文件确定，而不是由回答当前查询的cuboid下所有文件确定。
before apply patch:
after apply patch:
> KYLIN-5285 the number of filePartitions of FileScanRDD when used shardby

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkExecutable.java
- server-base/src/main/java/org/apache/kylin/rest/controller/DiagnosisController.java
> Remove useless code

- src/core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- src/query-common/src/main/java/org/apache/kylin/query/engine/KECalciteConfig.java
according to pgsql: https://www.postgresql.org/docs/current/queries-order.html
By default, null values sort as if larger than any non-null value; that is, NULLS FIRST is the default for DESC order, and NULLS LAST otherwise.
> KYLIN-5279 Add default null collation configuration with CalciteExtrasProperties for Kylin5.0 

- src/core-metadata/src/main/java/org/apache/kylin/metadata/query/JdbcQueryHistoryStore.java
> KYLIN-5375 sql performance enhancement

- src/core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/query/JdbcQueryHistoryStore.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/query/QueryHistoryDAO.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/query/QueryHistoryMapper.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/query/QueryHistoryProjectInfo.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/query/RDBMSQueryHistoryDAO.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/query/util/QueryHisStoreUtil.java
- src/core-metadata/src/test/java/org/apache/kylin/metadata/query/RDBMSQueryHistoryDaoTest.java
KYLIN-5381 Avoid timeout when cleaning query history by limiting the number of data deleted each time
Co-authored-by: hui.wang <hui.wang@kyligence.io>
If this is a relatively large or complex change, kick off the discussion at user@kylin.apache.org or …
>  KYLIN-5381 Avoid timeout when cleaning query history by limiting the number of data deleted each time

- src/query-common/src/main/codegen/javacc/org/apache/kylin/query/util/ManipulationSqlParser.jj
- src/query-common/src/main/java/org/apache/kylin/query/util/DMLParserResult.java
- src/query/src/test/java/org/apache/kylin/query/util/ManipulationSqlParserTest.java
> [KYLIN-5475] Use javaCC to parse self define DML
