- docs/Operations/Kylin Metadata Store.md
replace com.kylinolap with org.apache.kylin.
> Update Kylin Metadata Store.md

- webapp/app/js/controllers/job.js
- webapp/app/js/model/jobConfig.js
- webapp/app/js/model/jobListModel.js
- webapp/app/partials/jobs/jobList.html
Signed-off-by: chenzhx <chen@apache.org>
> KYLIN-3265 Add jobSearchMode as a filter condition for jobs UI part

- webapp/app/js/controllers/cubeAdvanceSetting.js
- webapp/app/js/controllers/cubeEdit.js
KYLIN-3236 The function 'reGenerateAdvancedDict()' has an error logical judgment, which will cause an exception when you edit the cube.
Signed-off-by: xingpeng1 <xing.peng1@zte.com.cn>
> KYLIN-3236

- webapp/app/partials/cubes/cube_delete_segment.html
KYLIN-3280 The delete button should not be enabled without any segment in cube segment delete confirm dialog
> KYLIN-3280

- webapp/app/partials/admin/admin.html
KYLIN-3292 The update button should be disabled with none key and value in setting config dialog
> KYLIN-3292

- query/src/main/java/org/apache/kylin/query/util/DefaultQueryTransformer.java
- query/src/test/java/org/apache/kylin/query/util/DefaultQueryTransformerTest.java
> KYLIN-3347 : calcite function QueryService Exception

- core-cube/src/main/java/org/apache/kylin/cube/inmemcubing/CuboidResult.java
> changed unsafe code to safety

- core-cube/src/main/java/org/apache/kylin/cube/CubeDescManager.java
- core-cube/src/test/java/org/apache/kylin/cube/CubeDescManagerTest.java
modify the code for null condition
> Kylin 3255 cannot save cube

- kylin-it/pom.xml
- kylin-it/src/test/scala/kafka/admin/AdminUtils.scala
- pom.xml
kafka upgrade
kafka upgrade again
> Kafka upgrade to 1.0.0

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-job/src/main/java/org/apache/kylin/job/JoinedFlatTable.java
- source-hive/src/main/java/org/apache/kylin/source/hive/HiveInputBase.java
- source-hive/src/main/java/org/apache/kylin/source/hive/HiveMRInput.java
- source-hive/src/main/java/org/apache/kylin/source/hive/HiveSparkInput.java
> KYLIN-3457 Distribute by multi column if not set distribute column

- website/_data/docs-cn.yml
- website/_data/docs.yml
- website/_docs/tutorial/superset.cn.md
- website/_docs/tutorial/superset.md
including Chinese and English document
> Superset document

- source-hive/src/main/java/org/apache/kylin/source/hive/HiveMRInput.java
> KYLIN-3478 Enhance backwards compatibility.

- core-metadata/src/main/java/org/apache/kylin/metadata/model/FunctionDesc.java
- core-metadata/src/test/java/org/apache/kylin/metadata/model/FunctionDescTest.java
> KYLIN-3385 fix sum1 error

- jdbc/pom.xml
https://issues.apache.org/jira/browse/KYLIN-3481
> KYLIN-3481 Shaded dependencies should be optional

- core-job/src/main/java/org/apache/kylin/job/JobSearchResult.java
- core-job/src/main/java/org/apache/kylin/job/dao/ExecutableDao.java
- core-job/src/main/java/org/apache/kylin/job/execution/ExecutableManager.java
- core-metadata/src/main/java/org/apache/kylin/metadata/cachesync/CachedCrudAssist.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/JobInfoConverter.java
- server-base/src/main/java/org/apache/kylin/rest/controller/JobController.java
- server-base/src/main/java/org/apache/kylin/rest/service/JobService.java
> KYLIN-3470 Add cache for execute and execute_output

- core-metadata/src/main/java/org/apache/kylin/metadata/datatype/DataType.java
> KYLIN-3505 Fix wrong usage of cache in DataType

- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
Fix [KYLIN-3507](https://issues.apache.org/jira/projects/KYLIN/issues/KYLIN-3507)
> KYLIN-3507 Avoid NPE when project is not found

- build/bin/kylin-port-replace-util.sh
https://issues.apache.org/jira/browse/KYLIN-3535
> KYLIN-3535 replace and uncomment the web server port

- server-base/src/main/java/org/apache/kylin/rest/job/HybridCubeCLI.java
> KYLIN-3258 No check for duplicate cube name when creating a hybrid cube

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/lookup/LookupTableToHFileJob.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/CubeHTableUtil.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/util/DeployCoprocessorCLI.java
KYLIN-3517 Upadate coprocessor on HBase2.0 is avaliable.
> KYLIN-3517 Upadate coprocessor on HBase2.0 is avaliable.

- core-metadata/src/main/java/org/apache/kylin/metadata/datatype/DataType.java
- core-metadata/src/main/java/org/apache/kylin/metadata/datatype/DataTypeOrder.java
https://issues.apache.org/jira/browse/KYLIN-3547
> KYLIN-3547 add boolean DataTypeOrder

- source-hive/src/main/java/org/apache/kylin/source/hive/GarbageCollectionStep.java
Reserve intermediate flat table data if kylin.source.hive.keep-flat-table set to true
> KYLIN-3525 Reserve intermediate flat table data if kylin.source.hive.keep-flat-table set to true

- server-base/src/main/java/org/apache/kylin/rest/security/KylinUserManager.java
- server-base/src/main/java/org/apache/kylin/rest/service/KylinUserService.java
https://issues.apache.org/jira/browse/KYLIN-3531
> KYLIN-3531 Save uppercase of usernames to metadata

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/CreateHTableJob.java
https://issues.apache.org/jira/browse/KYLIN-3543
> KYLIN-3543 Export HBase configuration only for Spark engine

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/resources/kylin-defaults.properties
- server/src/test/java/org/apache/kylin/rest/service/AdminServiceTest.java
…me with kylin-defaults.properties
> KYLIN-3439, make default kylin.web.timezone in KylinConfigBase the same with kylin-defaults.properties

- core-cube/src/main/java/org/apache/kylin/cube/cuboid/algorithm/CuboidStatsUtil.java
KYLIN-3580 Avoid using entrySet to add elements @ CuboidStatsUtil#complementRowCountForMandatoryCuboids
> KYLIN-3580 Avoid using entrySet to add elements

- core-common/src/main/java/org/apache/kylin/common/util/BytesUtil.java
- core-common/src/main/java/org/apache/kylin/common/util/ClassUtil.java
- core-common/src/main/java/org/apache/kylin/common/util/CompressionUtils.java
- core-common/src/main/java/org/apache/kylin/common/util/HadoopUtil.java
- core-common/src/main/java/org/apache/kylin/common/util/IdentityUtils.java
- core-common/src/main/java/org/apache/kylin/common/util/JsonUtil.java
- core-common/src/main/java/org/apache/kylin/common/util/MathUtil.java
- core-common/src/main/java/org/apache/kylin/common/util/RandomUtil.java
- core-common/src/main/java/org/apache/kylin/common/util/RangeUtil.java
- core-common/src/main/java/org/apache/kylin/common/util/SortUtil.java
- core-common/src/main/java/org/apache/kylin/common/util/SourceConfigurationUtil.java
- core-common/src/main/java/org/apache/kylin/common/util/StringUtil.java
- core-common/src/main/java/org/apache/kylin/common/util/TimeUtil.java
- core-common/src/main/java/org/apache/kylin/common/util/ZipFileUtils.java
- core-common/src/main/java/org/apache/kylin/common/util/ZooKeeperUtil.java
- core-job/src/main/java/org/apache/kylin/job/util/MailNotificationUtil.java
- core-metadata/src/main/java/org/apache/kylin/util/KryoUtils.java
- core-storage/src/main/java/org/apache/kylin/storage/util/SizeOfUtil.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/util/IteratorUtils.java
- query/src/main/java/org/apache/kylin/query/util/PushDownUtil.java
- query/src/main/java/org/apache/kylin/query/util/QueryUtil.java
- query/src/main/java/org/apache/kylin/query/util/RexUtil.java
- server-base/src/main/java/org/apache/kylin/rest/util/AclPermissionUtil.java
- server-base/src/main/java/org/apache/kylin/rest/util/QueryRequestLimits.java
- server-base/src/main/java/org/apache/kylin/rest/util/TableauInterceptor.java
- source-kafka/src/main/java/org/apache/kylin/source/kafka/util/KafkaClient.java
- tool/src/main/java/org/apache/kylin/tool/util/ToolUtil.java
Add private constructor for utility classes.
> KYLIN-3600 Add private constructor for utility classes.

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/lookup/HBaseLookupRowEncoder.java
- tool/src/main/java/org/apache/kylin/tool/JobInstanceExtractor.java
- tool/src/main/java/org/apache/kylin/tool/KylinLogExtractor.java
Use parseInt() to parse a primitive instead of to use boxing/unboxing
> KYLIN-3586

- core-common/src/main/java/org/apache/kylin/common/util/CheckUtil.java
- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- source-hive/src/main/java/org/apache/kylin/source/jdbc/SqlUtil.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/util/ZookeeperDistributedLock.java
1. Use try-with-resources instead try-catch-finally
2. Modify logger format
3. Add private constructor for utility class
> KYLIN-3597 Fix some issues reported by SonarCloud

- build/bin/build-incremental-cube.sh
- build/bin/kylin-port-replace-util.sh
- build/bin/system-cube.sh
https://issues.apache.org/jira/browse/KYLIN-3570
> KYLIN-3570 Automatically build system cube

- core-cube/src/main/java/org/apache/kylin/cube/cli/DictionaryGeneratorCLI.java
> KYLIN-3574 Close underlying resource of lookup table

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/java/org/apache/kylin/common/util/MailService.java
- core-metadata/src/main/java/org/apache/kylin/metadata/filter/ExtractTupleFilter.java
- core-metadata/src/main/java/org/apache/kylin/metadata/filter/TimeConditionLiteralsReplacer.java
- core-metadata/src/main/java/org/apache/kylin/metadata/filter/UDF/MassInTupleFilter.java
- core-metadata/src/main/java/org/apache/kylin/metadata/tuple/Tuple.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/MapReduceExecutable.java
- query/src/main/java/org/apache/kylin/query/util/DefaultQueryTransformer.java
- server-base/src/main/java/org/apache/kylin/rest/job/HybridCubeCLI.java
- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
- source-kafka/src/main/java/org/apache/kylin/source/kafka/DefaultTimeParser.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/lookup/LookupTableHFilesBulkLoadJob.java
- tool/src/main/java/org/apache/kylin/tool/AbstractInfoExtractor.java
- tool/src/main/java/org/apache/kylin/tool/CubeMetaExtractor.java
- tool/src/main/java/org/apache/kylin/tool/CubeMetaIngester.java
- tool/src/main/java/org/apache/kylin/tool/DiagnosisInfoCLI.java
- tool/src/main/java/org/apache/kylin/tool/JobDiagnosisInfoCLI.java
- tool/src/main/java/org/apache/kylin/tool/MetadataCleanupJob.java
- tool/src/main/java/org/apache/kylin/tool/MrJobInfoExtractor.java
KYLIN-3586 Fix eight primitive boxing/unboxing problem.
> KYLIN-3586 Fix eight primitive boxing/unboxing problem.

- core-storage/src/main/java/org/apache/kylin/storage/gtrecord/SegmentCubeTupleIterator.java
- source-kafka/src/main/java/org/apache/kylin/source/kafka/config/KafkaConsumerProperties.java
- source-kafka/src/main/java/org/apache/kylin/source/kafka/util/KafkaSampleProducer.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/util/RowCounterCLI.java
1. refactor logger format
2. use try with resource other than closeQuietly method of IOUtils
> KYLIN-3597 Improve code smell

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/util/UpdateHTableHostCLI.java
Close the HBase connection after used in UpdateHTableHostCLI
> KYLIN-3603 Close the HBase connection after used in UpdateHTableHostCLI

- webapp/app/js/controllers/cubeMeasures.js
- webapp/app/partials/cubeDesigner/measures.html
Add bulk add measures for web side more details in ticket: https://issues.apache.org/jira/browse/KYLIN-3599
> KYLIN-3599 Bulk Add Measures

- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkCubingMerge.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkFactDistinct.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkMergingDictionary.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/SparkCubeHFile.java
KYLIN-3597 Use try-with-resources to close JavaSparkContext after used.
> KYLIN-3597 Close JavaSparkContext after used.

- pom.xml
Travis-ci failed with message:
"
The job exceeded the maximum log length, and has been terminated."
I try to disable errorprone check to reduce the log output.
> KYLIN-2924 disable google error-prone for travis-ci

- build/script/download-spark.sh
- engine-spark/src/main/java/org/apache/kylin/engine/spark/KylinKryoRegistrator.java
- pom.xml
KYLIN-3272 Upgrade Spark to 2.3.2
> KYLIN-3272 Upgrade Spark to 2.3.2

- core-common/src/main/java/org/apache/kylin/common/debug/BackdoorToggles.java
- jdbc/src/main/java/org/apache/kylin/jdbc/Driver.java
- jdbc/src/main/java/org/apache/kylin/jdbc/KylinClient.java
- jdbc/src/main/java/org/apache/kylin/jdbc/KylinResultSet.java
- jdbc/src/test/java/org/apache/kylin/jdbc/KylinConnectionTest.java
- query/src/main/java/org/apache/kylin/query/QueryConnection.java
Fix [KYLIN-3496](https://issues.apache.org/jira/projects/KYLIN/issues/KYLIN-3496?filter=allissues)
> KYLIN-3496 Make calcite extras props available in JDBC Driver

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/HBaseResourceStore.java
Avoid resource inconsistent caused by hbase rpc timeout
> KYLIN-3499 Update HBaseResourceStore.java

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
Add configuration that can switch on/off preparedStatement cache in kylin server
> KYLIN-3632 Add configuration that can switch on/off preparedStatement cache

- build/bin/find-hive-dependency.sh
- build/bin/find-spark-dependency.sh
KYLIN-3642 Exclude conflict jar
> KYLIN-3642 Exclude conflict jar

- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- query/src/main/java/org/apache/kylin/query/enumerator/HiveEnumerator.java
- source-hive/src/main/java/org/apache/kylin/source/hive/BeelineHiveClient.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/util/GridTableHBaseBenchmark.java
- tool/src/main/java/org/apache/kylin/tool/CubeMetaIngester.java
Refactor methods to reduce the Cognitive Complexity
Reuse "Random" objects
Use SQL binding mechanisms
> KYLIN-3597 Fix sonar issues

- core-common/src/main/java/org/apache/kylin/common/persistence/JDBCResourceDAO.java
Locking on an interned string can cause unexpected locking collisions with other part of code. A better option is **_Interner_** in guava.
> KYLIN-3556, replace String.intern to avoid unexpected locking collisions

- build/smoke-test/testBuildCube.py
https://issues.apache.org/jira/browse/KYLIN-3673
> KYLIN-3673 Increasing the limit of smoke-test building time

- core-storage/src/main/java/org/apache/kylin/storage/gtrecord/SegmentCubeTupleIterator.java
> KYLIN-3669, add log to indicate the case when using "GTStreamAggregateScanner".

- core-common/src/main/java/org/apache/kylin/common/util/StringUtil.java
- core-common/src/test/java/org/apache/kylin/common/util/StringUtilTest.java
- core-cube/src/main/java/org/apache/kylin/cube/cli/CubeSignatureRefresher.java
- core-job/src/main/java/org/apache/kylin/job/impl/threadpool/DistributedScheduler.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/LookupMaterializeContext.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/AbstractHadoopJob.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/MergeDictionaryMapper.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/MergeDictionaryReducer.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkMergingDictionary.java
- jdbc/src/main/java/org/apache/kylin/jdbc/KylinConnection.java
- kylin-it/src/test/java/org/apache/kylin/cube/cuboid/algorithm/ITAlgorithmTestBase.java
- kylin-it/src/test/java/org/apache/kylin/cube/inmemcubing/ITInMemCubeBuilderTest.java
- query/src/main/java/org/apache/kylin/query/relnode/OLAPAuthentication.java
- query/src/main/java/org/apache/kylin/query/relnode/OLAPTableScan.java
- query/src/main/java/org/apache/kylin/query/schema/OLAPTable.java
- server-base/src/main/java/org/apache/kylin/rest/controller/TableController.java
- server-base/src/main/java/org/apache/kylin/rest/init/InitialTaskManager.java
- server-base/src/main/java/org/apache/kylin/rest/service/AdminService.java
- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
- server-base/src/main/java/org/apache/kylin/rest/signature/RealizationSetCalculator.java
- source-hive/src/main/java/org/apache/kylin/source/hive/cardinality/HiveColumnCardinalityUpdateJob.java
- source-hive/src/test/java/org/apache/kylin/source/hive/HiveMRInputTest.java
- tool/src/main/java/org/apache/kylin/tool/CubeMetaExtractor.java
- tool/src/main/java/org/apache/kylin/tool/CubeMigrationCheckCLI.java
- tool/src/main/java/org/apache/kylin/tool/HBaseUsageExtractor.java
- tool/src/main/java/org/apache/kylin/tool/JobDiagnosisInfoCLI.java
Issue : https://issues.apache.org/jira/browse/KYLIN-3559
Solution : 
1. Leverage Splitter in Guava to create split/splitByComma and refactor splitAndTrim method in StringUtil
2. Replace the string.split with StringUtil.split
> KYLIN-3559 Use Splitter for splitting String

- build/bin/find-hive-dependency.sh
Enhancement script for find-hive-dependency.sh
> #KYLIN-3684, HIVE_LIB is not set or not resolved correctly

- core-metadata/src/main/java/org/apache/kylin/metadata/model/PartitionDesc.java
Fixed [KYLIN-3665]: Partition time column may never be added.
> KYLIN-3665 Partition time column may never be added

- cache/src/main/java/org/apache/kylin/cache/memcached/MemcachedCache.java
- core-common/src/main/java/org/apache/kylin/common/BackwardCompatibilityConfig.java
- core-job/src/main/java/org/apache/kylin/job/JoinedFlatTable.java
- core-job/src/main/java/org/apache/kylin/job/util/FlatTableSqlQuoteUtils.java
- core-job/src/test/java/org/apache/kylin/job/util/FlatTableSqlQuoteUtilsTest.java
- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/framework/conv/ConvSqlWriter.java
Fix 4 issues
IT : 
[INFO] Apache Kylin ....................................... SUCCESS [  8.032 s]
[INFO] Apache Kylin - Core Common ......................... SUCCESS [ 22.815 s]
[INFO] Apache Kylin - Core Metadata ....................... SUCCESS [01:00 min]
[INFO] Apache Kylin - Core Dictionary ..................... SUCCESS [05:56 min]
[INFO] Apache Kylin - Core Cube ........................... SUCCESS [01:25 min]
[INFO] Apache Kylin - Core Metrics ........................ SUCCESS [  1.804 s]
[INFO] Apache Kylin - Core Job ............................ SUCCESS [ 47.911 s]
[INFO] Apache Kylin - Core Storage ........................ SUCCESS [ 10.086 s]
[INFO] Apache Kylin - MapReduce Engine .................... SUCCESS [ 26.941 s]
[INFO] Apache Kylin - Spark Engine ........................ …
> Issue 3597 fix sonar issues

- core-job/src/main/java/org/apache/kylin/job/dao/ExecutableDao.java
The method `isTaskExecutableOutput` is quite confusing to me, so I add my understanding as javadoc to that method, and I guess it might be helpful to other developers.
> KYLIN-3617 Add javadoc for magic number in isTaskExecutableOutput

- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
> KYLIN-3720 add column family check when save/update cube desc

- kylin-it/src/test/resources/query/sql_distinct_precisely/query02.sql
- kylin-it/src/test/resources/query/sql_distinct_precisely/query04.sql
>  KYLIN-3724 Kylin IT test sql is unreasonable

- webapp/app/js/controllers/cubeMeasures.js
revert KYLIN-2243 8c0c44b887e2caa21b097c2334f8d21c42462e80
> KYLIN-3738 Edit cube measure may make the decimal type change unexpectly

- core-metadata/src/main/java/org/apache/kylin/metadata/model/ParameterDesc.java
- server-base/src/main/java/org/apache/kylin/rest/controller/StreamingCoordinatorController.java
- storage-stream/src/main/java/org/apache/kylin/storage/stream/rpc/HttpStreamDataSearchClient.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/Coordinator.java
- stream-core/src/main/java/org/apache/kylin/stream/core/model/DataRequest.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/StreamingSegmentManager.java
- stream-core/src/main/java/org/apache/kylin/stream/core/util/RestService.java
- stream-receiver/src/main/java/org/apache/kylin/stream/server/StreamingServer.java
- stream-receiver/src/main/java/org/apache/kylin/stream/server/rest/controller/DataController.java
- stream-receiver/src/main/java/org/apache/kylin/stream/server/retention/RetentionPolicyInfo.java
- mvn test pass
- manual test pass
> KYLIN-3742 Fix DataRequest for NPE and add some javadoc

- assembly/pom.xml
- stream-coordinator/pom.xml
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/Coordinator.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/exception/ClusterStateException.java
- stream-coordinator/src/test/java/org/apache/kylin/stream/coordinator/CoordinatorTest.java
- stream-receiver/src/main/java/org/apache/kylin/stream/server/rest/controller/SystemController.java
- stream-source-kafka/pom.xml
The purpose of this PR is as following:
1. Fix a small bug in mapreduce job when lambda is enabled.
2. Add enhancement for reassign of Coordinator
3. Add unit test for for reassign of Coordinator
4. Add some javadoc
> KYLIN-3759 & KYLIN-3744

- stream-core/src/main/java/org/apache/kylin/stream/core/storage/StreamingSegmentManager.java
https://issues.apache.org/jira/browse/KYLIN-3791
> KYLIN-3791 Map return by Maps.transformValues is a immutable view

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/java/org/apache/kylin/common/livy/LivyRestBuilder.java
- core-common/src/main/java/org/apache/kylin/common/livy/LivyRestClient.java
- core-common/src/main/java/org/apache/kylin/common/livy/LivyRestExecutor.java
- core-common/src/main/java/org/apache/kylin/common/livy/LivyStateEnum.java
- core-common/src/main/java/org/apache/kylin/common/livy/LivyTypeEnum.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkBatchCubingJobBuilder2.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkBatchMergeJobBuilder2.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutableFactory.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutableLivy.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkSqlOnLivyBatch.scala
- source-hive/src/main/java/org/apache/kylin/source/hive/CreateFlatHiveTableByLivyStep.java
- source-hive/src/main/java/org/apache/kylin/source/hive/HiveInputBase.java
- source-hive/src/main/java/org/apache/kylin/source/hive/RedistributeFlatHiveTableByLivyStep.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/HBaseSparkSteps.java
KYLIN-3795 Submit Spark jobs via Apache Livy
> KYLIN-3795 Submit Spark jobs via Apache Livy

- source-jdbc/src/test/java/org/apache/kylin/source/jdbc/SqlUtilTest.java
- source-kafka/src/test/java/org/apache/kylin/source/kafka/hadoop/KafkaInputRecordReaderTest.java
> Added small Unit Tests

- core-metadata/src/main/java/org/apache/kylin/metadata/model/IEngineAware.java
- engine-flink/pom.xml
- webapp/app/js/model/cubeConfig.js
- webapp/app/partials/cubeDesigner/advanced_settings.html
jira ref : https://issues.apache.org/jira/browse/KYLIN-3853
> KYLIN-3853 Support Flink cube engine for Kylin web UI

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingByLayer.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkUtil.java
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3848
> KYLIN-3848 Flink cubing step : build by layer

- core-job/src/main/java/org/apache/kylin/job/constant/ExecutableConstants.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkBatchCubingJobBuilder2.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkExecutable.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkOnYarnConfigMapping.java
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3868
> KYLIN-3868 Implement Flink batch cubing job builder

- build/script/download-flink.sh
- build/script/package.sh
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3852
> KYLIN-3852 Provide Flink binary package download script

- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkOnYarnConfigMapping.java
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3876
> KYLIN-3876 Fix flink config option wrong key mapping

- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingMerge.java
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3850
> KYLIN-3850 Flink cubing step : merge by layer

- core-common/src/main/resources/kylin-defaults.properties
- examples/test_case_data/sandbox/kylin.properties
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3877
> KYLIN-3877 Add flink specific config items for kylin properties configuration files

- core-common/src/main/java/org/apache/kylin/common/util/FlinkEntry.java
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3879
> KYLIN-3879 Implement FlinkEntry

- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkBatchCubingEngine2.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkBatchMergeJobBuilder2.java
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3869
> KYLIN-3869 Implement Flink batch merge job builder

- build/bin/util.sh
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3864
> KYLIN-3864 Provide a function to judge whether the os type is Mac os x or not

- .gitignore
- pom.xml
See: https://issues.apache.org/jira/browse/KYLIN-3882
> KYLIN-3882: kylin master build failed for pom issues

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/CubeHFileJob.java
Detail: https://issues.apache.org/jira/browse/KYLIN-3874
> KYLIN-3874 "Convert Cuboid Data to HFile" failed when HBase and MR use different HDFS clusters

- source-hive/pom.xml
- source-hive/src/main/java/org/apache/kylin/source/hive/HiveFlinkInput.java
- source-hive/src/main/java/org/apache/kylin/source/hive/HiveSource.java
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3897
> KYLIN-3897 Implement IFlinkInput based on Hive

- storage-hbase/pom.xml
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/HBaseStorage.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/HBaseFlinkOutputTransition.java
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3896
> KYLIN-3896 Implement IFlinkOutput based on HBase

- build/bin/check-port-availability.sh
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3756
> KYLIN-3756 Support check-port-availability script for mac os x

- server-base/src/main/java/org/apache/kylin/rest/metrics/QueryMetricsFacade.java
see: https://issues.apache.org/jira/browse/KYLIN-3895
> KYLIN-3895 Failed to register new MBean when "kylin.server.query-metrics-enabled" set true

- build/script/download-flink.sh
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3910
> KYLIN-3910 Fix missing dependency when submit flink application to YARN

- engine-spark/src/main/java/org/apache/kylin/engine/spark/KylinKryoRegistrator.java
See: https://issues.apache.org/jira/browse/KYLIN-3909
> KYLIN-3909: kylin job failed for MappeableRunContainer is not registered

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/util/DeployCoprocessorCLI.java
See: https://issues.apache.org/jira/browse/KYLIN-3911
> KYLIN-3911: Check if HBase table is enabled before diabling table in DeployCoprocessorCLI

- build/script/download-flink.sh
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3914
> KYLIN-3914 Download required dependencies jar from maven central repository for FlinkCubeHFile

- engine-flink/src/test/java/org/apache/kylin/engine/flink/FlinkOnYarnConfigMappingTest.java
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3919
> KYLIN-3919 Add unit test for FlinkOnYarnConfigMapping

- build/bin/kylin.sh
> minor, refine logs when starting.

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-cube/src/main/java/org/apache/kylin/cube/model/CubeDesc.java
- core-job/src/main/java/org/apache/kylin/job/JoinedFlatTable.java
- core-job/src/main/java/org/apache/kylin/job/constant/ExecutableConstants.java
- core-metadata/src/main/java/org/apache/kylin/measure/bitmap/BitmapMeasureType.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/FunctionDesc.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/BaseCuboidBuilder.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/FactDistinctColumnsMapper.java
- examples/test_case_data/localmeta/cube_desc/ci_inner_join_cube.json
- source-hive/src/main/java/org/apache/kylin/source/hive/BeelineHiveClient.java
- source-hive/src/main/java/org/apache/kylin/source/hive/CLIHiveClient.java
- source-hive/src/main/java/org/apache/kylin/source/hive/CreateMrHiveDictStep.java
- source-hive/src/main/java/org/apache/kylin/source/hive/HiveInputBase.java
- source-hive/src/main/java/org/apache/kylin/source/hive/IHiveClient.java
- source-hive/src/main/java/org/apache/kylin/source/hive/MRHiveDictUtil.java
- Manual Test passed
- CI test passed
> KYLIN-3841 Build Global Dict by Hive

- core-common/src/main/java/org/apache/kylin/common/util/HiveCmdBuilder.java
- core-common/src/main/java/org/apache/kylin/common/util/SourceConfigurationUtil.java
- core-job/src/main/java/org/apache/kylin/job/execution/AbstractExecutable.java
- core-job/src/main/java/org/apache/kylin/job/execution/CheckpointExecutable.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/CubingJob.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/LookupSnapshotBuildJob.java
- source-hive/src/main/java/org/apache/kylin/source/hive/CreateFlatHiveTableByLivyStep.java
- source-hive/src/main/java/org/apache/kylin/source/hive/CreateFlatHiveTableStep.java
- source-hive/src/main/java/org/apache/kylin/source/hive/RedistributeFlatHiveTableByLivyStep.java
- source-hive/src/main/java/org/apache/kylin/source/hive/RedistributeFlatHiveTableStep.java
See: https://issues.apache.org/jira/browse/KYLIN-3912
Add hive confs in kylin config to hive jdbc connection
> KYLIN-3912: Support cube level mapreduuce queue config for BeelineHiveClient

- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkExecutable.java
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3915
> KYLIN-3915 Replace dead HADOOP_CLASSPATH in FlinkExecutable

- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingByLayer.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingMerge.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/util/PercentileCounterSerializer.java
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3963
> KYLIN-3963 Provide a custom serializer for PercentileCounter

- jdbc/pom.xml
- jdbc/src/main/resources/META-INF/services/java.sql.Driver
- pom.xml
- Driver manager compability.
- Add guava to uber-jar for standalone usage.
> KYLIN-3965 JDBC fix.

- core-common/src/test/java/org/apache/kylin/common/KylinConfigTest.java
- core-common/src/test/java/org/apache/kylin/common/util/StringUtilTest.java
Added Unit Tests to increase code coverage.
> Added Unit Tests

- source-jdbc/src/test/java/org/apache/kylin/source/jdbc/extensible/JdbcHiveMRInputTest.java
replace "\n" by System.lineseperator to support run test case
successfully on windows
platform
> replace "\n" by System.lineseperator to support run test case

- source-hive/src/main/java/org/apache/kylin/source/hive/BeelineHiveClient.java
Activate option -w password file for beeline for kylin.
Example:
https://cwiki.apache.org/confluence/display/Hive/HiveServer2+Clients
% beeline -u jdbc:hive2://localhost:10000/default -n scott -w password_file
> Read password from file for Beeline

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-dictionary/src/main/java/org/apache/kylin/dict/TrieDictionaryForestBuilder.java
jira : https://issues.apache.org/jira/browse/KYLIN-3995
> KYLIN-3995 config data type may make oom

- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/CuboidRecommenderUtil.java
> KYLIN-3998 Make "bpus-min-benefit-ratio" configurable in cube planner phase 1

- core-common/src/test/java/org/apache/kylin/common/util/SortUtilTest.java
- core-common/src/test/java/org/apache/kylin/common/util/StringSplitterTest.java
- core-common/src/test/java/org/apache/kylin/common/util/SumHelperTest.java
- engine-mr/src/test/java/org/apache/kylin/engine/mr/common/HadoopJobStatusCheckerTest.java
- jdbc/src/test/java/org/apache/kylin/jdbc/KylinClientTest.java
- stream-core/src/test/java/org/apache/kylin/stream/core/util/TimeDerivedColumnTypeTest.java
- stream-source-kafka/src/test/java/org/apache/kylin/stream/source/kafka/KafkaSourceTest.java
- stream-source-kafka/src/test/java/org/apache/kylin/stream/source/kafka/KafkaTopicAssignmentTest.java
Added Unit Tests to increase code coverage.
> Add additional unit tests

- core-common/src/main/java/org/apache/kylin/common/persistence/FileResourceStore.java
- core-common/src/main/java/org/apache/kylin/common/persistence/HDFSResourceStore.java
- core-common/src/main/java/org/apache/kylin/common/persistence/JDBCResourceSQL.java
- core-common/src/main/java/org/apache/kylin/common/persistence/JDBCResourceStore.java
- core-common/src/main/java/org/apache/kylin/common/persistence/PushdownResourceStore.java
- core-common/src/main/java/org/apache/kylin/common/persistence/ResourceStore.java
- core-common/src/test/java/org/apache/kylin/common/persistence/ResourceStoreTest.java
- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- core-cube/src/main/java/org/apache/kylin/cube/cli/DictionaryGeneratorCLI.java
- core-dictionary/src/main/java/org/apache/kylin/dict/DictionaryManager.java
- core-dictionary/src/main/java/org/apache/kylin/dict/lookup/SnapshotManager.java
- core-dictionary/src/test/java/org/apache/kylin/dict/DictionaryManagerTest.java
- core-dictionary/src/test/java/org/apache/kylin/dict/lookup/SnapshotManagerTest.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/CreateDictionaryJob.java
- kylin-it/src/test/java/org/apache/kylin/cube/ITDictionaryManagerTest.java
- server-base/src/main/java/org/apache/kylin/rest/job/MetadataCleanupJob.java
- server-base/src/test/java/org/apache/kylin/rest/job/MetadataCleanupJobTest.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/HBaseResourceStore.java
1. add ResourceStore.delete(respath, timestamp) interface & impl
2. add ResourceStore.updateTimestamp(respath, timestamp) interface & impl
3. update resource timestamp when reusing dict/snapshot
4. Retry avaibility build process of dict & snapshot 
5. refactor metadata cleanup by using delete with timestamp interface
> #KYLIN-3977

- cache/src/main/java/org/apache/kylin/cache/cachemanager/MemcachedCacheManager.java
- core-common/src/main/java/org/apache/kylin/common/util/Bytes.java
- core-common/src/main/java/org/apache/kylin/common/util/ClasspathScanner.java
- core-common/src/main/java/org/apache/kylin/common/util/MailService.java
- core-storage/src/main/java/org/apache/kylin/storage/gtrecord/GTCubeStorageQueryBase.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/AbstractHadoopJob.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/HadoopJobStatusChecker.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/lookup/LookupExecutableUtil.java
Small performance improvements
> Small performance improvements

- core-job/src/main/java/org/apache/kylin/job/engine/JobEngineConfig.java
- core-storage/src/test/java/org/apache/kylin/storage/StorageContextTest.java
- core-storage/src/test/java/org/apache/kylin/storage/hybrid/HybridInstanceTest.java
- core-storage/src/test/java/org/apache/kylin/storage/translate/FuzzyValueCombinationTest.java
Added Unit Tests to increase code coverage.
> Add unit tests five

- build/bin/check-port-availability.sh
- engine-mr/src/main/java/org/apache/kylin/engine/mr/IMROutput2.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/JobBuilderSupport.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/BatchConstants.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/CuboidJob.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/InMemCuboidJob.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/MergeCuboidJob.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/MergeCuboidMapper.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkBatchCubingJobBuilder2.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkCubingByLayer.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutableLivy.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkFactDistinct.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/HBaseMROutput2Transition.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/HBaseSparkSteps.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/SparkCubeHFile.java
1. There had found a warning info tip need run as root user when use lastest  version of `Apache Kylin` when check runtime environment.
2. By the way there had found some not friendly variable names and methods in source code,  you can check it with my  git commit.
> Fixed some look not friendly things

- core-dictionary/src/main/java/org/apache/kylin/dict/TableColumnValueSortedEnumerator.java
- core-dictionary/src/main/java/org/apache/kylin/dict/TrieDictionaryForestBuilder.java
- core-dictionary/src/main/java/org/apache/kylin/dict/global/AppendDictNode.java
- core-dictionary/src/main/java/org/apache/kylin/dict/lookup/SnapshotTable.java
- core-metadata/src/main/java/org/apache/kylin/measure/topn/TopNCounterSerializer.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/TableExtDesc.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java
- jdbc/src/main/java/org/apache/kylin/jdbc/KylinResultSet.java
- server-base/src/main/java/org/apache/kylin/rest/controller/StreamingV2Controller.java
- server-base/src/main/java/org/apache/kylin/rest/util/ValidateUtil.java
- stream-core/src/main/java/org/apache/kylin/stream/core/query/StreamingQueryProfile.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/RawRecord.java
- stream-receiver/src/main/java/org/apache/kylin/stream/server/StreamingServer.java
- stream-receiver/src/main/java/org/apache/kylin/stream/server/rest/util/QueryUtil.java
Additional small performance improvements
> Additional small performance improvements

- jdbc/src/main/java/org/apache/kylin/jdbc/KylinMeta.java
Removed duplicate code in KylinMeta
> Removed duplicate code in KylinMeta

- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/ModelController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/ProjectController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/StreamingController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/TableController.java
See: https://issues.apache.org/jira/browse/KYLIN-4025
> KYLIN-4025: Add detail exception in kylin http response

- core-cube/src/main/java/org/apache/kylin/cube/util/KeyValueBuilder.java
- core-dictionary/src/main/java/org/apache/kylin/dict/DictionaryGenerator.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/FactDistinctColumnsMapper.java
KYLIN-3845 solve the problem that kylin build error if Kafka streaming source  lacks selected dimensions or metrics then throws ArrayINdexOutofBoundsException  in a kylin stream build task,  .
> KYLIN-3845 solve the problem that kylin build error in stream build task.

- core-common/src/main/java/org/apache/kylin/common/persistence/ResourceTool.java
- core-common/src/test/java/org/apache/kylin/common/persistence/ResourceToolTest.java
KYLIN-3271 KYLIN-3454 minor refactor, accelerate ResourceTool
> KYLIN-3271 KYLIN-3454 minor refactor, accelerate ResourceTool

- core-common/src/main/resources/kylin-defaults.properties
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingByLayer.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingMerge.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkExecutable.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkOnYarnConfigMapping.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkUtil.java
- engine-flink/src/test/java/org/apache/kylin/engine/flink/FlinkOnYarnConfigMappingTest.java
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3991
> KYLIN-3991 Provide more config options for Flink cube engine

- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingByLayer.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingMerge.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkExecutable.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkMergingDictionary.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkUtil.java
JIRA : https://issues.apache.org/jira/browse/KYLIN-4050
> KYLIN-4050 Fix a CLI option parse error in FlinkMergingDictionary and some little code refactor

- pom.xml
Please see [KYLIN-4044](https://issues.apache.org/jira/browse/KYLIN-4044)
> #KYLIN-4044, update curator version to avoid NPE issue

- core-metrics/src/main/java/org/apache/kylin/metrics/lib/impl/BlockingReservoir.java
- metrics-reporter-hive/pom.xml
- metrics-reporter-hive/src/main/java/org/apache/kylin/metrics/lib/impl/hive/HiveProducer.java
- metrics-reporter-hive/src/main/java/org/apache/kylin/metrics/lib/impl/hive/HiveReservoirReporter.java
- server/src/main/resources/kylinMetrics.xml
See: https://issues.apache.org/jira/browse/KYLIN-4026
> KYLIN-4026: Avoid too many file append operations in HiveProducer of of hive metrics reporter

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-dictionary/src/main/java/org/apache/kylin/dict/CacheDictionary.java
- core-dictionary/src/test/java/org/apache/kylin/dict/ShrunkenDictionaryTest.java
- core-dictionary/src/test/java/org/apache/kylin/dict/TrieDictionaryForestTest.java
- core-dictionary/src/test/java/org/apache/kylin/dict/TrieDictionaryTest.java
- engine-mr/src/test/java/org/apache/kylin/engine/mr/steps/NumberDictionaryForestTest.java
KYLIN-4012 optimize cache in TrieDictionary/TrieDictionaryForest
>  KYLIN-4012 optimize cache in TrieDictionary/TrieDictionaryForest

- .travis.yml
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingByLayer.java
jira: https://issues.apache.org/jira/browse/KYLIN-4087
> Kylin-4087 Use reduceGroup operator to optimize build cube step

- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingByLayer.java
jira : https://issues.apache.org/jira/browse/KYLIN-4090
> KYLIN-4090 Use mapPartition operator to optimize build cube step

- query/src/main/java/org/apache/kylin/query/util/QueryUtil.java
- query/src/test/java/org/apache/kylin/query/util/QueryUtilTest.java
Currently, there is a bug in sql conversion, as follow:
```sql
SELECT E_Name FROM Employees_China
UNION
SELECT E_Name FROM Employees_USA
```
will convert to
```sql
SELECT E_Name FROM Employees_China
UNION
SELECT E_Name FROM Employees_USA
LIMIT 50000
```
This limit is not working on the result of union, but on SELECT E_Name FROM Employees_USA.
We should use a more secure way to achieve the limit effect.
This pr fixed the bug, making sure to append limit or offset after sql does not change sql semantics
> [KYLIN-4068] append limit and offset to sql reliably

- webapp/app/partials/cubes/cube_detail.html
fix issue [KYLIN-4066](https://issues.apache.org/jira/browse/KYLIN-4066)
Signed-off-by: langdamao <lang--lang--lang@163.com>
> [KYLIN-4066] Fix No planner for not ROLE_ADMIN user

- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/FactDistinctColumnsReducerMapping.java
do % opration before abs ，more detail：https://issues.apache.org/jira/browse/KYLIN-4106
Signed-off-by: langdamao <lang--lang--lang@163.com>
> KYLIN-4106 fix Illegal partition for SelfDefineSortableKey

- core-metadata/src/main/java/org/apache/kylin/metadata/model/Segments.java
- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
- server-base/src/main/java/org/apache/kylin/rest/service/CubeService.java
See: https://issues.apache.org/jira/browse/KYLIN-4098
> KYLIN-4098: Add a cube auto merge api

- source-hive/src/main/java/org/apache/kylin/source/hive/GarbageCollectionStep.java
See: https://issues.apache.org/jira/browse/KYLIN-4111
Remove the quote in drop table statement because the quote is no need in drop
> KYLIN-4111: drop table failed with no valid privileges after KYLIN-3857

- core-common/src/main/resources/kylin-defaults.properties
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkExecutable.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkOnYarnConfigMapping.java
- examples/test_case_data/sandbox/kylin.properties
jira ref : https://issues.apache.org/jira/browse/KYLIN-4110
> KYLIN-4110 Provider config options to specify yarn queue and nodelabel

- source-hive/src/main/java/org/apache/kylin/source/hive/GarbageCollectionStep.java
Solve the problem that won't drop hive view intermediate table  when the job build cube with hive view finished.
> KYLIN-4121 Cleanup hive view intermediate tables after job be finished

- webapp/app/partials/jobs/jobs.html
See: https://issues.apache.org/jira/browse/KYLIN-4093
> KYLIN-4093: Slow query pages should be open to all users of the project

- webapp/app/js/controllers/cubeSchema.js
- webapp/app/js/services/cubes.js
Hello there! I found that I seem to screw up the original warehouse, I re-forked a code, the package of the request function I got services/cubes.js, and. . . In the code block I used async/await, I really can't think of anything else other than doing this after getting the return value. . . Do you have any opinions to guide you? ?
> KYLIN-4113 Remove the surplus allCubes field & optimize the request to get the cube name

- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingByLayer.java
JIRA issue ref : https://issues.apache.org/jira/browse/KYLIN-4124?filter=-1
> KYLIN-4124 Fix bug in map partition function en cuboid children is empty or null

- core-common/src/main/java/org/apache/kylin/common/util/HiveCmdBuilder.java
- core-common/src/test/java/org/apache/kylin/common/util/HiveCmdBuilderTest.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkBatchCubingJobBuilder2.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkBatchMergeJobBuilder2.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java
- source-hive/src/main/java/org/apache/kylin/source/hive/CreateFlatHiveTableStep.java
- source-hive/src/main/java/org/apache/kylin/source/hive/CreateMrHiveDictStep.java
- source-hive/src/main/java/org/apache/kylin/source/hive/GarbageCollectionStep.java
- source-hive/src/main/java/org/apache/kylin/source/hive/RedistributeFlatHiveTableStep.java
See: https://issues.apache.org/jira/browse/KYLIN-4101
> KYLIN-4101: set hive and spark job name when building cube

- core-common/src/main/java/org/apache/kylin/common/persistence/ResourceTool.java
See: https://issues.apache.org/jira/browse/KYLIN-4095
> KYLIN-4095: Add RESOURCE_PATH_PREFIX option in ResourceTool

- pom.xml
- stream-coordinator/pom.xml
This reverts commit 970899011211b285b78cfc3a63ac5025436ddb59.
> Revert "#KYLIN-4044, upgrade curator dependency version"

- build/script/download-flink.sh
- engine-flink/pom.xml
JIRA ref: https://issues.apache.org/jira/browse/KYLIN-3921
> [KYLIN-3921] Bump Flink version from 1.7.1 to 1.9.0

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-job/src/main/java/org/apache/kylin/job/execution/ExecutableManager.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java
see: https://issues.apache.org/jira/browse/KYLIN-4143
> KYLIN-4143 truncate spark executable job output

- core-common/src/main/java/org/apache/kylin/common/persistence/PushdownResourceStore.java
- core-common/src/main/java/org/apache/kylin/common/persistence/ResourceStore.java
- server-base/src/main/java/org/apache/kylin/rest/job/MetadataCleanupJob.java
Please refer to https://issues.apache.org/jira/browse/KYLIN-4153 for  deatil.
> KYLIN-4153 Delete marker if real file not exists

- server-base/src/main/java/org/apache/kylin/rest/service/AccessService.java
- server/src/test/java/org/apache/kylin/rest/service/AccessServiceTest.java
See: https://jira.apache.org/jira/browse/KYLIN-4103
> KYLIN-4103: Make the user string in granting operation of project is case insensitive

- core-job/src/main/java/org/apache/kylin/job/JobSearchResult.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/JobInfoConverter.java
- server-base/src/main/java/org/apache/kylin/rest/controller/JobController.java
- server-base/src/main/java/org/apache/kylin/rest/service/JobService.java
- webapp/app/js/controllers/job.js
- webapp/app/js/model/jobConfig.js
- webapp/app/js/model/jobListModel.js
- webapp/app/js/services/jobs.js
- webapp/app/partials/jobs/jobList.html
See: https://jira.apache.org/jira/browse/KYLIN-4100
> KYLIN-4100: Add overall job number statistics in monitor page

- build/bin/metastore.sh
https://issues.apache.org/jira/browse/KYLIN-4095
> KYLIN-4095: Add RESOURCE_PATH_PREFIX option in ResourceTool (addendum)

- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
Previous code change will cause NPE for "SELECT * from DIMENSION_TABLE" when dimension table name use alias, here to fix this.
> KYLIN-3628 Fix regression bug

- server-base/src/main/java/org/apache/kylin/rest/service/StreamingV2Service.java
- webapp/app/partials/cubes/cube_detail.html
issue link: https://issues.apache.org/jira/browse/KYLIN-4147
> Fix KYLIN-4147 User has project's admin permission but doesn't have permission to see the Storage/Planner/streaming tab in Model page

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-dictionary/src/main/java/org/apache/kylin/dict/AppendTrieDictionary.java
- core-dictionary/src/test/java/org/apache/kylin/dict/AppendTrieDictionaryTest.java
See: https://issues.apache.org/jira/browse/KYLIN-4097
> KYLIN-4097: Throw exception when too many dict slice evictions in AppendTrieDictionary

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- core-cube/src/test/java/org/apache/kylin/cube/CubeManagerTest.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/Segments.java
- server-base/src/main/java/org/apache/kylin/rest/job/StorageCleanupJob.java
See: https://issues.apache.org/jira/browse/KYLIN-3917
> KYLIN-3917: Add max segment merge span to cleanup intermediate data of cube building

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- server-base/src/main/java/org/apache/kylin/rest/service/HBaseInfoUtil.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/cube/v2/CubeHBaseEndpointRPC.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/cube/v2/CubeHBaseScanRPC.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/util/HBaseUnionUtil.java
See: https://issues.apache.org/jira/browse/KYLIN-4095
> KYLIN-4175: Support secondary hbase storage config for hbase cluster migration

- core-cube/src/main/java/org/apache/kylin/cube/model/validation/CubeMetadataValidator.java
see: https://issues.apache.org/jira/browse/KYLIN-4207
> KYLIN-4207: fix exception while use cube metadata extra validators

- build/script/build.sh
make sure calcite package is updated automatically
> make sure calcite package is updated automatically

- website/_docs/install/configuration.cn.md
- website/_docs/install/configuration.md
add config kylin.source.hive.intermediate-table-prefix introduction
> KYLIN-4205 configuration support set hive.intermediate-table-prefix

- tool-assembly/pom.xml
see https://issues.apache.org/jira/browse/KYLIN-4244
> KYLIN-4244: add com.tdunning shade in tool assembly

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-dictionary/src/main/java/org/apache/kylin/dict/AppendTrieDictionary.java
- core-dictionary/src/test/java/org/apache/kylin/dict/AppendTrieDictionaryTest.java
> KYLIN-4097 Guava 11 compatibility

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
> Revert "KYLIN-3999, make kylin.query.enable-dynamic-column default true"

- webapp/app/partials/admin/change_pwd.html
- webapp/app/partials/admin/user_create.html
KYLIN-4248 When adding a user, the prompt message is incorrect when the user name is empty.
> KYLIN-4248 When adding a user, the prompt message is incorrect when the user name is empty.

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-job/src/main/java/org/apache/kylin/job/impl/threadpool/DefaultFetcherRunner.java
- core-job/src/main/java/org/apache/kylin/job/impl/threadpool/PriorityFetcherRunner.java
See: https://issues.apache.org/jira/browse/KYLIN-4178
> KYLIN-4178: job scheduler safe mode

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
it's a bug of KYLIN-4178
see: https://issues.apache.org/jira/browse/KYLIN-4178
> fix bug of KYLIN-4178

- build/bin/download-spark.sh
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-job/src/main/java/org/apache/kylin/job/constant/ExecutableConstants.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/TblColRef.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/JobBuilderSupport.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkBatchCubingJobBuilder2.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkBuildDictionary.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java
> KYLIN-4187 build dimension dictionary using spark

- webapp/app/js/controllers/query.js
https://issues.apache.org/jira/browse/KYLIN-1716
> KYLIN-1716 UI Location Change Bug Fix

- core-common/src/main/java/org/apache/kylin/common/lock/DistributedLock.java
- core-job/src/main/java/org/apache/kylin/job/lock/zookeeper/ZookeeperDistributedLock.java
- core-job/src/main/java/org/apache/kylin/job/lock/zookeeper/ZookeeperJobLock.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/StreamingCubingJobBuilder.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/CubeJobLockUtil.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/MapReduceExecutable.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/streaming/SaveDictStep.java
- server-base/src/main/java/org/apache/kylin/rest/service/JobService.java
issue link: https://issues.apache.org/jira/browse/KYLIN-4165
> [KYLIN-4165] Fix RT OLAP building job on "Save Cube Dictionaries" step concurrency error

- website/_docs/install/configuration.cn.md
- website/_docs/install/configuration.md
see: https://issues.apache.org/jira/browse/KYLIN-4267
> KYLIN-4267: Add doc for KYLIN-4178

- build/conf/kylin-server-log4j.properties
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/java/org/apache/kylin/common/util/DateFormat.java
- core-common/src/main/java/org/apache/kylin/common/util/TimeUtil.java
- core-common/src/main/resources/kylin-defaults.properties
- core-metadata/src/main/java/org/apache/kylin/dimension/TimeDerivedColumnType.java
- core-storage/src/main/java/org/apache/kylin/storage/gtrecord/CubeTupleConverter.java
- query/src/main/java/org/apache/kylin/query/relnode/OLAPFilterRel.java
- query/src/main/java/org/apache/kylin/query/relnode/visitor/TupleFilterVisitor.java
- server-base/src/main/java/org/apache/kylin/rest/controller/StreamingV2Controller.java
- storage-stream/src/main/java/org/apache/kylin/storage/stream/StreamStorageQuery.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/StreamMetadataStore.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/ZookeeperStreamMetadataStore.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/assign/AssignmentsCache.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/assign/DefaultAssigner.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/coordinate/BuildJobSubmitter.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/coordinate/ReceiverClusterManager.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/coordinate/StreamingCoordinator.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/doctor/ClusterDoctor.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/doctor/ClusterStateChecker.java
- stream-coordinator/src/test/java/org/apache/kylin/stream/coordinator/coordinate/BuildJobSubmitterTest.java
- stream-coordinator/src/test/java/org/apache/kylin/stream/coordinator/coordinate/StreamingTestBase.java
- stream-core/src/main/java/org/apache/kylin/stream/core/client/ReceiverAdminClient.java
- stream-core/src/main/java/org/apache/kylin/stream/core/consumer/StreamingConsumerChannel.java
- stream-core/src/main/java/org/apache/kylin/stream/core/query/StreamingDataQueryPlanner.java
- stream-core/src/main/java/org/apache/kylin/stream/core/query/StreamingTupleConverter.java
- stream-core/src/main/java/org/apache/kylin/stream/core/source/IStreamingMessageParser.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/FragmentFileSearcher.java
- stream-core/src/main/java/org/apache/kylin/stream/core/util/CompareFilterTimeRangeChecker.java
- stream-source-kafka/src/main/java/org/apache/kylin/stream/source/kafka/TimedJsonStreamParser.java
- Fix bugs when cubing job been dropped
- Drop former segment info when submit new one
- Add new logfile for streaming coordinator more log to let diagnostic easier.
> KYLIN-4167 Phase2

- core-metadata/src/main/java/org/apache/kylin/metadata/model/PartitionDesc.java
- core-metadata/src/test/java/org/apache/kylin/metadata/model/PartitionDescTest.java
- webapp/app/js/controllers/modelConditionsSettings.js
- webapp/app/partials/modelDesigner/conditions_settings.html
https://issues.apache.org/jira/browse/KYLIN-4211
PartitionDesc support custom year、month、day partitions name
> KYLIN-4211 PartitionDesc support custom year、month、day partitions name

- metrics-reporter-hive/src/main/java/org/apache/kylin/metrics/lib/impl/hive/HiveProducer.java
see: https://issues.apache.org/jira/browse/KYLIN-4225
> KYLIN-4225 close hive session manually

- build/bin/kylin-port-replace-util.sh
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- server-base/src/main/java/org/apache/kylin/rest/controller/StreamingV2Controller.java
- tool/src/main/java/org/apache/kylin/tool/ClientEnvExtractor.java
- tool/src/test/java/org/apache/kylin/tool/ClientEnvExtractorTest.java
Please see https://issues.apache.org/jira/browse/KYLIN-4197 for detail.
> KYLIN-4197 Set deadline for ClientEnvExtractor

- docker/build_image.sh
see: https://issues.apache.org/jira/browse/KYLIN-4272
> KYLIN-4272: optimize docker build scripts

- webapp/app/js/controllers/query.js
KYLIN-4252 Fix the error "Cannot read property 'index' of null" in visualization page
> KYLIN-4252

- webapp/app/index.html
- webapp/app/js/controllers/userProfile.js
- webapp/app/partials/admin/change_pwd.html
- webapp/app/partials/header.html
- webapp/app/partials/user/profile.html
- webapp/app/routes.json
see: https://issues.apache.org/jira/browse/KYLIN-4212
> KYLIN-4212 add user profile page allowing to change password

- docker/Dockerfile
berkeley mirror's apache-maven resource is invalid
> Minor, change resource URL in Dockerfile

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/java/org/apache/kylin/common/SourceDialect.java
- core-job/src/main/java/org/apache/kylin/job/JoinedFlatTable.java
- core-job/src/main/java/org/apache/kylin/job/util/FlatTableSqlQuoteUtils.java
- core-job/src/test/java/org/apache/kylin/job/util/FlatTableSqlQuoteUtilsTest.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/TableDesc.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/TableRef.java
- datasource-sdk/pom.xml
- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/adaptor/AbstractJdbcAdaptor.java
- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/adaptor/PostgresqlAdaptor.java
- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/framework/JdbcConnector.java
- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/framework/SourceConnectorFactory.java
- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/framework/conv/DefaultConfigurer.java
- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/framework/conv/GenericSqlConverter.java
- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/framework/conv/SqlConverter.java
- datasource-sdk/src/main/resources/datasource/postgresql.xml
- datasource-sdk/src/test/java/org/apache/kylin/sdk/datasource/framework/conv/PostgresqlSqlConverterTest.java
- source-hive/src/main/java/org/apache/kylin/source/hive/HiveInputBase.java
- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/JdbcExplorer.java
- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/JdbcHiveInputBase.java
- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/JdbcHiveMRInput.java
- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/JdbcHiveSparkInput.java
- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/extensible/JdbcHiveInputBase.java
- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/metadata/JdbcMetadataFactory.java
- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/metadata/PostgresqlJdbcMetadata.java
- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/metadata/SQLServerJdbcMetadata.java
- source-jdbc/src/test/java/org/apache/kylin/source/jdbc/JdbcHiveInputBaseTest.java
- source-kafka/src/main/java/org/apache/kylin/source/kafka/KafkaInputBase.java
> KYLIN-3832 Query pushdown support postgresql

- core-cube/src/main/java/org/apache/kylin/cube/model/validation/rule/StreamingCubeRule.java
- server-base/src/main/java/org/apache/kylin/rest/service/ModelService.java
Please see https://issues.apache.org/jira/browse/KYLIN-4300 for detail.
> fix bug KYLIN-4300.

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/java/org/apache/kylin/common/util/HadoopUtil.java
- core-job/src/main/java/org/apache/kylin/job/constant/ExecutableConstants.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/JobBuilderSupport.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/KylinKryoRegistrator.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkBatchCubingJobBuilder2.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkUHCDictionary.java
> KYLIN-4192 build uhc dictionary using spark

- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/ColumnarStoreDimDesc.java
- stream-core/src/main/java/org/apache/kylin/stream/core/storage/columnar/ColumnarStoreMetricsDesc.java
See https://issues.apache.org/jira/browse/KYLIN-4243 for detail.
> fix bug in KYLIN-4243

- build/bin/kylin.sh
- core-common/src/main/resources/kylin-defaults.properties
- examples/test_case_data/localmeta/kylin.properties
KYLIN-4271 Use configurable certificate to support LDAPs authentication of Kylin
> KYLIN-4271

- query/src/main/java/org/apache/kylin/query/util/QueryUtil.java
KYLIN-4324：User query returns Unknown error
> Collect information of NumberFormatException

- website/_docs/howto/howto_ldap_and_sso.md
update the document named 'Secure with LDAP and SSO'
> KYLIN-4271 update the document named 'Secure with LDAP and SSO'

- source-hive/src/main/java/org/apache/kylin/source/hive/HiveMetaStoreClientFactory.java
Fix for `getHiveMetastoreClient ` is not available when switch to CDH profile .
> Fix for KYLIN-4206

- webapp/app/partials/cubeDesigner/measures.html
Param Value should be required when creating a cube and adding a new measure.
> KYLIN-4359

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- storage-hbase/src/test/java/org/apache/kylin/storage/hbase/cube/v2/coprocessor/endpoint/CubeVisitServiceTest.java
> Revert "KYLIN-4322: set storage.hbase.endpoint-compress-result default value …"

- core-job/src/main/java/org/apache/kylin/job/impl/threadpool/DefaultFetcherRunner.java
- core-job/src/main/java/org/apache/kylin/job/impl/threadpool/FetcherRunner.java
- core-job/src/main/java/org/apache/kylin/job/impl/threadpool/PriorityFetcherRunner.java
This PR is recommit for KYLIN-4328. Add modify PriorityFetcherRunner.java on old PR.
The old PR is https://github.com/apache/kylin/pull/1064
Thanks.
> KYILN-4328 Add cache for succeed jobids in job scheduler

- engine-mr/src/main/java/org/apache/kylin/engine/mr/streaming/RowRecordReader.java
This reverts commit 3eff292e7d0ecfca5a68d55f5c62243da719ac89.
> Revert "KYLIN-4349 Close InputStream in RowRecordReader.initReaders()"

- core-job/src/main/java/org/apache/kylin/job/impl/threadpool/FetcherRunner.java
Add code be used to push succeed jobid to hashset.
At last time commit some code is missing,I'm so sorry to submit it again.
The last time PR link #1098.
Thanks.
> KYLIN-4328 Add code be used to push succeed jobid to hashset.

- webapp/app/partials/models/models_tree.html
see: https://issues.apache.org/jira/browse/KYLIN-4377
> KYLIN-4377: allow project administrator to operate hybrid model

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- core-cube/src/main/java/org/apache/kylin/cube/CubeSegment.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/CubingJob.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/CubeStatsReader.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/UpdateCubeInfoAfterBuildStep.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/UpdateCubeInfoAfterMergeStep.java
see: https://issues.apache.org/jira/browse/kylin-4185
> KYLIN-4185: optimize CuboidSizeMap by using historical segments

- source-hive/src/main/java/org/apache/kylin/source/hive/HiveMetaStoreClientFactory.java
Check https://issues.apache.org/jira/browse/KYLIN-4383.
> KYLIN-4383 Fix reflection error

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/CubeHFileJob.java
htable name can not be casted to upper
> htable name can not cast to upper

- website/_docs/index.cn.md
- website/_docs/index.md
- website/_docs30/index.cn.md
- website/_docs30/index.md
- website/_docs31/index.cn.md
- website/_docs31/index.md
- website/index.cn.md
- website/index.md
As we discussed in the mailing list, change Kylin's slogan to "Analytical Data Warehouse for big data"
> Document: change slogan

- core-job/src/main/java/org/apache/kylin/job/execution/CardinalityExecutable.java
- server-base/src/main/java/org/apache/kylin/rest/job/MetadataCleanupJob.java
- server-base/src/main/java/org/apache/kylin/rest/service/TableService.java
see: https://issues.apache.org/jira/browse/KYLIN-4356
> KYLIN-4356: clean outdate column cardinality job

- server-base/src/main/java/org/apache/kylin/rest/service/JobService.java
- server-base/src/main/java/org/apache/kylin/rest/service/ProjectService.java
Kylin needn't use "org.apache.directory.api.util.Strings"  to import extra dependency
> KYLIN-4132 Kylin needn't use "org.apache.directory.api.util.Strings" 

- build/bin/download-flink.sh
- build/bin/find-flink-dependency.sh
- build/bin/kylin.sh
- engine-flink/pom.xml
- pom.xml
Please ignore the pull request #1128, because of the branch had two extra commits issue.
> KYLIN-4389 Change Flink jar dependence from compile to provided

- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingMerge.java
Please ignore the pull request #1125, because the branch had the extra commit issue.
> KYLIN-4387 Flink cubing merge step failed

- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingByLayer.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkCubingMerge.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/JobBuilderSupport.java
Please refer jira: https://issues.apache.org/jira/browse/KYLIN-4402
> KYLIN-4402 Missing data size in web UI with flink cubing

- build/bin/system-cube.sh
see: https://issues.apache.org/jira/browse/KYLIN-4400
use the same way in sample.sh
> KYLIN-4400: use client in config to submit sql in system-cube.sh

- .github/pull_request_template.md
> Some change on pr template

- core-common/src/main/java/org/apache/kylin/common/util/CliCommandExecutor.java
- core-common/src/test/java/org/apache/kylin/common/util/CliCommandExecutorTest.java
- server-base/src/main/java/org/apache/kylin/rest/service/CubeService.java
> KYLIN-4426 Refine CliCommandExecutor

- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/MapReduceExecutable.java
see: https://issues.apache.org/jira/browse/KYLIN-4379
> KYLIN-4379: use config overwrite for all MR job

- build/bin/diag.sh
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/java/org/apache/kylin/common/util/HadoopUtil.java
- core-common/src/main/java/org/apache/kylin/common/util/ToolUtil.java
- server-base/src/main/java/org/apache/kylin/rest/service/DiagnosisService.java
- tool-assembly/pom.xml
- tool/pom.xml
- tool/src/main/java/org/apache/kylin/tool/DiagnosisInfoCLI.java
- tool/src/main/java/org/apache/kylin/tool/JobDiagnosisInfoCLI.java
- tool/src/main/java/org/apache/kylin/tool/extractor/AbstractInfoExtractor.java
- tool/src/main/java/org/apache/kylin/tool/extractor/ClientEnvExtractor.java
- tool/src/main/java/org/apache/kylin/tool/extractor/CubeMetaExtractor.java
- tool/src/main/java/org/apache/kylin/tool/extractor/HBaseUsageExtractor.java
- tool/src/main/java/org/apache/kylin/tool/extractor/HadoopConfExtractor.java
- tool/src/main/java/org/apache/kylin/tool/extractor/HiveConfigCLI.java
- tool/src/main/java/org/apache/kylin/tool/extractor/JStackExtractor.java
- tool/src/main/java/org/apache/kylin/tool/extractor/JobInstanceExtractor.java
- tool/src/main/java/org/apache/kylin/tool/extractor/KylinLogExtractor.java
- tool/src/main/java/org/apache/kylin/tool/extractor/MrJobInfoExtractor.java
- tool/src/main/java/org/apache/kylin/tool/extractor/SparkEnvInfoExtractor.java
- tool/src/main/java/org/apache/kylin/tool/extractor/YarnLogExtractor.java
- tool/src/test/java/org/apache/kylin/tool/ClientEnvExtractorTest.java
- tool/src/test/java/org/apache/kylin/tool/CubeMetaExtractorTest.java
> KYLIN-4425 Refactor diagnosis module

- engine-mr/src/main/java/org/apache/kylin/engine/mr/CubingJob.java
see: https://issues.apache.org/jira/browse/KYLIN-4412
> KYLIN-4412 Show cluster name in email title

- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
> KYLIN-3628 Fix the silently swallow legit exceptions and reduce code duplication

- core-cube/src/main/java/org/apache/kylin/cube/common/SegmentPruner.java
- core-cube/src/test/java/org/apache/kylin/cube/common/SegmentPrunerTest.java
> KYLIN-4354 Prune segment not using given filter when using jdbc preparestatement

- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- core-metrics/src/main/java/org/apache/kylin/metrics/MetricsManager.java
Fix FindBugs reported coding issues; Not bugs.
> minor, fix several findbugs issues

- metrics-reporter-hive/src/main/java/org/apache/kylin/metrics/lib/impl/hive/HiveProducer.java
> KYLIN-4385 Fix HiveProducer can not write to Hive Table(AWS Azure)

- website/_data/docs.yml
- website/_docs/gettingstarted/quickstart.cn.md
- website/_docs/gettingstarted/quickstart.md
> Add Quick Start EN version and fix format

- website/_docs/howto/howto_use_restapi.cn.md
- website/_docs/howto/howto_use_restapi.md
- website/_docs31/howto/howto_use_restapi.cn.md
- website/_docs31/howto/howto_use_restapi.md
> KYLIN-3825 Add ACL Rest APIs to document

- webapp/app/js/controllers/cubeSchema.js
> KYLIN-4119 Project ADMIN can not operate the Hybrid model

- website/_docs/gettingstarted/quickstart.cn.md
- website/_docs/gettingstarted/quickstart.md
> Fix quick start document display problems

- core-cube/src/main/java/org/apache/kylin/cube/model/CubeDesc.java
- core-cube/src/main/java/org/apache/kylin/cube/model/IHBaseMappingAdapter.java
> KYLIN-3844 Add interface for hbaseMappingAdapter

- core-common/src/main/java/org/apache/kylin/common/util/Array.java
> minor, if o == null, o instanceof Array will return false

- docker/entrypoint.sh
When run docker image for the first time, sometimes hive command will be executed concurrently and it will insert two version records into the VERSION table, this will lead to start kylin unsuccessfully.
**error messages:** 
Something wrong with Hive CLI or Beeline, please execute Hive CLI or Beeline CLI in terminal to find the root cause.
call script $KYLIN_HOME/bin/check-hive-usability.sh before all kylin.sh, it will insert one version record into VERSION table .
1. cd kylin/docker
2. ./build_image.sh
3. docker run -d -m 8G -p 7070:7070 -p 8088:8088 -p 50070:50070 -p 8032:8032 -p 8042:8042 -p 16010:16010 -p 8998:8998 -p 2181:2181 apachekylin/apache-kylin-standalone:latest
4. all dependents and kylin worked successfully.
5. docker container stop container-id
6. docker container start …
> [KYLIN-4472] After running docker image, it sometimes failed to run kylin successfully.

- website/_data/docs-cn.yml
- website/_data/docs.yml
- website/_data/docs31-cn.yml
- website/_data/docs31.yml
- website/_docs/install/Kylin_kubernetes.cn.md
- website/_docs/install/Kylin_kubernetes.md
- website/_docs31/install/Kylin_kubernetes.cn.md
- website/_docs31/install/Kylin_kubernetes.md
> KYLIN-4448 Kylin on Kubernetes Doc

- metrics-reporter-hive/src/main/java/org/apache/kylin/metrics/lib/impl/hive/HiveProducer.java
- server/src/main/resources/kylinMetrics.xml
> KYLIN-4385 HiveSink support object storage

- metrics-reporter-hive/src/main/java/org/apache/kylin/metrics/lib/impl/hive/HiveProducer.java
> KYLIN-4385 Only hdfs is appendable

- kylin-it/src/test/java/org/apache/kylin/query/KylinTestBase.java
> KYLIN-4407 fix IT

- webapp/app/partials/cubeDesigner/measures.html
> KYLIN-4490 Fix minor bug which add measure on frontend

- build/bin/check-env.sh
> KYLIN-3698 check-env.sh should print more details about checking items

- docker/Dockerfile
> KYLIN-4494 fix missing 'hive-hcatalog-core.jar' error when running cube build with spark

- website/_docs/tutorial/cube_spark.cn.md
- website/_docs/tutorial/sql_reference.cn.md
- website/_docs30/tutorial/cube_spark.cn.md
- website/_docs30/tutorial/sql_reference.cn.md
- website/_docs31/tutorial/cube_spark.cn.md
- website/_docs31/tutorial/sql_reference.cn.md
> Remove unnecessary extra characters

- source-kafka/src/main/java/org/apache/kylin/source/kafka/KafkaMRInput.java
> KYLIN-4151 FileSplit ClassCastException in KafkaMRInput

- storage-hbase/pom.xml
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/CreateHTableJob.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/FlinkCubeHFile.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/HBaseFlinkOutputTransition.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/HBaseFlinkSteps.java
Add flink cubing step: convert to HFile
> KYLIN-3849 Flink cubing step : convert to HFile

- core-metadata/src/test/java/org/apache/kylin/metadata/model/PartitionDescTest.java
- webapp/app/js/model/cubeConfig.js
- webapp/app/partials/modelDesigner/conditions_settings.html
Support custom date format for partition date column.
> KYLIN-4495 Support custom date format for partition date column

- webapp/app/js/controllers/sourceMeta.js
> KYLIN-4510 Automatically refresh the page after reload table

- source-hive/src/main/java/org/apache/kylin/source/hive/BeelineHiveClient.java
- source-hive/src/main/java/org/apache/kylin/source/hive/CLIHiveClient.java
- source-hive/src/main/java/org/apache/kylin/source/hive/HiveTableMeta.java
- source-hive/src/main/java/org/apache/kylin/source/hive/HiveTableMetaBuilder.java
see https://issues.apache.org/jira/browse/KYLIN-4315
> KYLIN-4315 use metadata numRows in beeline client for quick row counting

- build/bin/check-env.sh
- build/bin/find-flink-dependency.sh
- build/bin/find-kafka-dependency.sh
- build/bin/find-spark-dependency.sh
> KYLIN-3698 Fix kylin.sh can't export spark/flink/kafka dependency

- website/_docs/howto/howto_use_restapi.cn.md
- website/_docs/howto/howto_use_restapi.md
> Update website RESTful API page

- server-base/src/main/java/org/apache/kylin/rest/controller/ModelController.java
> KYLIN-4469 Fix clone model error

- metrics-reporter-hive/src/main/java/org/apache/kylin/metrics/lib/impl/hive/HiveProducer.java
bug fix of jira
https://issues.apache.org/jira/browse/KYLIN-4496
> KYLIN-4496: Metric data missing

- server/pom.xml
Problems:
After upgrading httpclient version to 4.3.6, on CDH 5.7 env it will lead to LinkageError occured, because it loades 'HttpContext' class in two different ClassLoader (CustomizedWebappClassloader and AppClassLoader):
**Error message below:**
`java.lang.LinkageError: loader constraint violation: when resolving method "org.apache.http.protocol.HttpCoreContext.<init>(Lorg/apache/http/protocol/HttpContext;)V" the class loader (instance of org/apache/kylin/ext/CustomizedWebappClassloader) of the current class, org/apache/http/client/protocol/HttpClientContext, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/apache/http/protocol/HttpCoreContext, have different Class objects for the type org/apache/http/protocol/HttpContext used in …
> KYLIN-4523 Fix 'LinkageError' error after upgrading httpclient version to 4.3.6

- build/bin/system-cube.sh
Problems:
There are some issues in script 'system-cube.sh':
1. can not create database 'KYLIN' in hive;
2. the parameter 'sample_database' is error;
If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by …
> KYLIN-4524 system-cube.sh script can't work

- webapp/app/js/model/jobListModel.js
> KYLIN-4537 Give a friendly tips to the user when getting task list fails

- core-common/src/main/java/org/apache/kylin/common/util/JsonUtil.java
> remove the usage for jackson enableDefaultTyping()

- storage-stream/src/main/java/org/apache/kylin/storage/stream/StreamStorageQuery.java
> KYLIN-4352 maxHistorySegmentTime should be reasonable

- query/src/main/java/org/apache/kylin/query/adhoc/JdbcPushDownConnectionManager.java
> KYLIN-4104 Fix multi jdbc push down engine bug

- build/bin/download-flink.sh
- pom.xml
- [√ ] I have create an issue on [Kylin's jira](https://issues.apache.org/jira/browse/KYLIN), and have described the bug/feature there in detail
If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by …
> KYLIN-4391 Bump Flink version from 1.9.0 to 1.9.2

- build/bin/find-kafka-dependency.sh
- engine-spark/src/main/java/org/apache/kylin/engine/spark/KylinKryoRegistrator.java
> KYLIN-4394 Fix NoSuchMethod in spark build job after update guava

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/java/org/apache/kylin/common/util/CliCommandExecutor.java
- core-common/src/test/java/org/apache/kylin/common/util/CliCommandExecutorTest.java
- server-base/src/main/java/org/apache/kylin/rest/controller/AdminController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/DiagnosisController.java
- server-base/src/main/java/org/apache/kylin/rest/service/AdminService.java
- disbale setting kylin config
- add check for database name
- add check for command parameter
If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by explaining why you chose the solution you did and what …
> Minor, refactor

- kylin-it/pom.xml
> KYLIN-4485 Fix NoSuchMethodError in kylin-it

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-metrics/src/main/java/org/apache/kylin/metrics/lib/impl/RecordEventTimeDetail.java
- core-metrics/src/test/java/org/apache/kylin/metrics/lib/impl/RecordEventTimeDetailTest.java
> KYLIN-4571 Add config kylin.metrics.event-time-zone for indicating RecordEventTimeDetail time zone

- NOTICE
> KYLIN-4512 Update NOTICE

- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/BatchConstants.java
- source-hive/src/main/java/org/apache/kylin/source/hive/HiveInputBase.java
- source-hive/src/main/java/org/apache/kylin/source/hive/MRHiveDictUtil.java
> KYLIN-4343 Cleanup intermediate dict table

- tool/src/test/java/org/apache/kylin/tool/metrics/systemcube/SCCreatorTest.java
- tool/src/test/resources/SCSinkTools.json
> KYLIN-4371 Fix ut

- tool/src/main/java/org/apache/kylin/tool/metrics/systemcube/CubeDescCreator.java
> KYLIN-4580 Add 90, 360 days auto-merge thresholds for system cubes

- build/bin/kylin.sh
- core-common/src/main/java/org/apache/kylin/common/util/CliCommandExecutor.java
- core-metrics/pom.xml
- pom.xml
- server-base/pom.xml
- server/pom.xml
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/CreateHTableJob.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/CubeHFileJob.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/HFileOutputFormat3.java
- stream-receiver/pom.xml
> Fix issue in hdp3 env

- query/src/main/java/org/apache/kylin/query/relnode/OLAPAggregateRel.java
> KYLIN-4275 Fix avg function not working

- core-metrics/src/main/java/org/apache/kylin/metrics/lib/impl/TimedRecordEvent.java
- metrics-reporter-hive/pom.xml
- metrics-reporter-hive/src/main/java/org/apache/kylin/metrics/lib/impl/hive/HiveProducer.java
- metrics-reporter-hive/src/main/java/org/apache/kylin/metrics/lib/impl/hive/HiveProducerRecord.java
- metrics-reporter-hive/src/main/java/org/apache/kylin/metrics/lib/impl/hive/HiveReservoirReporter.java
- metrics-reporter-hive/src/main/java/org/apache/kylin/tool/metrics/systemcube/HiveTableCreator.java
- metrics-reporter-hive/src/test/java/org/apache/kylin/metrics/lib/impl/hive/HiveProducerRecordTest.java
- metrics-reporter-hive/src/test/java/org/apache/kylin/metrics/lib/impl/hive/HiveProducerTest.java
- metrics-reporter-hive/src/test/java/org/apache/kylin/metrics/lib/impl/hive/HiveReservoirReporterTest.java
- metrics-reporter-kafka/pom.xml
- metrics-reporter-kafka/src/main/java/org/apache/kylin/metrics/lib/impl/kafka/KafkaActiveReserviorListener.java
- metrics-reporter-kafka/src/main/java/org/apache/kylin/metrics/lib/impl/kafka/KafkaReservoirReporter.java
- metrics-reporter-kafka/src/test/java/org/apache/kylin/metrics/lib/impl/kafka/KafkaReservoirReporterTest.java
> KYLIN-4508 Add unit test for core-metrics module & reporters

- core-common/src/main/java/org/apache/kylin/common/util/CliCommandExecutor.java
- server-base/src/main/java/org/apache/kylin/rest/controller/DiagnosisController.java
- server-base/src/main/java/org/apache/kylin/rest/msg/CnMessage.java
- server-base/src/main/java/org/apache/kylin/rest/msg/Message.java
- server-base/src/main/java/org/apache/kylin/rest/service/DiagnosisService.java
- server-base/src/main/java/org/apache/kylin/rest/util/AclEvaluate.java
When download diagnosis package, it's better to check whether project/jobid exists, if not, it raise a BadRequestException with XXX doesn't exist instead of NPE.
If this is a relatively large or complex change, kick off the discussion at user@kylin or …
> KYLIN-4617 Check whether project/jobid exists before download diagnosis package

- .gitignore
- x] I have create an issue on [Kylin's jira](https://issues.apache.org/jira/browse/KYLIN), and have described the bug/feature there in detail
If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by …
> KYLIN-4572 Add "build/VERSION" to .gitignore

- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/cluster/parser/FairSchedulerParser.scala
> KYLIN-4541 Optimizing the error information in job build

- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- core-metadata/src/main/java/org/apache/kylin/metadata/project/ProjectManager.java
- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/ModelController.java
- server-base/src/main/java/org/apache/kylin/rest/controller/ProjectController.java
- server-base/src/main/java/org/apache/kylin/rest/service/CubeService.java
- server-base/src/main/java/org/apache/kylin/rest/service/ProjectService.java
- server/src/test/java/org/apache/kylin/rest/controller/CubeControllerTest.java
- server/src/test/java/org/apache/kylin/rest/controller/ProjectControllerTest.java
- webapp/app/js/controllers/cube.js
- webapp/app/js/controllers/projects.js
- webapp/app/js/services/cubes.js
- webapp/app/js/services/projects.js
- webapp/app/partials/cubes/cube_detail.html
- webapp/app/partials/projects/project_detail.html
1. Add interfaces to transfer cube/model/project ownership
2. Add entrance in web page
> KYLIN-4551 Provide interfaces to transfer cube/model/project ownership

- docker/Dockerfile
- docker/Dockerfile_hadoop
- docker/README.md
- docker/build_image.sh
- docker/entrypoint.sh
- docker/run_container.sh
Upgrade kylin docker image for kylin 3.1.0
> KYLIN-4618 Upgrade kylin docker image for kylin 3.1.0

- website/_docs/install/kylin_cluster.cn.md
- website/_docs/install/kylin_cluster.md
> Add job scheduler blog wiki link for kylin cluster deployment page

- build/smoke-test/smoke-test.sh
- build/smoke-test/testBuildCube.py
- build/smoke-test/testQuery.py
- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
> KYLIN-4581 Add spark and flink engine test case for release test

- build/bin/find-hive-dependency.sh
- build/bin/kylin.sh
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-cube/src/main/java/org/apache/kylin/cube/CubeSegment.java
- core-cube/src/main/java/org/apache/kylin/cube/model/CubeDesc.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/JobBuilderSupport.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/DictionaryGetterUtil.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/BuildGlobalHiveDictPartBuildJob.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/ExtractDictionaryFromGlobalMapper.java
- source-hive/src/main/java/org/apache/kylin/source/hive/HiveInputBase.java
- source-hive/src/main/java/org/apache/kylin/source/hive/MRHiveDictUtil.java
> KYLIN-4616 Auto detect the default value of config kylin.source.hive.databasedir

- webapp/app/js/controllers/query.js
- webapp/app/partials/query/query.html
> KYLIN-4527 Beautify the drop-down list of the cube on query page

- core-common/src/main/resources/kylin-defaults.properties
- examples/test_case_data/sandbox/kylin.properties
> KYLIN-4632 No such element exception:spark.driver.cores

- build/bin/sample.sh
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/resources/kylin-defaults.properties
- core-metadata/src/main/java/org/apache/kylin/metadata/model/IEngineAware.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/IStorageAware.java
- examples/test_case_data/parquet_test/cube_desc/ci_inner_join_cube.json
- examples/test_case_data/parquet_test/cube_desc/ci_left_join_cube.json
- examples/test_case_data/parquet_test/cube_desc/ssb.json
- server/src/test/java/org/apache/kylin/rest/service/AdminServiceTest.java
> KYLIN-4631 Set the default build engine type to spark for Kylin on Parquet

- examples/test_case_data/sandbox/kylin.properties
> minor,update pre-defined name/pwd comment

- README.md
[KYLIN-4627] Add the document about try kylin with docker to help users to try kylin easily
- [x ] I have create an issue on [Kylin's jira](https://issues.apache.org/jira/browse/KYLIN), and have described the bug/feature there in detail
> [KYLIN-4627] Add the document about try kylin with docker to help users to try kylin easily

- kylin-it/pom.xml
> KYLIN-4633 Fix CI

- source-hive/src/main/java/org/apache/kylin/source/hive/BeelineHiveClient.java
- source-hive/src/main/java/org/apache/kylin/source/hive/CLIHiveClient.java
> KYLIN-4526 Enhance get the hive table rows

- build/conf/kylin-parquet-log4j.properties
- build/conf/kylin-server-log4j.properties
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkExecutable.java
- kylin-spark-project/kylin-spark-engine/src/test/java/org/apache/kylin/engine/spark/job/NSparkExecutableTest.java
> KYLIN-4621 Avoid annoying log message when build cube and query

- core-job/src/main/java/org/apache/kylin/job/execution/AbstractExecutable.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkUHCDictionary.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkMergingJob.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/merger/AfterMergeOrRefreshResourceMerger.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/ResourceDetectBeforeMergingJob.java
- kylin-spark-project/kylin-spark-engine/src/test/java/org/apache/kylin/engine/spark/source/CsvSourceTest.java
Fix NoClassDefFoundError in merge job step3
> KYLIN-4646 kylin on parquet:  Merge job error

- external/shaded-guava/pom.xml
- jdbc/pom.xml
> KYLIN-4656 Guava classpath conflict caused by kylin-jdbc 3.1.0 jar

- build/bin/kylin.sh
- build/script/prepare-libs.sh
> KYLIN-4660 fix package.sh

- .github/workflows/maven.yml
- core-metrics/src/main/java/org/apache/kylin/metrics/lib/impl/BlockingReservoir.java
- server/src/main/resources/kylinMetrics.xml
> KYLIN-4653 Make the capacity for the LinkedBlockingQueue

- .travis.yml
> Fix travis ci job log exceeded maximum log length

- webapp/app/js/controllers/sourceMeta.js
> KYLIN-4684 Fix web ui bug when create streamig table

- server-base/src/main/java/org/apache/kylin/rest/job/StorageCleanupJob.java
> KYLIN-4678 continue execute job  when clean job sub step has error

- server-base/src/main/java/org/apache/kylin/rest/job/StorageCleanupJob.java
>  KYLIN-4677 storagecleanupjob throw NPE

- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/MapReduceExecutable.java
> KYLIN-4657 dead-loop in org.apache.kylin.engine.mr.common.MapReduceExecutable.doWork

- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkBatchCubingJobBuilder2.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkExecutable.java
> KYLIN-4665 set flink job name shown in resource manager

- query/src/main/java/org/apache/kylin/query/routing/RealizationChooser.java
bug fix of KYLIN-4634, add model force choosing logic.
> KYLIN-4634 Fail to specify cube in model of low priority to query

- core-job/src/main/java/org/apache/kylin/job/common/PatternedLogger.java
- engine-flink/src/main/java/org/apache/kylin/engine/flink/FlinkExecutable.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutableLivy.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/CubeHFileJob.java
> KYLIN-4640 StepInfo saved wrong key about flink or spark

- server-base/src/main/java/org/apache/kylin/rest/job/MetadataCleanupJob.java
- server-base/src/test/java/org/apache/kylin/rest/job/MetadataCleanupJobTest.java
- tool/src/main/java/org/apache/kylin/tool/MetadataCleanupJob.java
> KYLIN-4686 clean metadata support to delete all jobs

- build/bin/clean-kylin-dirty-data.sh
> KYLIN-4687 add unify clean sh to excute some clean shells

- query/src/main/java/org/apache/kylin/query/util/QueryUtil.java
> KYLIN-4685 return user friendly msg when stackoverflowerror

- kylin-spark-project/kylin-spark-engine/src/test/java/org/apache/kylin/engine/spark/job/SparkCubingJobTest.java
- kylin-spark-project/kylin-spark-engine/src/test/resources/log4j.properties
- kylin-spark-project/kylin-spark-test/src/test/java/org/apache/kylin/engine/spark2/NManualBuildAndQueryCuboidTest.java
> KYLIN-4680 Avoid annoying log messages of unit test and integration test

- core-metadata/src/main/java/org/apache/kylin/metadata/MetadataConstants.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkCubingJob.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkCubingStep.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkExecutable.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkMergingJob.java
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/ResultPlan.scala
- tool/src/main/java/org/apache/kylin/tool/metrics/systemcube/CubeDescCreator.java
> KYLIN-4516 support System cube

- build/bin/clean-kylin-dirty-data.sh
> KYLIN-4687 addendum - add apache license header

- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/KylinFileSourceScanExec.scala
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/datasource/ResetShufflePartition.scala
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/hive/utils/QueryMetricUtils.scala
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/application/SparkApplication.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeBuildJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeMergeJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/utils/JobMetricsUtils.scala
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/utils/Repartitioner.java
- kylin-spark-project/kylin-spark-engine/src/test/java/org/apache/kylin/engine/spark/LocalWithSparkSessionTest.java
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/pushdown/SparkSqlClient.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/SparkEngine.java
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/ResultPlan.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContext.scala
- kylin-spark-project/kylin-spark-query/src/test/java/org/apache/kylin/query/pushdown/PushDownRunnerSparkImplTest.java
- kylin-spark-project/kylin-spark-test/src/test/java/org/apache/kylin/engine/spark2/NManualBuildAndQueryCuboidTest.java
- pom.xml
- query/src/main/java/org/apache/kylin/query/relnode/OLAPToEnumerableConverter.java
- query/src/test/resources/log4j.properties
> KYLIN-4662 Migrate from third-party Spark to offical Apache Spark

- website/_dev/howto_docs.cn.md
- website/_dev/howto_docs.md
> update how to doc

- webapp/app/js/controllers/cubeAdvanceSetting.js
> KYLIN-4700 Wrong engine type for realtime streaming

- website/_docs/tutorial/query_pushdown.cn.md
- website/_docs/tutorial/query_pushdown.md
> Optimize pushdown document

- core-common/src/main/java/org/apache/kylin/common/KylinConfig.java
- core-cube/src/main/java/org/apache/kylin/gridtable/GTAggregateTransformScanner.java
- core-cube/src/main/java/org/apache/kylin/gridtable/benchmark/SortedGTRecordGenerator.java
- core-dictionary/src/main/java/org/apache/kylin/dict/DictionaryGenerator.java
- core-metadata/src/main/java/org/apache/kylin/measure/MeasureType.java
- core-metadata/src/main/java/org/apache/kylin/measure/basic/BasicMeasureType.java
- core-metadata/src/main/java/org/apache/kylin/measure/bitmap/BitmapMeasureType.java
- core-metadata/src/main/java/org/apache/kylin/measure/bitmap/RetentionPartialResult.java
- core-metadata/src/main/java/org/apache/kylin/measure/dim/DimCountDistinctMeasureType.java
- core-metadata/src/main/java/org/apache/kylin/measure/hllc/HLLCMeasureType.java
- core-metadata/src/main/java/org/apache/kylin/measure/map/bitmap/BitmapMapMeasureType.java
- core-metadata/src/main/java/org/apache/kylin/measure/raw/RawMeasureType.java
- core-metadata/src/main/java/org/apache/kylin/measure/topn/TopNMeasureType.java
- core-metadata/src/main/java/org/apache/kylin/metadata/cachesync/Broadcaster.java
- core-metadata/src/test/java/org/apache/kylin/metadata/cachesync/BroadcasterTest.java
- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/adaptor/DefaultAdaptor.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/CubingJob.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/CubeStatsReader.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/streaming/RowRecordReader.java
- server-base/src/main/java/org/apache/kylin/rest/request/SQLRequest.java
- tool/src/main/java/org/apache/kylin/tool/extractor/MrJobInfoExtractor.java
fix several sonar reported bugs or issues: https://sonarcloud.io/project/issues?id=org.apache.kylin%3Akylin&resolved=false&severities=BLOCKER&types=BUG
> minor, fix sonar reported bugs

- website/_data/development.yml
- website/_dev/about_temp_files.cn.md
- website/_dev/about_temp_files.md
- website/_dev/coding_naming_convention.cn.md
- website/_dev/coding_naming_convention.md
- website/_dev/datasource_sdk.cn.md
- website/_dev/datasource_sdk.md
- website/_dev/dev_env.cn.md
- website/_dev/doc_spec.cn.md
- website/_dev/doc_spec.md
- website/_dev/howto_become_apache_committer.cn.md
- website/_dev/howto_contribute.cn.md
- website/_dev/howto_contribute.md
- website/_dev/howto_hbase_branches.cn.md
- website/_dev/howto_release.cn.md
- website/_dev/howto_release.md
- website/_dev/howto_test.cn.md
- website/_dev/index.cn.md
- website/_dev/index.md
- website/_dev/new_metadata.cn.md
- website/_dev/new_metadata.md
- website/_dev/web_tech.cn.md
- website/_dev/web_tech.md
> Improve Development part in the website

- kylin-spark-project/kylin-spark-test/src/test/java/org/apache/kylin/engine/spark2/NExecAndComp.java
> KYLIN-4660 Add comparison with prepared data set

- build/bin/check-migration-acl.sh
- build/bin/kylin.sh
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/java/org/apache/kylin/common/QueryContext.java
- core-common/src/main/java/org/apache/kylin/common/debug/BackdoorToggles.java
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/ResultPlan.scala
- server-base/src/main/java/org/apache/kylin/rest/response/SQLResponse.java
- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
- server-base/src/test/java/org/apache/kylin/rest/response/SQLResponseTest.java
> KYLIN-4713 Support use diff spark schedule pool for diff query

- core-common/src/main/java/org/apache/kylin/common/QueryContext.java
- examples/test_case_data/sample_local/table/DEFAULT.KYLIN_ACCOUNT.json
- examples/test_case_data/sample_local/table/DEFAULT.KYLIN_CAL_DT.json
- examples/test_case_data/sample_local/table/DEFAULT.KYLIN_CATEGORY_GROUPINGS.json
- examples/test_case_data/sample_local/table/DEFAULT.KYLIN_COUNTRY.json
- examples/test_case_data/sample_local/table/DEFAULT.KYLIN_SALES.json
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/hive/utils/QueryMetricUtils.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/pushdown/SparkSqlClient.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/ResultPlan.scala
- server-base/src/main/java/org/apache/kylin/rest/response/SQLResponse.java
- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
> KYLIN-4722 && KYLIN-4721

- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeBuildJob.java
> KYLIN-4723 Set the configurations about shard by to cube level

- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/datasource/FilePruner.scala
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/hive/utils/QueryMetricUtils.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/pushdown/SparkSqlClient.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/SparkEngine.java
- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
- server-base/src/test/java/org/apache/kylin/rest/response/SQLResponseTest.java
> KYLIN-4730 Add scan bytes metric to the query results

- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/utils/BuildUtils.scala
- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
- server-base/src/main/java/org/apache/kylin/rest/response/StorageResponse.java
- server-base/src/main/java/org/apache/kylin/rest/service/CubeService.java
- server-base/src/main/java/org/apache/kylin/rest/service/HBaseInfoUtil.java
- webapp/app/js/controllers/cube.js
- webapp/app/js/controllers/cubes.js
- webapp/app/js/filters/filter.js
- webapp/app/js/services/cubes.js
- webapp/app/partials/cubes/cube_detail.html
> KYLIN-4732 & KYLIN-4733 Fix the wrong size of cube

- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- kylin-spark-project/kylin-spark-engine/src/test/java/org/apache/kylin/engine/spark/job/SparkCubingJobTest.java
- kylin-spark-project/kylin-spark-test/src/test/java/org/apache/kylin/engine/spark2/NBuildAndQueryTest.java
> HOTFIX Fix test cases for merging segments

- core-storage/src/main/java/org/apache/kylin/storage/gtrecord/CubeTupleConverter.java
Please see the detailed info: [KYLIN-4731](https://issues.apache.org/jira/projects/KYLIN/issues/KYLIN-4731)  
If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by explaining why you chose the solution …
> KYLIN-4731 Kylin query failing with 'NPE while executing SQL'

- core-common/src/main/java/org/apache/kylin/common/util/HadoopUtil.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/CubeHFileJob.java
> KYLIN-4688 Too many tmp files in HDFS tmp dictionary

- core-job/src/main/java/org/apache/kylin/job/execution/AbstractExecutable.java
> KYLIN-4725 NSparkCubingStep returns error state when pause build job

- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkExecutable.java
> KYLIN-4744 Add tracking URL for build spark job on yarn and optimize step output

- build/conf/kylin-parquet-log4j.properties
- build/conf/kylin-server-log4j.properties
- core-common/src/main/java/org/apache/kylin/common/QueryContext.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/utils/BuildUtils.scala
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/utils/Repartitioner.java
- kylin-spark-project/kylin-spark-engine/src/test/scala/org/apache/kylin/engine/spark/job/TestCubeBuildJob.scala
- kylin-spark-project/kylin-spark-query/pom.xml
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContext.scala
- kylin-spark-project/kylin-spark-test/pom.xml
- pom.xml
- server-base/src/main/java/org/apache/kylin/rest/service/BadQueryDetector.java
- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
- webapp/app/partials/admin/admin.html
> KYLIN-4660 Cleanup

- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeBuildJob.java
> KYLIN-4746 Improve build performance by reducing the count of calling 'count()' function

- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkCubingUtil.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeBuildJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeMergeJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/utils/Repartitioner.java
> KYLIN-4747 Use the first dimension column as sort column within a partiton

- webapp/app/js/controllers/admin.js
- webapp/app/js/services/admin.js
> KYLIN-4705 Monitor Spark's AppMaster for QueryServer - Part II

- core-common/src/main/resources/kylin-defaults.properties
- server/src/test/java/org/apache/kylin/rest/service/AdminServiceTest.java
> KYLIN-4719 Refine kylin-defaults.properties for parquet Storage

- webapp/app/js/model/projectConfig.js
- webapp/app/partials/projects/projects.html
> KYLIN-4716 Optimize the project page

- .travis.yml
> Just Verify If TravisCI passed

- core-dictionary/pom.xml
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/application/SparkApplication.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkCubingStep.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeBuildJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/utils/Repartitioner.java
- kylin-spark-project/kylin-spark-engine/src/test/java/org/apache/kylin/engine/spark/source/CsvSourceTest.java
- kylin-spark-project/kylin-spark-test/pom.xml
- pom.xml
> KYLIN-4660 Add parameter 'skipRunIt' for maven to support running 'Integration Test'

- core-metadata/src/main/java/org/apache/kylin/measure/topn/Counter.java
- core-metadata/src/main/java/org/apache/kylin/measure/topn/TopNCounter.java
- core-metadata/src/main/java/org/apache/kylin/measure/topn/TopNMeasureType.java
- core-metadata/src/test/java/org/apache/kylin/measure/topn/TopNCounterBasicTest.java
- kylin-it/src/test/resources/query/sql_topn/query45.sql
- kylin-it/src/test/resources/query/sql_topn/query81.sql
- kylin-spark-project/kylin-spark-engine/src/test/scala/org/apache/kylin/engine/spark/job/TestTopNUDAF.scala
> KYLIN-4751 Fix NPE issue when run test case TestTopNUDAF

- README.md
- docker/README.md
- docker/run_container.sh
Update the documentation to specify a given container name for `docker run/exec` commands
> Update the documentation to specify a given container name for docker run/exec commands

- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/AbstractHadoopJob.java
Delete duplicate code in AbstractHadoopJob.java that add project resource twice.
> Delete duplicate code in AbstractHadoopJob

- server-base/src/main/java/org/apache/kylin/rest/service/CubeService.java
- [x ] Bugfix (non-breaking change which fixes an issue)
> KYLIN-4753 Merging job stop working after Kylin upgrade

- webapp/app/js/controllers/userGroup.js
- [ x Commit messages in my PR start with the related jira ID, like "KYLIN-0000 Make Kylin project open-source"
If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by explaining why you chose the solution …
> KYLIN-4756 user/group page has duplicate information between adjacent page numbers

- core-common/src/main/java/org/apache/kylin/common/util/HiveCmdBuilder.java
- server-base/src/main/java/org/apache/kylin/rest/job/StorageCleanupJob.java
- source-hive/src/main/java/org/apache/kylin/source/hive/BeelineHiveClient.java
> KYLIN-4679 StorageCleanupJob clean hive table support hive table prefix

- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/udaf/NullSafeValueSerializer.scala
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/udaf/TopN.scala
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CuboidAggregator.scala
> KYLIN-4760 Optimize TopN measure

- server-base/src/main/java/org/apache/kylin/rest/service/AclService.java
- server/src/test/java/org/apache/kylin/rest/controller/AccessControllerTest.java
- server/src/test/java/org/apache/kylin/rest/service/AccessServiceTest.java
> KYLIN-4714 Failed to revoke role access of the project

- stream-source-kafka/src/main/java/org/apache/kylin/stream/source/kafka/consumer/KafkaConnector.java
JIRA：https://issues.apache.org/jira/browse/KYLIN-4683
> KYLIN-4683 Fail to consume kafka when partition number get larger

- tool/src/main/java/org/apache/kylin/tool/CubeMetaIngester.java
> KYLIN-4712 Optimize Optimize CubeMetaIngester.java CLI

- build/bin/download-spark.sh
- pom.xml
> Upgrade spark and spring version

- build/bin/diag.sh
- build/bin/set-java-home.sh
> KYLIN-4759 Remove hbase command from scripts in build directory

- kylin-spark-project/kylin-spark-engine/src/test/java/org/apache/kylin/engine/spark/LocalWithSparkSessionTest.java
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContext.scala
- kylin-spark-project/kylin-spark-test/src/test/java/org/apache/kylin/engine/spark2/NManualBuildAndQueryCuboidTest.java
- webapp/app/js/controllers/admin.js
(cherry picked from commit 24822baa27c342a4486491157be8d8619472a631)
If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by explaining why you chose the solution you did and what alternatives you …
> KYLIN-4764 Throws NoClassDefFoundError when run query test cases

- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/datasource/FilePruner.scala
(cherry picked from commit 109598539dd22bc17a218de03e3125a90fda43f1)
If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by explaining why you chose the solution you did and what alternatives you …
> KYLIN-4660 Remove some unused code from FilePruner.scala

- core-metadata/src/main/java/org/apache/kylin/metadata/model/ISourceAware.java
- kylin-spark-project/kylin-spark-metadata/src/main/java/org/apache/kylin/engine/spark/metadata/cube/source/SourceFactory.java
- server-base/src/main/java/org/apache/kylin/rest/service/JobService.java
- server-base/src/main/java/org/apache/kylin/rest/service/TableService.java
(cherry picked from commit 82d770745f5bd85cf1333abf6cc7c14380726c18)
If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by explaining why you chose the solution you did and what alternatives you …
> KYLIN-4763 Rename ISourceAware.ID_SPARK to ISourceAware.ID_CSV

- source-jdbc/src/main/java/org/apache/kylin/source/jdbc/extensible/JdbcExplorer.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/coordinate/BuildJobSubmitter.java
> KYLIN-4689 Fix inconsistent global lock 

- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/application/SparkApplication.java
- kylin-spark-project/kylin-spark-engine/src/test/java/org/apache/kylin/engine/spark/LocalWithSparkSessionTest.java
> KYLIN-4765 Set spark.sql.shuffle.partition to 1 for debug on local

- core-metadata/src/main/java/org/apache/kylin/metadata/model/DataModelManager.java
- tool/src/main/java/org/apache/kylin/tool/CubeMetaIngester.java
> KYLIN-4712 Fix some bugs when ingest cube

- core-metadata/src/main/java/org/apache/kylin/metadata/model/DataModelManager.java
- tool/src/main/java/org/apache/kylin/tool/CubeMetaIngester.java
> KYLIN-4712 Fix bug when ingest cube

- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkCubingJob.java
- server-base/src/main/java/org/apache/kylin/rest/service/JobService.java
> KYLIN-4766 Delete job tmp and segment file after job be discarded

- server-base/src/main/java/org/apache/kylin/rest/controller/UserController.java
- server-base/src/main/java/org/apache/kylin/rest/security/KylinAuthenticationProvider.java
- server-base/src/main/java/org/apache/kylin/rest/security/KylinUserManager.java
- server-base/src/main/java/org/apache/kylin/rest/service/KylinUserGroupService.java
- server-base/src/main/java/org/apache/kylin/rest/service/KylinUserService.java
- server-base/src/main/java/org/apache/kylin/rest/service/UserService.java
- [x ] Bugfix (non-breaking change which fixes an issue)
- [x ] I have create an issue on [Kylin's jira](https://issues.apache.org/jira/browse/KYLIN), and have described the bug/feature there in detail
If this is a relatively large or complex change, …
> KYLIN-4697: Fix User info update logic use copyForWrite

- webapp/app/partials/cubes/cubes.html
Grammar fix on message when there are no cubes.
> Correct grammar of message when there are no cubes

- build/smoke-test/testBuildCube.py
- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
> KYLIN-4581 Modify the REST API url of update cube build engine

- build/bin/kylin.sh
- kubernetes/docker/kylin-client/Dockerfile
- kubernetes/docker/kylin-client/bin/bootstrap.sh
JIRA: https://issues.apache.org/jira/browse/KYLIN-4770
> KYLIN-4770: Move Kylin service on k8s from background to foreground

- external/shaded-guava/pom.xml
> HOTFIX modify the version of shaded-guava module to 3.1.2-SNAPSHOT

- website/_data/docs-cn.yml
- website/_data/docs.yml
- website/_docs/tutorial/real_time_olap.md
> Add some missing tutorial

- build/bin/sample.sh
- build/smoke-test/testBuildCube.py
> Auto add USE $DATABASE; to the beginning of create_sample_tables.sql

- server/src/main/resources/kylinSecurity.xml
> KYLIN-4636 Make /api/admin/public_config callable for profile saml

- website/_docs/howto/howto_use_cli.cn.md
- website/_docs/howto/howto_use_cli.md
> Kylin-4712 Update document

- website/_data/contributors.yml
- website/_docs/release_notes.md
- website/download/index.cn.md
- website/download/index.md
> Prepare release for Kylin 3.1.1

- build/bin/kylin.sh
> KYLIN-4790 Automaticly copy required jars to SPARK_HOME/jars for HDI3.6

- kylin-it/src/test/resources/query/sql_castprunesegs/query01.sql
- kylin-it/src/test/resources/query/sql_castprunesegs/query02.sql
- kylin-it/src/test/resources/query/sql_castprunesegs/query03.sql
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/datasource/FilePruner.scala
- kylin-spark-project/kylin-spark-test/src/test/java/org/apache/kylin/engine/spark2/NBuildAndQueryTest.java
When execute function 'pruneSegments' of FilePruner, if there are some cast expressions in filter, it will throw exception 'UnsupportedOperationException: empty.reduceLeft'.
Solution:
Convert cast expressions in filter to attribute before translating filter.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …
> KYLIN-4791 Fix exception 'UnsupportedOperationException: empty.reduceLeft' when there are cast expressions in the filters of FilePruner

- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeBuildJob.java
- kylin-spark-project/kylin-spark-test/src/test/java/org/apache/kylin/engine/spark2/NBuildAndQueryTest.java
> KYLIN-4797 Correct inputRecordSizes of segment when there is no data in this segment

- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/datasource/FilePruner.scala
Optimize join where there is the same shardby partition num on join key.
Part I ：
Implement on kylin side
> KYLIN-4762 Optimize join where there is the same shardby partition num on join key -- Part I Implement on kylin side

- CONTRIBUTING.md
There are documents for developers on the website. Placing CONTRIBUTING.md in the root of the GitHub repository is defacto-standard but this project doesn't. I create a `CONTRIBUTING.md` file and make it refer to documents on the official website of Kylin. I expect this makes other developers easy to access to development guide.
I make this PR to the `master` branch because the `CONTRIBUTING.md` file should be located in root dir in this repository. I understand the `document` branch only takes documents for the website. If I understand wrong, please let me know.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …
> KYLIN-4799 Create CONTRIBUTING.md

- build/bin/find-hadoop-conf-dir.sh
> KYLIN-4808 Auto copy hive-site.xml to hadoop_conf_dir in kylin4

- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkExecutable.java
> KYLIN-4811 Support cube level configuration for BuildingJob

- website/_docs/tutorial/setup_systemcube.cn.md
- website/_docs/tutorial/setup_systemcube.md
> update system cube

- website/_data/contributors.yml
- website/_docs/security.md
> add new committer chuxiao and new cve

- build/bin/find-hadoop-conf-dir.sh
- docker/docker-compose/others/client-write-read.env
- docker/docker-compose/others/client-write.env
- docker/docker-compose/others/docker-compose-kerberos.yml
- docker/docker-compose/others/docker-compose-kylin-write-read.yml
- docker/docker-compose/others/docker-compose-kylin-write.yml
- docker/docker-compose/others/docker-compose-metastore.yml
- docker/docker-compose/read/docker-compose-hadoop.yml
- docker/docker-compose/read/docker-compose-hbase.yml
- docker/docker-compose/read/docker-compose-zookeeper.yml
- docker/docker-compose/read/read-hadoop.env
- docker/docker-compose/read/read-hbase-distributed-local.env
- docker/docker-compose/write/docker-compose-hadoop.yml
- docker/docker-compose/write/docker-compose-hbase.yml
- docker/docker-compose/write/docker-compose-hive.yml
- docker/docker-compose/write/docker-compose-kafka.yml
- docker/docker-compose/write/docker-compose-zookeeper.yml
- docker/docker-compose/write/write-hadoop.env
- docker/docker-compose/write/write-hbase-distributed-local.env
- docker/dockerfile/cluster/client/entrypoint.sh
- docker/dockerfile/cluster/client/run_cli.sh
- docker/dockerfile/cluster/hmaster/Dockerfile
- docker/dockerfile/cluster/hregionserver/Dockerfile
- docker/dockerfile/cluster/kylin/entrypoint.sh
- docker/dockerfile/cluster/metastore-db/Dockerfile
- docker/dockerfile/cluster/metastore-db/run_db.sh
- pom.xml
> KYLIN-4775 Add license for some file and some fix

- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/hive/utils/QueryMetricUtils.scala
> KYLIN-4822 The metrics 'Total spark scan time' of query log is negative in some cases

- kubernetes/template/production/deployment/kylin/kylin-job-statefulset.yaml
- kubernetes/template/production/deployment/kylin/kylin-query-statefulset.yaml
- kubernetes/template/production/deployment/streaming/kylin-receiver-statefulset.yaml
- kubernetes/template/production/example/deployment/kylin-job/kylin-job-statefulset.yaml
- kubernetes/template/production/example/deployment/kylin-query/kylin-query-statefulset.yaml
- kubernetes/template/quickstart/deployment/kylin/kylin-all-statefulset.yaml
JIRA: https://issues.apache.org/jira/browse/KYLIN-4807
> KYLIN-4807 Add liveness and readiness probe to k8s deployment

- core-dictionary/src/main/java/org/apache/kylin/dict/TrieDictionaryBuilder.java
- core-dictionary/src/test/java/org/apache/kylin/dict/TrieDictionaryTest.java
> KYLIN-4810 fix

- website/_data/contributors.yml
> add new committer xvyiming

- website/_docs/install/index.cn.md
- website/_docs/install/index.md
> [Document] Add solution of guava conflict error when start kylin

- website/_docs/tutorial/cube_migration.cn.md
- website/_docs/tutorial/cube_migration.md
> Update cubeMigrationCLI document

- kylin-spark-project/kylin-spark-common/pom.xml
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/datasource/ResetShufflePartition.scala
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/utils/SparderUtils.scala
- kylin-spark-project/kylin-spark-engine/pom.xml
- kylin-spark-project/kylin-spark-query/pom.xml
- kylin-spark-project/kylin-spark-query/src/main/java/org/apache/kylin/query/monitor/SparderContextCanary.java
- kylin-spark-project/kylin-spark-query/src/main/java/org/apache/kylin/query/pushdown/SparkSubmitter.java
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/UdfManager.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/pushdown/SparkSqlClient.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/ResultPlan.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/KylinSession.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContext.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContextFacade.scala
- kylin-spark-project/kylin-spark-query/src/test/java/org/apache/kylin/query/monitor/SparderContextCanaryTest.java
- kylin-spark-project/kylin-spark-query/src/test/java/org/apache/spark/sql/SparderContextFacadeTest.java
- kylin-spark-project/kylin-spark-test/pom.xml
> KYLIN-4829 Support to use thread-level SparkSession to execute query

- source-hive/src/main/java/org/apache/kylin/source/hive/BeelineHiveClient.java
> KYLIN-4838  fix KYLIN-4679 bug

- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkCubingByLayer.java
> KYLIN-4841 Spark RDD cache is invalid when building with spark engine

- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkCubingByLayer.java
> KYLIN-4841 Spark RDD cache is invalid when building with spark engine (For Kylin 2.6.x)

- storage-hbase/pom.xml
> Remove redundant code

- website/_docs/gettingstarted/faq.cn.md
- website/_docs/gettingstarted/faq.md
- website/_docs/install/configuration.cn.md
- website/_docs/install/configuration.md
- website/_docs/tutorial/sql_reference.cn.md
- website/_docs/tutorial/sql_reference.md
- website/_includes/header.cn.html
- website/_includes/header.html
- website/_includes/home_header.cn.html
- website/_includes/home_header.html
> Update some document

- website/_docs/gettingstarted/faq.cn.md
- website/_docs/gettingstarted/faq.md
- website/_docs/howto/howto_use_restapi.cn.md
- website/_docs/howto/howto_use_restapi.md
> Update specify cube for query

- tool/src/main/java/org/apache/kylin/tool/CubeMigrationCLI.java
> KYLIN-4837 optimize CubeMigrationCLI

- tool/src/main/java/org/apache/kylin/tool/CubeMigrationCLI.java
> KYLIN-4836 fix CubeMigrationCLI bug

- kylin-it/src/test/resources/query/sql_grouping/query03.sql
- kylin-it/src/test/resources/query/sql_grouping/query04.sql
- kylin-it/src/test/resources/query/sql_grouping/query05.sql
- kylin-it/src/test/resources/query/sql_grouping/query06.sql
- kylin-it/src/test/resources/query/sql_grouping/query07.sql
- kylin-it/src/test/resources/query/sql_grouping/query08.sql
- kylin-it/src/test/resources/query/sql_grouping/query09.sql
- kylin-spark-project/kylin-spark-common/src/test/java/org/apache/spark/sql/common/SparkQueryTest.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/AggregatePlan.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/ValuesPlan.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparkOperation.scala
- kylin-spark-project/kylin-spark-test/src/test/java/org/apache/kylin/engine/spark2/NBuildAndQueryTest.java
> KYLIN-4842 Supports grouping sets function for Kylin 4

- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/builder/CubeSnapshotBuilder.scala
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/ParentSourceChooser.scala
> KYLIN-4818 Check lookup table duplicate key when building job

- tool/src/main/java/org/apache/kylin/tool/CubeMigrationCLI.java
snapshot can be reused when doing cube migration.
> [KYLIN-4702] Correct cube-level snapshot path when the related

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
> update kylin.metric.subject-suffix to kylin.metrics.subject-suffix

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContext.scala
- kylin-spark-project/kylin-spark-query/src/test/java/org/apache/spark/sql/SparderAppNameTest.java
> KYLIN-4741 Support to config the sparder application name

- kylin-spark-project/kylin-spark-query/src/main/java/org/apache/kylin/query/pushdown/SparkSubmitter.java
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/pushdown/SparkSqlClient.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/ResultPlan.scala
> KYLIN-4846 Set the related query id to sparder job description

- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkMergingDictionary.java
> [KYLIN-4827] Fix SparkMergingDictionary parallelize not work.

- pom.xml
revert a change on master branch yesterday by mistake when I made another change
> revert hadoop version change to recover UT

- query/src/main/java/org/apache/kylin/query/relnode/OLAPWindowRel.java
- query/src/main/java/org/apache/kylin/query/relnode/visitor/TupleExpressionVisitor.java
> KYLIN-4658 Fix union all issue with regarding to windows function & aggregation on

- core-common/src/main/java/org/apache/kylin/common/util/ClassUtil.java
> KYLIN-4847 Cuboid to HFile step failed on multiple job server env

- build/bin/find-hive-dependency.sh
- build/bin/kylin.sh
- build/bin/replace-jars-under-spark.sh
> KYLIN-4858 Support Kylin4 deployment on CDH 6.X

- server-base/src/main/java/org/apache/kylin/rest/service/QueryService.java
> KYLIN-4853 QueryPreparedStatementCache invalid in Spark Query Engine.

- build/conf/kylin-server-log4j.properties
> KYLIN-4859 Log4J reinitialized/reconfigured by Spark Logging

- core-common/src/main/java/org/apache/kylin/common/persistence/ResourceStore.java
- core-cube/src/main/java/org/apache/kylin/cube/CubeSegment.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/utils/UpdateMetadataUtil.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeBuildJob.java
- metastore-hbase/src/main/java/org/apache/kylin/storage/hbase/HBaseResourceStore.java
> KYLIN-4818 Not store HLL binary file into RDBMS directly

- website/download/index.cn.md
- website/download/index.md
> Update v4.0.0-alpha download info

- build-engine/src/main/java/org/apache/kylin/engine/mr/common/CubeStatsReader.java
- webapp/app/js/controllers/cube.js
> KYLIN-4872 Fix NPE when there are more than one segment if cube planner is open

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- tool/src/main/java/org/apache/kylin/tool/CubeMigrationCLI.java
> KYLIn-4874 Fix CubeMigrationCLI bug for kylin4

- build/conf/spark-driver-log4j.properties
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- kylin-spark-project/kylin-spark-common/src/main/java/org/apache/kylin/engine/spark/common/logging/AbstractHdfsLogAppender.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NResourceDetectStep.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkExecutable.java
> KYLIN-4875 Remove executor configurations when execute resource detect step (local mode)

- build/bin/replace-jars-under-spark.sh
> Minor, fix replace-jars-under-spark.sh

- server-base/src/main/java/org/apache/kylin/rest/job/StorageCleanupJob.java
- server-base/src/test/java/org/apache/kylin/rest/job/StorageCleanupJobTest.java
> Fix storage clean up tool

- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkBatchCubingJobBuilder2.java
> KYLIN-4882 config["kylin.engine.spark-fact-distinct"] overwrite in the Cube-level is invalid

- build/bin/find-hadoop-conf-dir.sh
- metrics-reporter-hive/src/main/java/org/apache/kylin/metrics/lib/impl/hive/HiveProducer.java
> HOTFIX Fix the issue of closing FileSystem

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/HFileDistcpJob.java
> Minor, JobContext.JOB_NAME will cause compile error in cdh57 profile

- pom.xml
> Update version of shade-guava

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- stream-core/src/main/java/org/apache/kylin/stream/core/query/MultiThreadsResultCollector.java
> Minor, unify thread capacity for scannerThreadPool

- external/pom.xml
- pom.xml
> Fix maven-release-plugin.

- website/_data/contributors.yml
> Add new committer yaqian

- pom.xml
> Reset version for shaded-guava

- website/_docs/release_notes.md
- website/download/index.cn.md
- website/download/index.md
> Update download and release info for kylin4.0.0-beta

- website/download/index.cn.md
- website/download/index.md
> minor fix for 4.0.0-beta release

- kylin-spark-project/kylin-spark-query/src/main/java/org/apache/kylin/query/monitor/SparderContextCanary.java
> KYLIN-4890 Use numSlices = 1 to reduce task num when executing sparder canary

- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/HBaseResourceStore.java
> KYLIN-4896 Optimize the process of writing big resource files into HDFS.

- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/CalciteToSparkPlaner.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/SparkEngine.java
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/UnionPlan.scala
- query/src/main/java/org/apache/kylin/query/exec/SparkExec.java
> KYLIN-4888, Performance optimization of union query with spark engine

- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/datasource/FilePruner.scala
> KYLIN-4887 Segment pruner support string type partition col in spark query engine

- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/KylinSession.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContext.scala
> KYLIN-4889

- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/datasource/FilePruner.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContext.scala
- kylin-spark-project/kylin-spark-test/src/test/java/org/apache/kylin/engine/spark2/NBadQueryAndPushDownTest.java
> KYLIN-4892 Reduce the times of fetching files status from HDFS Namenode in FilePruner

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/datasource/FilePruner.scala
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/datasource/ResetShufflePartition.scala
> KYLIN-4893 Optimize query performance when using shard by column

- docker/dockerfile/standalone/Dockerfile_hadoop
> HOTFIX Add missing docker file: Dockerfile_hadoop

- kylin-spark-project/kylin-spark-common/src/main/java/org/apache/kylin/engine/spark/common/logging/AbstractHdfsLogAppender.java
- kylin-spark-project/kylin-spark-common/src/main/java/org/apache/kylin/engine/spark/common/logging/SparkExecutorHdfsAppender.java
- server-base/src/main/java/org/apache/kylin/rest/job/StorageCleanupJob.java
> KYLIN-4917 Fix some problem of logger system in kylin4

- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContext.scala
> KYLIN-4910 Return hostname as Sparder URL address when spark master is set to local

- core-storage/src/main/java/org/apache/kylin/storage/gtrecord/CubeTupleConverter.java
- stream-core/src/main/java/org/apache/kylin/stream/core/query/StreamingTupleConverter.java
- stream-source-kafka/src/main/java/org/apache/kylin/stream/source/kafka/TimedJsonStreamParser.java
fix two issues.
[KYLIN-4900](https://issues.apache.org/jira/browse/KYLIN-4900)
[KYLIN-4901](https://issues.apache.org/jira/browse/KYLIN-4901)
If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by …
> KYLIN-4900 real-time stream doesn't support GMT-N timezone and doesn't convert other time columnexcept derived column above day 

- server-base/src/main/java/org/apache/kylin/rest/controller/StreamingV2Controller.java
when create lambda table in real-time stream, the derived columns are not be checked compatibility with partition columns in hive table.
> [KYLIN-4924] bug fix: check the compatibility for derived column in lambda mode

- website/_docs/tutorial/setup_systemcube.cn.md
- website/_docs/tutorial/setup_systemcube.md
> KYLIN-4854 Fix some errors in system cube document

- pom.xml
- query/pom.xml
- query/src/main/codegen/javacc/org/apache/kylin/query/util/.gitignore
- query/src/main/codegen/javacc/org/apache/kylin/query/util/CommentParser.jj
- query/src/main/java/org/apache/kylin/query/util/QueryUtil.java
- query/src/test/java/org/apache/kylin/query/util/QueryUtilTest.java
> KYLIN-4879 kylin4 - Fix the function of remove sql comments 

- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/dict/NGlobalDictBuilderAssist.scala
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/builder/CubeDictionaryBuilder.scala
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/builder/DictHelper.scala
- kylin-spark-project/kylin-spark-engine/src/test/java/org/apache/kylin/engine/spark/dict/NGlobalDictionaryTest.java
- query/src/main/codegen/javacc/org/apache/kylin/query/util/CommentParser.jj
> KYLIN-4926 Optimize Global Dict building: replace operation 'mapPartitions.count()' with 'foreachPartitions'

- core-job/src/main/java/org/apache/kylin/job/execution/ExecutableManager.java
- pom.xml
> KYLIN-4935 Existing JobOutput's extend info will be lost when it is updated

- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/datasource/FilePruner.scala
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/execution/datasource/ResetShufflePartition.scala
- [] New feature (non-breaking change which adds functionality)
If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by explaining why you chose the solution you did and what alternatives you considered, …
> KYLIN-4918 Support Cube Level configuration in FilePruner

- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
- server-base/src/main/java/org/apache/kylin/rest/msg/Message.java
- server-base/src/main/java/org/apache/kylin/rest/service/CubeService.java
> [KYLIN-4938] remove segment by UUID

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-dictionary/src/main/java/org/apache/kylin/dict/DictionaryManager.java
> KYLIN-4933 Support set cache strength for dict cache

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/BuildLayoutWithUpdate.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeBuildJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeMergeJob.java
> KYLIN-4903 cache parent datasource to accelerate next layer's cuboid building

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/builder/CubeTableEncoder.scala
- kylin-spark-project/kylin-spark-metadata/src/main/scala/org/apache/kylin/engine/spark/metadata/MetaData.scala
- kylin-spark-project/kylin-spark-metadata/src/main/scala/org/apache/kylin/engine/spark/metadata/MetadataConverter.scala
> KYLIN-4945 Repartition encoded dataset to avoid data skew caused by a single column

- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkCubingByLayer.java
> KYLIN-4962 Fix NPE in ShrunkDict step

- build/bin/download-flink.sh
> KYLIN-4979 Fix flink shaded jar version error in download-flink.sh

- .gitignore
- examples/test_case_data/parquet_test/model_desc/ci_left_join_model.json
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/builder/CreateFlatTable.scala
> KYLIN-4965 Fix the 'can not resolve columns' error when create model and add lookup table column as filter condition

- core-job/src/main/java/org/apache/kylin/job/JoinedFormatter.java
- core-metadata/src/main/java/org/apache/kylin/metadata/util/ModelUtil.java
- server-base/src/main/java/org/apache/kylin/rest/service/ModelService.java
- server/src/test/java/org/apache/kylin/rest/service/ModelServiceTest.java
verify filter condition using the following login
1 select * from tableName where {filterCondition} pass   calcite  parse
2 all column in filter condition must be model table column
> [KYLIN-4554] validate filter condition on model saving

- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
- server-base/src/main/java/org/apache/kylin/rest/request/JobOptimizeRequest2.java
> [KYLIN-4948] Provide an API to allow users to adjust cuboids manually

- core-metadata/src/main/java/org/apache/kylin/metadata/model/Segments.java
[issue link](https://issues.apache.org/jira/browse/KYLIN-4978)
> [KYLIN-4978]NPE: refresh segment when there is no segments

- query/src/test/java/org/apache/kylin/query/util/QueryUtilTest.java
> KYLIN-4879 add UT

- docker/Dockerfile_hadoop
- docker/entrypoint.sh
> KYLIN-4944  kylin3 Docker image is upgraded from centos6.9 to centos7.9.2009

- core-common/src/main/java/org/apache/kylin/common/restclient/RestClient.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/ColumnDesc.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/TableDesc.java
- cube-migration/src/main/java/org/apache/kylin/rest/controller/MigrationController.java
- cube-migration/src/main/java/org/apache/kylin/rest/service/MigrationRuleSet.java
- cube-migration/src/main/java/org/apache/kylin/rest/service/MigrationService.java
- server-base/src/main/java/org/apache/kylin/rest/service/BasicService.java
- server-base/src/main/java/org/apache/kylin/rest/service/StreamingV2Service.java
- server-base/src/main/java/org/apache/kylin/rest/service/TableSchemaUpdateChecker.java
- server-base/src/main/java/org/apache/kylin/rest/service/TableService.java
- server/src/main/resources/kylinSecurity.xml
- stream-core/src/main/java/org/apache/kylin/stream/core/source/MessageParserInfo.java
- tool/src/main/java/org/apache/kylin/tool/CubeMigrationCLI.java
- tool/src/main/java/org/apache/kylin/tool/migration/StreamTableCompatibilityCheckRequest.java
[issue](https://issues.apache.org/jira/browse/KYLIN-4931?filter=12350368)
1. don't check the hive table, when real-time stream is not lambda.
2. add check rule for real-time stream: check the table desc and stream source config.
> [KYLIN-4931] real-time stream migration: change the migration rule check

- build/script/build.sh
- webapp/bower.json
>  KYLIN-5003 Remove legacy front end dependencies

- core-metadata/src/main/java/org/apache/kylin/metadata/model/ColumnDesc.java
> Minor fix, remove unused import

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-cube/src/main/java/org/apache/kylin/cube/cuboid/CuboidScheduler.java
- core-cube/src/main/java/org/apache/kylin/cube/cuboid/CuboidUtil.java
- core-cube/src/main/java/org/apache/kylin/cube/cuboid/TreeCuboidScheduler.java
- core-cube/src/main/java/org/apache/kylin/cube/kv/RowKeyDecoder.java
- core-job/src/main/java/org/apache/kylin/job/constant/ExecutableConstants.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/BatchOptimizeJobBuilder2.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/BatchConstants.java
- engine-mr/src/main/java/org/apache/kylin/engine/mr/common/CubeStatsWriter.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/KylinKryoRegistrator.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkBatchCubingEngine2.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkBatchOptimizeJobBuilder2.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkBuildDictionary.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkCalculateStatsFromBaseCuboidJob.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkCubingByLayer.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkCubingByLayerForOpt.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkCubingMerge.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkExecutable.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkFactDistinct.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkFilterRecommendCuboidDataJob.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkFunction.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkMergingDictionary.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkUHCDictionary.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkUpdateShardForOldCuboidDataStep.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkUtil.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/BulkLoadJob.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/CreateHTableJob.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/HBaseSparkOutputTransition.java
- storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/SparkCubeHFile.java
Implement spark engine for cube optimization jobs.
> [KYLIN-4947] Implement spark engine for cube optimization jobs.

- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/builder/CubeSnapshotBuilder.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/SparderLookupManager.scala
JIRA: https://issues.apache.org/jira/browse/KYLIN-5013
> KYLIN-5013 Write table_snapshot to wrong cluster in Kylin4.0

- build/bin/kylin-port-replace-util.sh
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/resources/kylin-defaults.properties
- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- core-metadata/src/main/java/org/apache/kylin/metadata/cachesync/CachedCrudAssist.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/application/SparkApplication.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkExecutable.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/OptimizeBuildJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeBuildJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeMergeJob.java
> KYLIN-5014 fix log and remove unnecessary config server.port

- core-cube/src/main/java/org/apache/kylin/cube/CubeInstance.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/TableDesc.java
- server-base/src/main/java/org/apache/kylin/rest/service/JobService.java
> [KYLIN-4983]add rule for submit build job: forbid submitting appending segment in the lambda stream cube

- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/framework/conv/DefaultConfigurer.java
- datasource-sdk/src/main/java/org/apache/kylin/sdk/datasource/framework/conv/SqlConverter.java
Avoid npe issue in rdbms pushdown
> KYLIN-5016 avoid npe issue in rdbms pushdown

- website/index.cn.md
- website/index.md
> Adjust logo order

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- kylin-spark-project/kylin-spark-metadata/src/main/scala/org/apache/kylin/engine/spark/metadata/MetadataConverter.scala
> KYLIN-5027 Add the config of whether to build base cuboid in kylin4

- build/bin/kylin.sh
- build/conf/stream-receiver-log4j.properties
> [KYLIN-5030]add stream-receiver log configuration to the conf dir

- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/Coordinator.java
- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/coordinate/StreamingCoordinator.java
> [KYLIN-5026]check whether the node is in the existing set before creating the new replicaset

- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/coordinate/BuildJobSubmitter.java
> [KYLIN-5009]When coordinator leader change, clear the cached submitted job info

- kylin-spark-project/kylin-spark-common/pom.xml
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/catalyst/expressions/KylinExpresssions.scala
- kylin-spark-project/kylin-spark-metadata/pom.xml
- parquet-assembly/pom.xml
> HOTFIX Fix some issues for spark3

- server-base/src/main/java/org/apache/kylin/rest/service/JobService.java
> KYLIN-5031 Fix the last_build_job_id of segment is null when the semgent status is RUNNING or ERROR.

- engine-mr/src/main/java/org/apache/kylin/engine/mr/steps/CalculateStatsFromBaseCuboidJob.java
- engine-spark/src/main/java/org/apache/kylin/engine/spark/SparkCalculateStatsFromBaseCuboidJob.java
> [KYLIN-5035] Fix Merge Cuboid Statistics EOFException.

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkExecutable.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/spark/deploy/SparkApplicationClient.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContext.scala
> KYLIN-5023 Some fix for spark standalone

- kylin-it/src/test/resources/query/sql_exactly_agg_multi_segment/query00.sql
- kylin-it/src/test/resources/query/sql_exactly_agg_multi_segment/query01.sql
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/AggregatePlan.scala
- kylin-spark-project/kylin-spark-test/src/test/java/org/apache/kylin/engine/spark2/NBuildAndQueryTest.java
> KYLIN-5040 Add rule for exactly match cuboid

- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
> [KYLIN-5034] forbid creating streaming cube with non-MR engine

- stream-coordinator/src/main/java/org/apache/kylin/stream/coordinator/client/HttpCoordinatorClient.java
> [KYLIN-5020]fix bug: retry the same error url when coordinator leader changes

- website/_data/docs40-cn.yml
- website/_data/docs40.yml
- website/_docs40/install/deploy_without_hadoop.cn.md
- website/_docs40/install/deploy_without_hadoop.md
- website/_docs40/install/index.cn.md
- website/_docs40/install/index.md
> Add deploy_without_hadoop document

- website/_docs40/install/deploy_without_hadoop.cn.md
- website/_docs40/install/deploy_without_hadoop.md
- website/_posts/blog/2021-07-29-kylin-on-parquet-new-architecture-share.cn.md
> Fix cn blog and some typos

- build/bin/kylin.sh
- core-common/src/main/resources/kylin-defaults.properties
- docker/dockerfile/standalone/conf/bin/kylin.sh
- kylin-spark-project/kylin-spark-classloader/src/main/java/org/apache/kylin/spark/classloader/SparkClassLoader.java
- kylin-spark-project/kylin-spark-common/src/main/java/org/apache/kylin/engine/spark/metadata/cube/PathManager.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkExecutable.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/spark/conf/rule/SparkConfRule.scala
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/spark/utils/ResourceUtils.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/KylinSession.scala
- pom.xml
- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
> HOTFIX for spark3

- website/_data/docs40-cn.yml
- website/_data/docs40.yml
- website/_dev40/dev_env.cn.md
- website/_dev40/dev_env.md
- website/_docs/install/index.cn.md
- website/_docs/install/index.md
- website/_docs40/howto/howto_use_cli.cn.md
- website/_docs40/howto/howto_use_cli.md
- website/_docs40/index.cn.md
- website/_docs40/index.md
- website/_docs40/install/index.cn.md
- website/_docs40/install/index.md
> Update howto_use_cli document for docs40

- core-common/src/main/resources/kylin-defaults.properties
- kylin-spark-project/kylin-spark-common/src/main/java/org/apache/kylin/engine/spark/common/logging/SparkExecutorHdfsAppender.java
> HOTFIX fix slf4j jar version conflict

- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/builder/CubeTableEncoder.scala
> KYLIN-5011 Detect and scatter skewed data in dict encoding step

- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/dict/NBucketDictionary.java
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/catalyst/expressions/KylinExpresssions.scala
> KYLIN-5059 Fix error when using different HDFS cluster in cube building

- .github/pull_request_template.md
> Refine PR template

- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/OptimizeBuildJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/BuildLayoutWithUpdate.java
> KYLIN-4903 cache parent datasource to accelerate next layer's cuboid building -- fix bug

- website/_includes/header.cn.html
- website/_includes/header.html
- website/_includes/home_header.cn.html
- website/_includes/home_header.html
- website/assets/css/styles.css
> Minor fix header html

- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/builder/CubeTableEncoder.scala
> KYLIN-5011 HotFix for scatter skew data in dict-encoding step

- build/bin/kylin.sh
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/java/org/apache/kylin/common/QueryContext.java
- core-common/src/main/java/org/apache/kylin/common/annotation/ConfigTag.java
- core-common/src/main/resources/kylin-defaults.properties
- core-dictionary/DEPRECATED_MODULE
- datasource-sdk/DEPRECATED_MODULE
- docker/conf/kylin/kylin.properties
- docker/dockerfile/standalone/conf/bin/kylin.sh
- docker/dockerfile/standalone/conf/kylin/kylin.properties
- engine-flink/DEPRECATED_MODULE
- engine-mr/DEPRECATED_MODULE
- engine-spark/DEPRECATED_MODULE
- examples/sample_cube/template/cube_desc/kylin_sales_cube.json
- examples/test_case_data/file_prunning/kylin.properties
- examples/test_case_data/localmeta/kylin.properties
- examples/test_case_data/parquet_test/kylin.properties
- examples/test_case_data/sandbox/kylin.properties
- kylin-it/DEPRECATED_MODULE
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeBuildJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/utils/JobMetricsUtils.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContext.scala
- source-jdbc/DEPRECATED_MODULE
- source-kafka/DEPRECATED_MODULE
- storage-hbase/DEPRECATED_MODULE
- storage-stream/DEPRECATED_MODULE
- stream-coordinator/DEPRECATED_MODULE
- stream-core/DEPRECATED_MODULE
- stream-receiver/DEPRECATED_MODULE
- stream-source-kafka/DEPRECATED_MODULE
> Refine Kylin Config

- core-cube/src/main/java/org/apache/kylin/cube/CubeCapabilityChecker.java
- core-cube/src/main/java/org/apache/kylin/cube/model/CubeDesc.java
- core-job/src/main/java/org/apache/kylin/job/execution/ExecutableManager.java
> KYLIN-5027 Fix query for the cube dose not build basecuboid

- build-engine/src/main/java/org/apache/kylin/engine/mr/common/CuboidRecommenderUtil.java
- build/conf/spark-driver-log4j.properties
- core-common/src/main/java/org/apache/kylin/common/util/CliCommandExecutor.java
- core-common/src/main/resources/kylin-defaults.properties
- kylin-it/DEPRECATED_MODULE
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/utils/UpdateMetadataUtil.java
- server-base/src/main/java/org/apache/kylin/rest/job/StorageCleanupJob.java
- server-base/src/test/java/org/apache/kylin/rest/job/StorageCleanupJobTest.java
> Add option to remove stale files under job_tmp for StorageCleanupJob

- website/_docs40/howto/howto_cleanup_storage.cn.md
- website/_docs40/howto/howto_cleanup_storage.md
- website/_docs40/release_notes.md
- website/download/index.cn.md
- website/download/index.md
> Release Kylin 4.0.0

- website/download/index.cn.md
- website/download/index.md
> fix release note

- website/_docs40/install/kylin_docker.cn.md
- website/_docs40/install/kylin_docker.md
> minor fix for kylin4 docker

- website/_data/docs-cn.yml
- website/_data/docs.yml
> Add pushdown item for docs

- docker/dockerfile/standalone/entrypoint.sh
> KYLIN-5083, check hdfs service usability for kylin4 on docker

- core-metadata/src/main/java/org/apache/kylin/measure/percentile/PercentileCounter.java
- core-metadata/src/main/java/org/apache/kylin/measure/percentile/PercentileSerializer.java
- kylin-it/src/test/resources/query/sql_exactly_agg/query11.sql
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/KylinFunctions.scala
- kylin-spark-project/kylin-spark-common/src/main/scala/org/apache/spark/sql/catalyst/expressions/KylinExpresssions.scala
- kylin-spark-project/kylin-spark-common/src/main/spark24/org/apache/spark/sql/catalyst/expressions/ExpressionUtils.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/AggregatePlan.scala
Refer to this: https://github.com/apache/kylin/pull/1619. For percentile function exactly match.
SQL: 
```
SELECT LO_SUPPKEY, percentile_approx(LINEORDER.LO_ORDTOTALPRICE, 0.5) AS ORDER_TOTAL_PRICE
FROM SSB.LINEORDER
GROUP BY LO_SUPPKEY
```
before my change:
after my change:
Please check [Intro to Kylin 4 architecture](https://kylin.apache.org/blog/2021/07/02/Apache …
> KYLIN-5082,exactly match for percentile

- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/application/SparkApplication.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/spark/deploy/StandaloneAppClient.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContext.scala
> KYLIN-5076 Fix spark tracking url missing on spark standalone mode

- .github/workflows/maven.yml
> Modify branch name for kylin3

- kylin-it/src/test/resources/query/sql_percentile/query03.sql
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/SchemaProcessor.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/AggregatePlan.scala
> KYLIN-5117 Support percentile function after aggregate sub query

- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
> Fix the bug of CubeDesc can't be update

- build/bin/prepare_hadoop_dependency.sh
> KYLIN-5906 fix cdh6

- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/spark/application/JobMonitor.scala
> KYLIN-5090 The error message was not printed in class JobWoker

- server-base/src/main/java/org/apache/kylin/rest/controller/CubeController.java
This reverts commit f8f52aff
Please check [Intro to Kylin 4 architecture](https://kylin.apache.org/blog/2021/07/02/Apache-Kylin4-A-new-storage-and-compute-architecture/ …
> Revert "[KYLIN-5032] Not allow change project for a cubeInstance."

- server-base/src/main/java/org/apache/kylin/rest/controller/TableController.java
> Avoid redundant error information

- build/bin/prepare-hadoop-dependency.sh
> KYLIN-5069 Fix

- build/bin/kylin.sh
> KYLIN-5069 Fix wrong file name

- source-hive/src/main/java/org/apache/kylin/source/hive/SparkHiveClient.java
> KYLIN-5069 Fix can't get location

- core-cube/src/main/java/org/apache/kylin/cube/CubeInstance.java
> minor fix for KYLIN-5071

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- source-hive/src/main/java/org/apache/kylin/source/hive/HiveInputBase.java
- source-hive/src/main/java/org/apache/kylin/source/hive/MRHiveDictUtil.java
> KYLIN-5097 configurable hive dict table format

- source-hive/src/main/java/org/apache/kylin/source/hive/MRHiveDictUtil.java
> KYLIN-5097 Fix bug

- build-engine/pom.xml
- cache/pom.xml
- core-common/pom.xml
- core-cube/pom.xml
- core-job/pom.xml
- core-metadata/pom.xml
- core-metrics/pom.xml
- core-storage/pom.xml
- jdbc/pom.xml
- kylin-spark-project/kylin-spark-classloader/pom.xml
- kylin-spark-project/kylin-spark-common/pom.xml
- kylin-spark-project/kylin-spark-engine/pom.xml
- kylin-spark-project/kylin-spark-metadata/pom.xml
- kylin-spark-project/kylin-spark-query/pom.xml
- kylin-spark-project/kylin-spark-test/pom.xml
- kylin-spark-project/pom.xml
- metastore-hbase/pom.xml
- metrics-reporter-hive/pom.xml
- metrics-reporter-kafka/pom.xml
- parquet-assembly/pom.xml
- pom.xml
- query/pom.xml
- server-base/pom.xml
- server/pom.xml
- source-hive/pom.xml
- tool-assembly/pom.xml
- tool/pom.xml
> V4.0.1 release

- website/_dev/index.md
- website/_dev40/index.md
- website/_docs/howto/howto_config_spark_pool.md
- website/_docs/howto/howto_upgrade.md
- website/_docs/security.md
- website/_docs30/security.md
- website/_docs30/tutorial/real_time_olap.md
- website/_docs31/howto/howto_upgrade.md
- website/_docs31/security.md
- website/_docs31/tutorial/real_time_olap.md
- website/_includes/header.cn.html
- website/_includes/header.html
- website/_includes/home_header.cn.html
- website/_includes/home_header.html
- website/_posts/blog/2019-07-01-deep-dive-real-time-olap.md
> Update security page

- website/_docs/install/index.md
- website/_docs31/release_notes.md
- website/download/index.md
> Fix some link

- website/_dev/dev_env.cn.md
- website/_dev/dev_env.md
- website/_dev/howto_setup_frontend_registry.cn.md
- website/_dev/howto_setup_frontend_registry.md
- website/_dev40/dev_env.cn.md
- website/_dev40/dev_env.md
- website/_dev40/howto_setup_frontend_registry.cn.md
- website/_dev40/howto_setup_frontend_registry.md
> Add doc about how to set up front end registry

- website/_dev/howto_setup_frontend_registry.cn.md
- website/_dev/howto_setup_frontend_registry.md
- website/_dev40/howto_setup_frontend_registry.cn.md
- website/_dev40/howto_setup_frontend_registry.md
> Remove code styles

- website/_dev/howto_setup_frontend_registry.cn.md
- website/_dev/howto_setup_frontend_registry.md
- website/_dev40/howto_setup_frontend_registry.cn.md
- website/_dev40/howto_setup_frontend_registry.md
> Fix format

- kylin-it/src/test/resources/query/sql/query115.sql
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/SparderRexVisitor.scala
Support boolean expression (true or false) on where clause. For example `select SELLER_ID,sum(PRICE) from KYLIN_SALES where true  GROUP BY SELLER_ID `
Please check [Intro to Kylin 4 architecture](https://kylin.apache.org/blog/2021/07/02/Apache-Kylin4-A-new-storage-and-compute-architecture/) and [INFRA-22166](https://issues.apache.org/jira/browse/INFRA-22166) if you …
> [KYLIN-5152] support boolean expression on where clause

- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/OptimizeBuildJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeBuildJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeMergeJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/utils/JobMetricsUtils.scala
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/utils/QueryExecutionInterceptListener.scala
> [KYLIN-5121] Make JobMetricsUtils.collectMetrics be working again

- README.md
- bin/init.sh
- engine_utils.py
- kylin_configs.yaml
- readme/advanced_configs.md
- readme/commands.md
- readme/monitor.md
- readme/prerequisites.md
- readme/quick_start_for_multiple_clusters.md
> Fix readme 1

- cloudformation_templates/ec2-cluster-kylin4-template.yaml
- cloudformation_templates/ec2-cluster-kylin4.yaml
- cloudformation_templates/ec2-cluster-rds.yaml
- cloudformation_templates/ec2-cluster-spark-master.yaml
- cloudformation_templates/ec2-cluster-spark-slave-template.yaml
- cloudformation_templates/ec2-cluster-spark-slave.yaml
- cloudformation_templates/ec2-cluster-static-services.yaml
- cloudformation_templates/ec2-cluster-zk.yaml
- cloudformation_templates/ec2-or-emr-vpc.yaml
- constant/yaml_params.py
- instances/aws_instance.py
- kylin_configs.yaml
> # support multiple region for tool

- jdbc/src/test/java/org/apache/kylin/jdbc/DriverTest.java
- query/src/main/java/org/apache/kylin/query/relnode/OLAPContext.java
fix[ KYLIN-4382](https://issues.apache.org/jira/browse/KYLIN-4382) Unable to use DATE type in prepared statements
What types of …
> [KYLIN-4382] Unable to use DATE type in prepared statements in kylin3

- .gitignore
- backup/properties/templates/kylin.properties.template
- backup/scripts/prepare-ec2-env-for-kylin4.sh
- backup/scripts/prepare-ec2-env-for-spark-master.sh
- backup/scripts/prepare-ec2-env-for-spark-slave.sh
- backup/scripts/prepare-ec2-env-for-static-services.sh
- backup/scripts/prepare-ec2-env-for-zk.sh
- cloudformation_templates/ec2-cluster-kylin4-template.yaml
- cloudformation_templates/ec2-cluster-kylin4.yaml
- cloudformation_templates/ec2-cluster-spark-master.yaml
- cloudformation_templates/ec2-cluster-spark-slave-template.yaml
- cloudformation_templates/ec2-cluster-spark-slave.yaml
- cloudformation_templates/ec2-cluster-static-services.yaml
- cloudformation_templates/ec2-cluster-zk.yaml
- cloudformation_templates/ec2-or-emr-vpc.yaml
- clouds/aws.py
- constant/yaml_files.py
- constant/yaml_params.py
- engine_utils.py
- instances/aws_instance.py
- kylin_configs.yaml
- readme/commands.md
- readme/quick_start.md
- utils.py
> Support mdx

- backup/properties/default/kylin.properties
- backup/properties/templates/kylin.properties.template
> Add s3a properties for glue

- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/utils/JobMetricsUtils.scala
> KYLIN-5121 fix key not found: numOutputRows on s3

- utils.py
> Update the size of kylin and spark package

- website/.gitignore
- website/_docs/tutorial/quick_start_for_mdx.cn.md
- website/_docs/tutorial/quick_start_for_mdx.md
> # update quick_start_for_mdx doc

- deploy.py
> # minor fix commands about destroy-all

- clouds/aws.py
- engine.py
- instances/aws_instance.py
- utils/common_utils.py
- utils/engine_utils.py
- utils/progress_bar.py
> # minor fix, add progress bar for logging detail

- README.md
- instances/aws_instance.py
- readme/advanced_configuration.md
- readme/commands.md
- readme/configuration.md
- readme/quick_start.md
- readme/quick_start_for_multiple_clusters.md
> Modify docs

- readme/prerequisites.md
> Fix ssm resource issues on aws global env

- build/deploy/server.xml
- build/script/download-tomcat.sh
- pom.xml
- server/src/main/java/org/apache/kylin/rest/DebugTomcat.java
> KYLIN-5178, upgrade tomcat to 8.5.78

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/java/org/apache/kylin/common/QueryTrace.java
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/ResultPlan.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/util/SparkJobTrace.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/util/SparkJobTraceV2.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/metrics/AppStatus.scala
> KYLIN-5111 Refine query metrics

- core-common/src/main/resources/kylin-defaults.properties
> minor, fix invalid config

- website/_docs/install/kylin_docker.cn.md
- website/_docs/install/kylin_docker.md
> # minor, add note for part of docker

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/builder/CubeSnapshotBuilder.scala
> Kylin 5182

- pom.xml
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
Resolved https://issues.apache.org/jira/browse/KYLIN-3610 …
> chore: bump the version of curator to 5.2.1[KYLIN-3610]

- website/_docs/gettingstarted/quickstart.cn.md
- website/_docs/gettingstarted/quickstart.md
- website/_posts/blog/2022-04-20-kylin4-on-cloud-part1.md
- website/_posts/blog/2022-04-20-kylin4-on-cloud-part2.md
> Add new 220613

- website/_docs24/howto/howto_update_coprocessor.cn.md
- website/_docs31/howto/howto_update_coprocessor.cn.md
- website/_docs31/howto/howto_upgrade.cn.md
> # add howto_upgrade & minor fix error redirection

- server-base/src/main/java/org/apache/kylin/rest/controller/UserController.java
- server-base/src/main/java/org/apache/kylin/rest/security/KylinUserManager.java
> KYLIN-5194, fix deleted user can login when auth cache is valid

- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkCubingJob.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkMergingJob.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkOptimizingJob.java
> KYLIN-5188, fix email notification after cubing and merging job

- kylin-spark-project/kylin-spark-classloader/src/main/java/org/apache/kylin/spark/classloader/TomcatClassLoader.java
> KYLIN-5191 fix Can not see executors on spardar page on AWS EMR 6

- build-engine/src/main/java/org/apache/kylin/engine/mr/CubingJob.java
- build-engine/src/main/java/org/apache/kylin/engine/mr/common/CubeStatsReader.java
- build-engine/src/main/java/org/apache/kylin/engine/mr/common/CuboidRecommenderUtil.java
- build-engine/src/main/java/org/apache/kylin/engine/mr/common/CuboidStatsReaderUtil.java
- build-engine/src/main/java/org/apache/kylin/engine/mr/common/MapReduceUtil.java
- build-engine/src/main/java/org/apache/kylin/engine/mr/common/StatisticsDecisionUtil.java
- core-cube/src/main/java/org/apache/kylin/cube/CubeManager.java
- core-cube/src/main/java/org/apache/kylin/cube/CubeSegment.java
- core-cube/src/main/java/org/apache/kylin/cube/cuboid/DefaultCuboidScheduler.java
- core-cube/src/main/java/org/apache/kylin/cube/kv/CubeDimEncMap.java
- core-job/src/main/java/org/apache/kylin/job/impl/curator/CuratorLeaderSelector.java
- core-metadata/src/main/java/org/apache/kylin/metadata/model/Segments.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/OptimizeBuildJob.java
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/utils/UpdateMetadataUtil.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/builder/CubeMergeAssist.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeBuildJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/CubeMergeJob.java
- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/kylin/engine/spark/job/ParentSourceChooser.scala
- kylin-spark-project/kylin-spark-test/src/test/java/org/apache/kylin/engine/spark2/NOptimizeJobTest.java
> KYLIN-5184, fix cuboid statistic feature

- build/conf/spark-driver-log4j-default.properties
- build/conf/spark-executor-log4j-default.properties
- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-common/src/main/resources/kylin-defaults.properties
- kylin-spark-project/kylin-spark-engine/src/main/java/org/apache/kylin/engine/spark/job/NSparkExecutable.java
- pom.xml
> Minor, using default log4j properties for spark driver and exectutor

- kylin-spark-project/kylin-spark-classloader/src/main/java/org/apache/kylin/spark/classloader/TomcatClassLoader.java
- pom.xml
> Kylin 5195, update spark from 3.1.1 to 3.1.3

- build/sbin/check-1401-kylin-config.sh
- build/sbin/check-3000-clickhouse.sh
- build/sbin/log-rotate-cron.sh
- src/common-booter/src/main/resources/config/config.yaml
- src/common-booter/src/main/resources/config/init.properties
- src/data-loading-booter/src/main/resources/config/config.yaml
- src/data-loading-booter/src/main/resources/config/init.properties
- src/examples/test_case_data/sandbox/kylin.properties
- src/query-booter/src/main/resources/config/config.yaml
- src/query-booter/src/main/resources/config/init.properties
- src/server/src/main/resources/config/config.yaml
- src/server/src/main/resources/config/init.properties
- src/spark-project/engine-spark/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnarCachedBatchSerializer.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ShadeParquetRecordMaterializer.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/spark/utils/ProxyThreadUtils.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/spark/utils/ResourceUtils.scala
- src/spark-project/sparder/src/test/resources/fairscheduler.xml
- src/spark-project/sparder/src/test/resources/query-limit-fair-scheduler.xml.template
- src/spark-project/sparder/src/test/resources/test-query-limit-fair-scheduler.xml
- src/spark-project/spark-common/src/main/scala/org/apache/kylin/engine/spark/utils/LogEx.scala
- src/spark-project/spark-common/src/main/scala/org/apache/kylin/engine/spark/utils/StorageUtils.scala
- src/spark-project/spark-common/src/main/scala/org/apache/spark/sql/catalyst/optimizer/ConvertInnerJoinToSemiJoin.scala
- src/spark-project/spark-common/src/test/scala/org/apache/spark/sql/catalyst/optimizer/ConvertInnerJoinToSemiJoinSuite.scala
- src/tool/src/main/resources/bisync/tds/tableau.mappings.xml
- src/tool/src/main/resources/bisync/tds/tableau.template.xml
> KYLIN-5218, remove wrong license header

- src/spark-project/engine-spark/src/test/java/org/apache/kylin/engine/spark/source/NSparkCubingSourceInputBySparkDataSourceTest.java
- src/spark-project/engine-spark/src/test/java/org/apache/kylin/engine/spark/utils/HiveTransactionTableHelperTest.java
- src/spark-project/engine-spark/src/test/scala/org/apache/spark/sql/newSession/WithKylinExternalCatalog.scala
> KYLIN-5217, fix ut in kylin-engine-spark module

- src/spark-project/engine-build-sdk/src/main/java/io/kyligence/kap/engine/spark/job/EnviromentAdaptor.java
- src/spark-project/engine-build-sdk/src/main/java/io/kyligence/kap/engine/spark/job/IJobProgressReport.java
- src/spark-project/engine-build-sdk/src/main/java/io/kyligence/kap/engine/spark/job/ISparkJobHandler.java
- src/spark-project/engine-build-sdk/src/main/java/io/kyligence/kap/engine/spark/job/ParamsConstants.java
- src/spark-project/engine-build-sdk/src/main/java/io/kyligence/kap/engine/spark/job/SparkAppDescription.java
- src/spark-project/engine-spark/src/main/java/org/apache/kylin/engine/spark/application/SparkApplication.java
- src/spark-project/engine-spark/src/main/java/org/apache/kylin/engine/spark/application/SparkEntry.java
- src/spark-project/engine-spark/src/main/java/org/apache/kylin/engine/spark/source/NSparkCubingSourceInput.java
- src/spark-project/engine-spark/src/main/java/org/apache/kylin/engine/spark/source/NSparkDataSource.java
- src/spark-project/engine-spark/src/main/java/org/apache/kylin/engine/spark/source/NSparkMetadataExplorer.java
- src/spark-project/engine-spark/src/main/java/org/apache/kylin/engine/spark/source/NSparkTable.java
- src/spark-project/engine-spark/src/main/java/org/apache/kylin/engine/spark/source/NSparkTableMeta.java
- src/spark-project/engine-spark/src/main/java/org/apache/kylin/engine/spark/source/NSparkTableMetaBuilder.java
- src/spark-project/engine-spark/src/main/java/org/apache/kylin/engine/spark/source/NSparkTableMetaExplorer.java
- src/spark-project/engine-spark/src/main/java/org/apache/kylin/engine/spark/source/NSparkTableReader.java
- src/spark-project/engine-spark/src/main/java/org/apache/kylin/engine/spark/source/SparkSqlUtil.java
> KYLIN-5217 Create a initial commit

- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/CreateFlatTable.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/DFBuilderHelper.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/DFDictionaryBuilder.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/DFLayoutMergeAssist.java
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/DFTableEncoder.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/DictionaryBuilderHelper.java
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/NonEquiJoinConditionBuilder.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/PartitionFlatTable.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/SegmentFlatTable.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/SnapshotBuilder.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/SnapshotPartitionBuilder.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/StepCheckpoint.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/StepCheckpointSnapshot.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/builder/ZKJaasConfiguration.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/utils/FileNames.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/utils/HDFSUtils.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/utils/SparkConfHelper.java
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/utils/SparkConfRuleConstants.java
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/utils/SparkDataSource.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/utils/SparkUtils.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/kylin/engine/spark/utils/ThreadUtils.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/spark/conf/rule/SparkConfRule.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/spark/utils/LOGUtils.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/spark/utils/ProxyThreadUtils.scala
- src/spark-project/engine-spark/src/main/scala/org/apache/spark/utils/ResourceUtils.scala
> KYLIN-5217 Create a initial commit with build engine

- pom.xml
- server-base/src/main/java/org/apache/kylin/rest/util/Log4jConfigListener.java
- server/pom.xml
- server/src/main/resources/kylinSecurity.xml
- tool/pom.xml
Upgrade spring-core and spring-security's version to fix https://github.com/advisories/GHSA-hh32-7344-cg2f
_Put an `x` in the boxes that …
> KYLIN-5214 upgrade spring-core and spring-security

- build/bin/download-spark.sh
KYLIN-5225 update bin/download-spark.sh to spark 3.1.3
_Put an `x` in the boxes that apply. You can also fill these out after creating the …
> KYLIN-5225 update download-spark.sh to spark 3.1.3

- build/apache_release/build.sh
- build/sbin/spark-test.sh
- src/common-service/src/main/java/org/apache/kylin/rest/service/task/QueryHistoryTaskScheduler.java
- src/core-common/src/main/java/org/apache/kylin/common/KylinConfigExt.java
- src/spark-project/engine-build-sdk/pom.xml
- src/spark-project/sparder/src/main/scala/org/apache/kylin/query/asyncprofiler/AsyncProfilerExecutorPlugin.scala
- src/spark-project/spark-common/pom.xml
Minor fix and Support to run kylin 5.0 on hadoop 3.2.1 platform
_Put an `x` in the boxes that apply. You can also fill these out after …
> KYLIN-5234 support Kylin 5.0 on hadoop 3.2.1

- kystudio/src/components/common/EditProjectConfigDialog/index.vue
- kystudio/src/components/common/EditProjectConfigDialog/store.js
- kystudio/src/components/common/Modal/Modal.vue
- kystudio/src/components/setting/SettingAdvanced/SettingAdvanced.vue
fix add configuration feature in Advanced Settings page
_Put an `x` in the boxes that apply. You can also fill these out after creating …
> KYLIN-5239 fix add configuration in advanced setting page

- kystudio/src/components/project/project_list.vue
- kystudio/src/components/studio/StudioModel/ModelList/ModelActions/modelActions.vue
- kystudio/src/config/spec.js
> KYLIN-5241 fix import models

- src/data-loading-service/src/main/java/org/apache/kylin/rest/service/JobService.java
fix jobs list with sortBy which is `total_duration` instead of `duration`
_Put an `x` in the boxes that apply. You can also fill these out …
> KYLIN-5240 fix the filer of sortBy in jobs api

- website/docs/development/how_to_package.md
Fixed two semantic errors due to the inverse of the original semantics。
> Fixed two semantic errors

- core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- core-cube/src/main/java/org/apache/kylin/cube/RawQueryLastHacker.java
Add a switch to the workaround the `RawQueryLastHacker` handle logic
> KYLIN-5250 work round for no hack aggregation group

- pom.xml
fix kylin run on hadoop with an ClassNotFoundException: org/apache/common/configuration
> KYLIN-5251 fix kylin run on hadoop3

- kystudio/src/components/admin/SystemCapacity/CapacityTopBar.vue
- kystudio/src/components/admin/SystemCapacity/locales.js
- kystudio/src/components/layout/layout_left_right_top.vue
- kystudio/src/main.js
- kystudio/src/store/capacity.js
- kystudio/src/store/index.js
- src/core-common/src/main/java/org/apache/kylin/common/util/BasicEmailNotificationContent.java
- src/tool/src/main/java/org/apache/kylin/tool/RollbackTool.java
> Kylin 5249

- dev-support/sandbox/runConfigurations/BootstrapServer_docker_sandbox_.xml
- dev-support/sandbox/sandbox.sh
> Fix IDEA run configuration

- build/release/package.sh
> Minor fix package.sh for download spark/influxdb/grafana

- build/release/package.sh
fix kylin 5.0 compile script in /kylin/build/release/package.sh
> fix kylin 5.0 compile script

- build/bin/sample.sh
- build/release/release.sh
- src/docker/.gitignore
- src/docker/all_in_one/Dockerfile_hadoop
- src/docker/all_in_one/Dockerfile_kylin
- src/docker/all_in_one/build_image.sh
- src/docker/all_in_one/conf/hadoop/capacity-scheduler.xml
- src/docker/all_in_one/conf/hadoop/core-site.xml
- src/docker/all_in_one/conf/hadoop/hdfs-site.xml
- src/docker/all_in_one/conf/hadoop/mapred-site.xml
- src/docker/all_in_one/conf/hadoop/yarn-site.xml
- src/docker/all_in_one/conf/hive/hive-site.xml
- src/docker/all_in_one/conf/kylin/kylin.properties.override
- src/docker/all_in_one/conf/zk/zoo.cfg
- src/docker/all_in_one/entrypoint.sh
- src/docker/all_in_one/scripts/install_mysql.sh
> KYLIN-5266 add docker image for kylin5

- website/docs/development/how_to_contribute.md
Improve the how_to_contribute.md page. Better wordings and smoother sentences.
> [doc] Improve the how_to_contribute.md

- core-cube/src/main/java/org/apache/kylin/cube/cuboid/CuboidCLI.java
- docker/README-cluster.md
- docker/README-standalone.md
- docker/README.md
- docker/build_standalone_image.sh
> Docker update

- core-cube/src/main/java/org/apache/kylin/cube/cuboid/CuboidCLI.java
>  [tyro] fix typo in CuboidCLI

- kylin-spark-project/kylin-spark-query/src/main/java/org/apache/kylin/query/pushdown/SparkSubmitter.java
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/SparkEngine.java
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/kylin/query/runtime/plans/ResultPlan.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContext.scala
- kylin-spark-project/kylin-spark-query/src/main/scala/org/apache/spark/sql/SparderContextFacade.scala
> KYLIN-5271 Query memory leaks

- website/docs/development/how_to_write_doc.md
> Remove unexpected .md

- src/core-common/src/main/java/org/apache/kylin/common/ICachedExternalConfigLoader.java
- src/core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- src/core-common/src/main/java/org/apache/kylin/common/KylinConfigExt.java
- src/core-common/src/main/java/org/apache/kylin/common/KylinExternalConfigLoader.java
- src/core-common/src/main/java/org/apache/kylin/common/PropertiesDelegate.java
- src/core-common/src/main/java/org/apache/kylin/common/util/CompositeMapView.java
> Improve performance of getSubstitutor

- core-common/src/main/java/org/apache/kylin/common/KylinConfig.java
Improve performance of getInstanceFromEnv to avoid unnecessary synchronization
> improve performance of getInstanceFromEnv

- kylin-spark-project/kylin-spark-engine/src/main/scala/org/apache/spark/application/JobWorkSpace.scala
Due to KYLIN-4895, on Yarn 3.X.X status code not handled by spark job. It's always got SUCEEDED state.
> KYLIN-5008: Status code is not handled correctly by the Kylin job.

- dev-support/unit_testing.sh
- src/common-server/src/test/java/org/apache/kylin/rest/controller/NEpochControllerTest.java
- src/core-common/src/main/java/org/apache/kylin/common/KylinConfig.java
- src/core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- src/core-common/src/main/java/org/apache/kylin/common/PropertiesDelegate.java
- src/core-common/src/main/java/org/apache/kylin/common/SystemPropertiesCache.java
- src/core-common/src/main/java/org/apache/kylin/common/util/Unsafe.java
- src/core-common/src/test/java/org/apache/kylin/common/AbstractTestCase.java
- src/core-common/src/test/java/org/apache/kylin/common/KylinConfigBaseTest.java
- src/core-common/src/test/java/org/apache/kylin/common/KylinConfigTest.java
- src/core-common/src/test/java/org/apache/kylin/common/PropertiesDelegateTest.java
- src/core-common/src/test/java/org/apache/kylin/junit/MetadataExtension.java
- src/core-common/src/test/java/org/apache/kylin/junit/OverwritePropExtension.java
- src/data-loading-server/src/test/java/org/apache/kylin/rest/controller/StreamingJobControllerTest.java
- src/datasource-service/src/test/java/org/apache/kylin/rest/service/StreamingTableServiceTest.java
- src/metadata-server/src/test/java/org/apache/kylin/rest/controller/KafkaControllerTest.java
- src/metadata-server/src/test/java/org/apache/kylin/rest/controller/StreamingTableControllerTest.java
- src/server-base/src/test/java/org/apache/kylin/rest/controller/open/OpenStreamingJobControllerTest.java
- src/source-hive/src/test/java/org/apache/kylin/source/hive/HiveCmdBuilderTest.java
- src/spark-project/engine-spark/src/test/java/org/apache/kylin/engine/spark/utils/HiveTransactionTableHelperTest.java
- src/streaming-service/src/test/java/org/apache/kylin/rest/service/StreamingJobServiceTest.java
> Refine patch from KYLIN-5256

- website/docs/development/how_to_contribute.md
- website/docs/development/how_to_debug_kylin_in_ide.md
- website/docs/development/how_to_debug_kylin_in_local.md
Improve a few doc about how to setup dev env on Windows.
> Improve doc about Windows dev env setup

- core-common/pom.xml
- core-common/src/main/java/org/apache/kylin/common/persistence/JDBCResourceStore.java
- core-common/src/main/java/org/apache/kylin/common/persistence/ResourceTool.java
- core-common/src/main/resources/metadata-jdbc-postgresql.properties
- pom.xml
> Kylin 5181 new

- kystudio/src/components/common/DataSourceModal/store.js
> [KYLIN-5288] set sampling button 'off' by default

- kystudio/src/components/monitor/batchJobs/jobErrorDetail.vue
- kystudio/src/components/user/login.vue
Fix the incorrect jump URL for Kylin5
> Minor fix related url for kylin5

- website/docs/deployment/on-premises/prerequisite.md
- website/docs/modeling/model_design/computed_column.md
- website/docs/operations/access-control/data-access-control/intro.md
- website/docs/operations/access-control/group_management.md
- website/docs/operations/access-control/user_management.md
- website/docs/operations/monitoring/influxdb/influxdb_maintenance.md
- website/docs/operations/system-operation/cli_tool/metadata_tool/metadata_backup_restore.md
- website/docs/query/insight/insight.md
- website/docs/quickstart/expert_mode_tutorial.md
> Minor fix missing url

- website/docs/query/history.md
> Minor fix some broken pages

- website/docs/integration/driver/intro.md
- website/docs/integration/driver/jdbc.md
- website/sidebars.js
> KYLIN-5297 add jdbc module

- website/docs/quickstart/intro.md
- website/docusaurus.config.js
- website/src/components/HomepageFeatures/index.js
- website/src/pages/index.js
Minor fix Kylin 5.0 doc base URL and homepage
> Minor fix doc5.0 base url and homepage

- website/docusaurus.config.js
> Minor fix logo image path

- website/_includes/header.cn.html
- website/_includes/header.html
- website/_includes/home_header.cn.html
- website/_includes/home_header.html
> Minor add kylin 5 document

- website/_includes/header.cn.html
- website/_includes/home_header.cn.html
MInor fix chinese version doc for kylin 4
> Minor fix chinese version doc for kylin 4

- kystudio/src/components/setting/SettingBasic/SettingBasic.vue
Fix when the user saves basic settings with irrelevant information
> KYLIN-5299 fix save basic settings with irrelevant information

- website/docs/modeling/data_modeling.md
> Minor remove useless image

- src/core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- src/core-common/src/main/java/org/apache/kylin/common/persistence/metadata/EpochStore.java
- src/core-common/src/main/java/org/apache/kylin/common/persistence/metadata/FileEpochStore.java
- src/core-common/src/main/java/org/apache/kylin/common/persistence/metadata/JdbcAuditLogStore.java
- src/core-common/src/main/java/org/apache/kylin/common/persistence/metadata/JdbcEpochStore.java
- src/core-common/src/main/java/org/apache/kylin/common/persistence/metadata/jdbc/JdbcUtil.java
- src/core-common/src/test/java/org/apache/kylin/common/KylinConfigBaseTest.java
- src/core-common/src/test/java/org/apache/kylin/common/persistence/metadata/epochstore/AbstractEpochStoreTest.java
- src/core-common/src/test/java/org/apache/kylin/common/persistence/metadata/epochstore/JdbcEpochStoreTest.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/epoch/EpochManager.java
- src/core-metadata/src/test/java/org/apache/kylin/metadata/epoch/EpochManagerTest.java
Co-authored-by: Jiale He <jialehebo55@gmail.com>
If this is a relatively large or complex change, kick off the discussion at user@kylin.apache.org or dev@kylin.apache.org by explaining why you chose the solution you did and what alternatives you …
> KYLIN-5308 add transaction timeout when epoch renew

- src/core-metadata/src/main/java/org/apache/kylin/metadata/epoch/EpochOrchestrator.java
- src/core-metadata/src/test/java/org/apache/kylin/metadata/epoch/EpochOrchestratorTest.java
- src/server/pom.xml
- src/server/src/main/java/org/apache/kylin/rest/discovery/KylinServiceDiscoveryCache.java
- src/server/src/test/java/org/apache/kylin/rest/discovery/KylinServiceDiscoveryCacheTest.java
> KYLIN-5379 Disable epoch renew when epoch checker disabled

- src/common-service/src/main/java/org/apache/kylin/rest/service/MetadataBackupService.java
- src/core-common/src/main/java/org/apache/kylin/common/persistence/metadata/JdbcAuditLogStore.java
- src/job-service/src/main/java/org/apache/kylin/rest/service/ScheduleService.java
- src/job-service/src/test/java/org/apache/kylin/rest/service/ScheduleServiceTest.java
Co-authored-by: Jiale He <jiale.he@kyligence.io>
If this is a relatively large or complex change, kick off the discussion at user@kylin.apache.org or dev@kylin.apache.org by explaining why you chose the solution you did and what alternatives you …
> KYLIN-5378 Add logs when delete auditlog, to improve the diagnosability

- src/spark-project/engine-spark/src/main/java/org/apache/kylin/engine/spark/application/SparkApplication.java
- src/spark-project/engine-spark/src/main/scala/org/apache/spark/application/JobWorker.scala
- src/spark-project/engine-spark/src/test/scala/org/apache/spark/application/TestJobMonitor.scala
- src/spark-project/engine-spark/src/test/scala/org/apache/spark/application/TestJobWorker.scala
If the Job occurs permission exception ,then let the Job failed  instead of retry.
If this is a relatively large or complex change, kick off the discussion at user@kylin.apache.org or dev@kylin.apache.org by explaining why you chose the solution you …
> KYLIN-5372 If the Job occurs permission exception error ,then let the Job failed instead of retry

- src/common-service/src/main/java/org/apache/kylin/rest/service/AccessService.java
- src/common-service/src/main/java/org/apache/kylin/rest/service/ProjectService.java
- src/common-service/src/test/java/org/apache/kylin/rest/service/AccessServiceTest.java
- src/common-service/src/test/java/org/apache/kylin/rest/service/UserAclServiceTest.java
> KYLIN-5373 fix user/usergroup display error in project acl

- src/query-common/src/main/java/org/apache/kylin/query/relnode/ContextUtil.java
Co-authored-by: hui.wang <hui.wang@kyligence.io>
If this is a relatively large or complex change, kick off the discussion at user@kylin.apache.org or dev@kylin.apache.org by explaining why you chose the solution you did and what alternatives you …
> KYLIN-5382 Block the agg pushdown when there is a non RexCall in the project

- src/modeling-service/src/main/java/org/apache/kylin/rest/response/FusionModelResponse.java
- src/modeling-service/src/main/java/org/apache/kylin/rest/service/FusionModelService.java
- src/modeling-service/src/test/java/org/apache/kylin/rest/service/FusionModelServiceTest.java
> KYLIN-5383 remove baseIndex for streaming when update fusion model

- src/common-service/src/main/java/org/apache/kylin/rest/cache/RedisCache.java
KYLIN-5384 fix nativeQueryRealization deserialization failed,fix query timeout when redis connection failed
If this is a relatively large or complex change, kick off the discussion at user@kylin.apache.org or dev@kylin.apache.org by explaining why you …
> KYLIN-5384 fix nativeQueryRealization deserialization failed,fix query timeout when redis connection failed

- src/core-common/src/main/java/org/apache/kylin/common/KylinConfigBase.java
- src/query-common/src/main/java/org/apache/kylin/query/util/KapQueryUtil.java
- src/query/src/main/java/org/apache/kylin/query/engine/QueryRoutingEngine.java
- src/query/src/test/java/org/apache/kylin/query/engine/QueryRoutingEngineTest.java
- src/query/src/test/java/org/apache/kylin/query/util/QueryUtilTest.java
Co-authored-by: fanfanAlice <18611532909@163.com>
If this is a relatively large or complex change, kick off the discussion at user@kylin.apache.org or dev@kylin.apache.org by explaining why you chose the solution you did and what alternatives you …
> KYLIN-5385 add bigquery pushdown

- src/common-service/src/main/java/org/apache/kylin/rest/service/task/QueryHistoryTaskScheduler.java
- src/common-service/src/test/java/org/apache/kylin/rest/service/task/QueryHistoryTaskSchedulerTest.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/cube/model/NDataflow.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/model/FusionModel.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/model/FusionModelManager.java
- src/core-metadata/src/main/java/org/apache/kylin/metadata/query/QueryHistory.java
- src/core-metadata/src/test/java/org/apache/kylin/metadata/cube/model/NDataflowManagerTest.java
- src/core-metadata/src/test/java/org/apache/kylin/metadata/streaming/FusionModelManagerTest.java
- src/job-service/src/main/java/org/apache/kylin/rest/service/AsyncTaskService.java
- src/query-service/src/main/java/org/apache/kylin/rest/service/QueryCacheManager.java
- src/query-service/src/main/java/org/apache/kylin/rest/service/QueryHistoryService.java
- src/query-service/src/main/java/org/apache/kylin/rest/service/QueryService.java
- src/query-service/src/test/java/org/apache/kylin/rest/service/QueryHistoryServiceTest.java
- src/query-service/src/test/java/org/apache/kylin/rest/service/QueryServiceTest.java
> KYLIN-5367  fix updata layoutHits error in fusion model

- website/docs/datasource/logical_view.md
- website/docs/restapi/async_query_api.md
- website/sidebars.js
> Doc KYLIN-5447, KYLIN-5454

- build-engine/src/main/java/org/apache/kylin/engine/mr/IMROutput.java
- build-engine/src/main/java/org/apache/kylin/engine/mr/common/AbstractHadoopJob.java
> Correcting spelling mistakes

- src/common-service/src/main/java/org/apache/kylin/rest/config/AppInitializer.java
> [KYLIN-5595] Launch Job Node not initialize spark session issue

- src/query-service/src/test/java/org/apache/kylin/rest/service/DashboardServiceTest.java
> [KYLIN-5596] fix kylin5 dashboard test units error issue

- kystudio/src/components/studio/StudioModel/ModelList/index.vue
- kystudio/src/util/index.js
> KYLIN-5667 fix model list page issue

- kystudio/src/components/common/CustomTransferData/TransferData.vue
- kystudio/src/components/query/query_result.vue
- kystudio/src/components/studio/StudioModel/TableIndexEdit/tableindex_edit.vue
> KYLIN-5685 fix query issue

- kystudio/src/components/query/query_result.vue
> KYLIN-5686 query result open ModelAggregate and IndexDetails issue
